Repository withspectrum/spectrum, pull requests merged in 2018-12, with the labels that each got.

#4394 Trigger CI
  api/index.js
  cypress/integration/channel/view/members_spec.js
  cypress/integration/thread_spec.js
  package.json
  yarn.lock
Labels: WIP: Building

#4396 Remove .only on e2e, extra comment in api
  api/index.js
  cypress/integration/thread_spec.js
Labels: Ready for Review

#4384 Format online counts to locale
  src/components/profile/community.js
  src/views/channel/index.js
Labels: Ready for Review

#4397 Fix email updating flow
  api/mutations/user/editUser.js
  api/queries/user/email.js
  src/views/userSettings/components/editForm.js
  src/views/userSettings/index.js
Labels: Ready for Review

#4407 feat: fallback ui for server crashes (500 errors)
  hyperion/renderer/index.js
Labels: Ready for Review

#4382 Fix channel member list items should init a dm, add a test
  cypress/integration/channel/settings/members_spec.js
  cypress/integration/channel/view/members_spec.js
  cypress/integration/thread_spec.js
  flow-typed/npm/electron-is-dev_vx.x.x.js
  flow-typed/npm/electron-updater_vx.x.x.js
  flow-typed/npm/electron_vx.x.x.js
  src/views/channelSettings/components/channelMembers.js
  src/views/channelSettings/components/overview.js
  src/views/community/components/memberGrid.js
  src/views/directMessages/containers/newThread.js
Labels: Ready for Review

#4409 Remove getspectrum as a toxicity check provider
  api/mutations/thread/publishThread.js
  athena/queues/moderationEvents/message.js
  athena/queues/moderationEvents/perspective.js
  athena/queues/moderationEvents/spectrum.js
  athena/queues/moderationEvents/thread.js
  email-templates/adminToxicContent.html
  hermes/queues/send-admin-toxic-content-email.js
  now.json
Labels: Ready for Review

#4411 Remove a .only in tests, check tests pass
  cypress/integration/thread_spec.js
Labels: Ready for Review

#4410 2.4.80
  api/mutations/thread/publishThread.js
  api/mutations/user/editUser.js
  api/package.json
  api/queries/user/email.js
  api/yarn.lock
  athena/queues/moderationEvents/message.js
  athena/queues/moderationEvents/perspective.js
  athena/queues/moderationEvents/spectrum.js
  athena/queues/moderationEvents/thread.js
  cypress/integration/channel/settings/members_spec.js
  cypress/integration/channel/view/members_spec.js
  cypress/integration/thread_spec.js
  email-templates/adminToxicContent.html
  flow-typed/npm/electron-is-dev_vx.x.x.js
  flow-typed/npm/electron-updater_vx.x.x.js
  flow-typed/npm/electron_vx.x.x.js
  hermes/queues/send-admin-toxic-content-email.js
  hyperion/index.js
  hyperion/renderer/index.js
  now.json
  package.json
  shared/db/db.js
  shared/middlewares/toobusy.js
  src/components/icons/index.js
  src/components/profile/community.js
  src/routes.js
  src/views/announcementBanner/index.js
  src/views/announcementBanner/style.js
  src/views/channel/index.js
  src/views/channelSettings/components/channelMembers.js
  src/views/channelSettings/components/overview.js
  src/views/community/components/memberGrid.js
  src/views/directMessages/containers/newThread.js
  src/views/userSettings/components/editForm.js
  src/views/userSettings/index.js
  yarn.lock
Labels: Ready for Review

#4417 Migration to remove old usersNotifications
  api/migrations/20181205171559-remove-old-users-notifications.js
  chronos/index.js
  chronos/jobs/index.js
  chronos/models/usersNotifications.js
  chronos/queues/constants.js
  chronos/queues/remove-seen-usersNotifications.js
  shared/bull/queues.js
  shared/bull/types.js
Labels: Ready for Review

#4419 Uncomment pool garbage collection
  api/migrations/seed/index.js
  api/package.json
  api/yarn.lock
  flow-typed/npm/rethinkhaberdashery_vx.x.x.js
  package.json
  shared/changefeed-utils/index.js
  shared/db/db.js
  shared/testing/db.js
  yarn.lock
Labels: Ready for Review

#4421 Adds maintenance mode back
  api/schema.js
  config-overrides.js
  hyperion/renderer/index.js
  src/components/maintenance/index.js
  src/components/redirectHandler/index.js
  src/index.js
  src/routes.js
Labels: Ready for Review

#4412 Move to Compose & add SSL support to database connections
  .npmignore
  now.json
  package.json
  shared/db/db.js
  yarn.lock
Labels: WIP: Needs Testing

#4426 fix(cypress): grab the found user's id
  cypress/support/commands.js
Labels: Ready for Review

#4424 Use default db configs, upgrade node version in api
  api/package.json
  shared/db/db.js
Labels: Ready for Review

#4423 Console error actual errors instead of getting swallowed by Raven rate lims
  athena/queues/channel-notification.js
  athena/queues/community-invite.js
  athena/queues/community-notification.js
  athena/queues/create-thread-notification-email.js
  athena/queues/direct-message-notification.js
  athena/queues/mention-notification.js
  athena/queues/new-message-in-thread/index.js
  athena/queues/private-channel-request-approved.js
  athena/queues/private-channel-request-sent.js
  athena/queues/private-community-request-approved.js
  athena/queues/private-community-request-sent.js
  athena/queues/reaction-notification.js
  athena/queues/send-push-notifications.js
  athena/queues/send-slack-invitations.js
  athena/queues/thread-notification.js
  athena/queues/thread-reaction-notification.js
  athena/queues/track-user-thread-last-seen.js
  athena/utils/push-notifications/send-expo-push-notifications.js
Labels: Ready for Review

#4428 Temporarily disable chronos usersNotifications cleanup
  chronos/queues/remove-seen-usersNotifications.js
Labels: Ready for Review

#4425 Move waterfall to be served from app code not s3
  public/img/waterfall.png
  src/views/pages/features/index.js
Labels: Ready for Review

#4430 Fix cron schedule
  chronos/jobs/index.js
  chronos/queues/remove-seen-usersNotifications.js
Labels: Ready for Review

#4431 Reduce load on api from websocket reconnections
  src/hooks/useConnectionRestored.js
Labels: Ready for Review

#4398 Dynamic GitHub username fetch
  .eslintrc.js
  api/authentication.js
  api/package.json
  api/queries/channel/metaData.js
  api/queries/community/metaData.js
  api/yarn.lock
  flow-typed/npm/ioredis_v3.x.x.js
  flow-typed/npm/ioredis_vx.x.x.js
  now.json
  package.json
  shared/graphql-cache-keys.js
  src/components/githubProfile/index.js
  src/components/profile/community.js
  src/views/channel/index.js
  src/views/channelSettings/components/channelMembers.js
  src/views/community/components/memberGrid.js
  src/views/directMessages/containers/newThread.js
  src/views/userSettings/components/editForm.js
  yarn.lock
Labels: Ready for Review

#4433 Fix edit action bar to bottom of text area
  src/views/thread/components/actionBar.js
  src/views/thread/style.js
Labels: Ready for Review

#4435 Remove GitHub announcement banner
  src/routes.js
  src/views/announcementBanner/index.js
  src/views/announcementBanner/style.js
Labels: Ready for Review

#4445 Track database connection count and queue size in DataDog
  shared/db/db.js
  shared/middlewares/statsd.js
  shared/statsd.js
Labels: Ready for Review

#4436 Limit digests to just 20 threads
  chronos/queues/digests/processIndividualDigest.js
  email-templates/weeklyDigest.html
  hermes/queues/send-digest-email.js
  shared/bull/types.js
Labels: Ready for Review

#4446 Frontend perf
  api/migrations/20181211181146-add-usersthreads-user-id-and-participant-index.js
  api/models/channel.js
  api/models/community.js
  api/models/thread.js
  api/queries/community/memberGrowth.js
  api/queries/community/metaData.js
  api/queries/thread/reactions.js
  api/types/User.js
  shared/db/queries/user.js
  src/views/authViewHandler/index.js
  src/views/user/index.js
Labels: Ready for Review

#4375 Privacy Policy and Terms of Service update
  src/views/pages/privacy/index.js
  src/views/pages/terms/index.js
Labels: Ready for Review

#4451 Add ssl cert when running prod migrations
  api/migrations/config.js
Labels: Ready for Review

#4453 Fix flow
  api/migrations/config.js
Labels: Ready for Review

#4457 Consoles instead of debugs
  analytics/queues/identify-analytics.js
  analytics/queues/track-analytics.js
  analytics/utils/identify.js
  analytics/utils/track.js
  api/migrations/seed/index.js
  api/queries/thread/messageConnection.js
  athena/utils/get-email-status.js
  chronos/queues/coreMetrics/activeCommunityAdminReport.js
  chronos/queues/coreMetrics/index.js
  chronos/queues/digests/dailyDigest.js
  chronos/queues/digests/processDigest.js
  chronos/queues/digests/processIndividualDigest.js
  chronos/queues/digests/weeklyDigest.js
  chronos/queues/remove-seen-usersNotifications.js
  mercury/queues/processReputationEvent.js
  vulcan/queues/index.js
Labels: Ready for Review

#4459 More hermes console logs
  hermes/index.js
  hermes/queues/send-new-thread-email.js
  shared/bull/create-queue.js
Labels: Ready for Review

#4460 Update packages
  analytics/package.json
  analytics/yarn.lock
  api/index.js
  api/package.json
  api/yarn.lock
  chronos/package.json
  mercury/package.json
  now.json
  package.json
  shared/bull/create-queue.js
  vulcan/package.json
  yarn.lock
Labels: Ready for Review

#4464 [HOTFIX] Fix email jobs never completing
  hermes/send-email.js
Labels: Ready for Review

#4466 Use array of email objects for sending emails
  analytics/package.json
  analytics/yarn.lock
  api/package.json
  api/yarn.lock
  athena/package.json
  athena/queues/send-slack-invitations.js
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  flow-typed/npm/bluebird_vx.x.x.js
  hermes/index.js
  hermes/package.json
  hermes/queues/send-admin-active-community-report-email.js
  hermes/queues/send-admin-community-created-email.js
  hermes/queues/send-admin-slack-import-email.js
  hermes/queues/send-admin-toxic-content-email.js
  hermes/queues/send-admin-user-reported-email.js
  hermes/queues/send-admin-user-spamming-threads-notification-email.js
  hermes/queues/send-administrator-email-validation-email.js
  hermes/queues/send-community-invite-email.js
  hermes/queues/send-digest-email.js
  hermes/queues/send-email-validation-email.js
  hermes/queues/send-mention-message-email.js
  hermes/queues/send-mention-thread-email.js
  hermes/queues/send-new-community-welcome-email.js
  hermes/queues/send-new-direct-message-email.js
  hermes/queues/send-new-message-email.js
  hermes/queues/send-new-thread-email.js
  hermes/queues/send-private-channel-request-approved-email.js
  hermes/queues/send-private-channel-request-sent-email.js
  hermes/queues/send-private-community-request-approved-email.js
  hermes/queues/send-private-community-request-sent-email.js
  hermes/queues/send-user-welcome-email.js
  hermes/queues/sendgrid-webhook-events.js
  hermes/send-email.js
  hermes/yarn.lock
  mercury/package.json
  mercury/yarn.lock
  package.json
  shared/bull/types.js
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review

#4473 More aggressively reconnect changefeeds
  shared/changefeed-utils/index.js
Labels: Ready for Review

#4470 Dont use createwritequery for setuseronline
  shared/db/queries/user.js
Labels: Ready for Review

#4477 Fix chronos
  chronos/index.js
  chronos/yarn.lock
  yarn.lock
Labels: Ready for Review

#4481 Attempt to fix bug in dm view
  api/models/thread.js
  api/queries/directMessageThread/participants.js
Labels: Ready for Review

#4483 Shorter time to timestamp while grouping messages
  shared/clients/group-messages.js
  src/views/dashboard/style.js
Labels: Ready for Review

#4484 2.5.3
  api/models/thread.js
  api/package.json
  api/queries/directMessageThread/participants.js
  api/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  package.json
  shared/clients/group-messages.js
  src/components/fullscreenView/style.js
  src/components/withCurrentUser/index.js
  src/views/dashboard/style.js
Labels: Ready for Review

#4486 Dm bugs
  api/loaders/create-loader.js
  api/migrations/seed/default/directMessageThreads.js
  api/migrations/seed/default/index.js
  api/migrations/seed/default/notifications.js
  api/migrations/seed/default/usersDirectMessageThreads.js
  api/migrations/seed/default/usersNotifications.js
  api/routes/middlewares/index.js
  api/utils/permissions.js
  cypress/integration/messages_spec.js
  package.json
  shared/graphql/queries/directMessageThread/getCurrentUserDMThreadConnection.js
  shared/middlewares/logging.js
  shared/testing/data.js
  src/components/granularUserProfile/index.js
  src/components/infiniteScroll/index.js
  src/views/directMessages/components/header.js
  src/views/directMessages/components/messageThreadListItem.js
  src/views/directMessages/components/messages.js
  src/views/directMessages/components/style.js
  src/views/directMessages/components/threadsList.js
  src/views/directMessages/containers/existingThread.js
  src/views/directMessages/containers/index.js
  src/views/directMessages/containers/newThread.js
  src/views/directMessages/style.js
  src/views/navbar/components/messagesTab.js
  yarn.lock
Labels: Ready for Review

#4488 v2.5.4
  api/loaders/create-loader.js
  api/migrations/seed/default/directMessageThreads.js
  api/migrations/seed/default/index.js
  api/migrations/seed/default/notifications.js
  api/migrations/seed/default/usersDirectMessageThreads.js
  api/migrations/seed/default/usersNotifications.js
  api/routes/middlewares/index.js
  api/utils/permissions.js
  cypress/integration/messages_spec.js
  package.json
  shared/graphql/queries/directMessageThread/getCurrentUserDMThreadConnection.js
  shared/middlewares/logging.js
  shared/testing/data.js
  src/components/granularUserProfile/index.js
  src/components/infiniteScroll/index.js
  src/views/directMessages/components/header.js
  src/views/directMessages/components/messageThreadListItem.js
  src/views/directMessages/components/messages.js
  src/views/directMessages/components/style.js
  src/views/directMessages/components/threadsList.js
  src/views/directMessages/containers/existingThread.js
  src/views/directMessages/containers/index.js
  src/views/directMessages/containers/newThread.js
  src/views/directMessages/style.js
  src/views/navbar/components/messagesTab.js
  yarn.lock
Labels: Ready for Review

#4493 Reenable toobusy
  shared/middlewares/toobusy.js
Labels: Ready for Review

#4490 Disable GraphQL playground in production
  api/apollo-server.js
Labels: Ready for Review

#4444 Add StatsD tracking
  analytics/package.json
  analytics/yarn.lock
  api/apollo-server.js
  api/index.js
  api/package.json
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  flow-typed/npm/datadog-metrics_vx.x.x.js
  flow-typed/npm/express-hot-shots_vx.x.x.js
  flow-typed/npm/hot-shots_vx.x.x.js
  hermes/package.json
  hermes/yarn.lock
  hyperion/index.js
  mercury/package.json
  mercury/yarn.lock
  now.json
  package.json
  shared/db/db.js
  shared/middlewares/logging.js
  shared/middlewares/statsd.js
  shared/statsd.js
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review, WIP: Building

#4497 Upgrade apollo-cache-inmemory
  package.json
  yarn.lock
Labels: Ready for Review

#4498 Use official latest version of apollo inmemory
  package.json
  yarn.lock
Labels: Ready for Review

#4500 Better CodeSandbox support
  src/components/rich-text-editor/Embed.js
  src/helpers/regexps.js
  src/views/explore/collections.js
Labels: Ready for Review

#4499 2.5.5
  analytics/package.json
  analytics/yarn.lock
  api/apollo-server.js
  api/index.js
  api/package.json
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  docs/workers/background-jobs.md
  flow-typed/npm/datadog-metrics_vx.x.x.js
  flow-typed/npm/express-hot-shots_vx.x.x.js
  flow-typed/npm/hot-shots_vx.x.x.js
  hermes/package.json
  hermes/yarn.lock
  hyperion/index.js
  mercury/package.json
  mercury/yarn.lock
  now.json
  package.json
  shared/db/db.js
  shared/middlewares/logging.js
  shared/middlewares/statsd.js
  shared/middlewares/toobusy.js
  shared/statsd.js
  src/components/rich-text-editor/Embed.js
  src/helpers/regexps.js
  src/views/directMessages/containers/newThread.js
  src/views/explore/collections.js
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review

#4501 Add packages for deploys
  analytics/package.json
  analytics/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  mercury/package.json
  mercury/yarn.lock
  vulcan/package.json
  vulcan/yarn.lock
Labels: Ready for Review

#4505 Track job queue metrics
  shared/bull/create-queue.js
Labels: WIP: Building
