Repository withspectrum/spectrum, pull requests merged in 2018-06, with the labels that each got.

#3237 Open all desktop app links in browser
  desktop/src/config.js
  desktop/src/main.js
  desktop/src/menu.js
  src/components/linkPreview/index.js
  src/components/profile/community.js
  src/components/threadFeed/index.js
  src/views/dashboard/components/inboxThread.js
  src/views/userSettings/components/notificationSettings.js
Labels: Ready for Review

#3238 Ensure onerror handler exists in username search
  src/components/usernameSearch/index.js
Labels: Ready for Review

#3235 Adds menu item and shortcut to copy current url to the clipboard
  desktop/src/menu.js
Labels: Ready for Review

#3224 Add standard right click menu to desktop app
  desktop/package.json
  desktop/src/main.js
  desktop/yarn.lock
  flow-typed/npm/electron-window-state_vx.x.x.js
Labels: Ready for Review

#3242 Remove desktop continuous deployment
  .circleci/config.yml
  desktop/deployment.md
Labels: Ready for Review, WIP: Needs Testing

#3247 2.4.4
  .circleci/config.yml
  desktop/deployment.md
  desktop/package.json
  desktop/src/config.js
  desktop/src/main.js
  desktop/src/menu.js
  desktop/yarn.lock
  flow-typed/npm/electron-window-state_vx.x.x.js
  package.json
  src/components/linkPreview/index.js
  src/components/profile/community.js
  src/components/threadFeed/index.js
  src/components/usernameSearch/index.js
  src/views/communityMembers/index.js
  src/views/dashboard/components/inboxThread.js
  src/views/notifications/components/notificationDropdownList.js
  src/views/thread/components/messages.js
  src/views/thread/container.js
  src/views/userSettings/components/notificationSettings.js
Labels: Ready for Review

#3248 Fix SSR
  config-overrides.js
  hyperion/index.js
  hyperion/renderer/index.js
  package.json
  src/components/buttons/index.js
  src/components/infiniteScroll/index.js
  src/components/upsell/joinChannel.js
  src/index.js
  yarn.lock
Labels: Ready for Review, WIP: Building

#3249 2.4.5
  config-overrides.js
  hyperion/index.js
  hyperion/renderer/index.js
  package.json
  src/components/buttons/index.js
  src/components/infiniteScroll/index.js
  src/components/upsell/joinChannel.js
  src/index.js
  yarn.lock
Labels: Ready for Review

#3261 Fix mobile onpress handler
  mobile/components/Facepile/index.js
  mobile/components/InfiniteList/index.js
  mobile/components/Lists/CommunityListItem.js
  mobile/components/Lists/DirectMessageListItem/index.js
  mobile/components/Lists/ListItem.js
  mobile/components/Lists/NotificationListItem.js
  mobile/components/Lists/ThreadListItem/ThreadCommunityInfo.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/Lists/UserListItem.js
  mobile/components/Messages/Author.js
  mobile/components/Messages/index.js
  mobile/components/ThreadFeed/index.js
  mobile/package.json
  mobile/utils/types.js
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/Dashboard/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThread/index.js
  mobile/views/DirectMessages/components/DirectMessageThreadsList.js
  mobile/views/DirectMessages/index.js
  mobile/views/Notifications/index.js
  mobile/views/Search/CommunitiesSearchView.js
  mobile/views/Search/PeopleSearchView.js
  mobile/views/Search/ThreadsSearchView.js
  mobile/views/Search/index.js
  mobile/views/Search/style.js
  mobile/views/Thread/components/Byline.js
  mobile/views/Thread/components/CommunityHeader.js
  mobile/views/Thread/index.js
  mobile/yarn.lock
  shared/graphql/queries/user/getUserThreadConnection.js
Labels: Ready for Review

#3262 Bug bash
  config-overrides.js
  hyperion/index.js
  package.json
  shared/graphql/constants.js
  src/components/threadComposer/components/composer.js
  src/helpers/analytics/raven.js
  src/views/dashboard/components/inboxThread.js
  src/views/thread/components/sidebar.js
  yarn.lock
Labels: Ready for Review

#3264 Swap in loading component for all loading ui
  mobile/components/Messages/index.js
  mobile/components/ThreadFeed/index.js
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessages/components/DirectMessageThreadsList.js
  mobile/views/Notifications/index.js
  mobile/views/Thread/index.js
  mobile/views/User/profile.js
Labels: Ready for Review

#3269 Mobile error states
  mobile/components/ErrorBoundary/index.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/NullStates/Fullscreen.js
  mobile/components/NullStates/index.js
  mobile/components/NullStates/style.js
  mobile/components/ThreadFeed/index.js
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/Dashboard/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThread/index.js
  mobile/views/DirectMessages/components/DirectMessageThreadsList.js
  mobile/views/DirectMessages/index.js
  mobile/views/Notifications/index.js
  mobile/views/Search/CommunitiesSearchView.js
  mobile/views/Search/PeopleSearchView.js
  mobile/views/Thread/index.js
  mobile/views/User/profile.js
Labels: Ready for Review

#3270 Use default tab bar styles for easier os consistency
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/TabBar/index.js
  mobile/views/User/profile.js
Labels: Ready for Review

#3271 Cleanup default search view behavior, empty states, rerendering flashes
  mobile/App.js
  mobile/components/Avatar/index.js
  mobile/components/Lists/CommunityListItem.js
  mobile/components/Lists/LoadingListItem.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/Lists/index.js
  mobile/components/NullStates/Fullscreen.js
  mobile/components/ThreadFeed/index.js
  mobile/views/Search/CommunitiesSearchView.js
  mobile/views/Search/PeopleSearchView.js
  mobile/views/Search/ThreadsSearchView.js
  mobile/views/Search/index.js
Labels: Ready for Review

#3281 2.4.6
  config-overrides.js
  hyperion/index.js
  mobile/App.js
  mobile/components/Avatar/index.js
  mobile/components/DeleteAlert/index.js
  mobile/components/ErrorBoundary/index.js
  mobile/components/Facepile/index.js
  mobile/components/InfiniteList/index.js
  mobile/components/Lists/CommunityListItem.js
  mobile/components/Lists/DirectMessageListItem/index.js
  mobile/components/Lists/ListItem.js
  mobile/components/Lists/LoadingListItem.js
  mobile/components/Lists/NotificationListItem.js
  mobile/components/Lists/ThreadListItem/PillOrMessageCount.js
  mobile/components/Lists/ThreadListItem/ThreadCommunityInfo.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/Lists/ThreadListItem/style.js
  mobile/components/Lists/UserListItem.js
  mobile/components/Lists/index.js
  mobile/components/Lists/style.js
  mobile/components/Messages/Author.js
  mobile/components/Messages/index.js
  mobile/components/NullStates/Fullscreen.js
  mobile/components/NullStates/index.js
  mobile/components/NullStates/style.js
  mobile/components/ThreadFeed/index.js
  mobile/package.json
  mobile/utils/types.js
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/Dashboard/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThread/index.js
  mobile/views/DirectMessages/components/DirectMessageThreadsList.js
  mobile/views/DirectMessages/index.js
  mobile/views/Notifications/index.js
  mobile/views/Search/CommunitiesSearchView.js
  mobile/views/Search/PeopleSearchView.js
  mobile/views/Search/ThreadsSearchView.js
  mobile/views/Search/index.js
  mobile/views/Search/style.js
  mobile/views/TabBar/index.js
  mobile/views/Thread/components/Byline.js
  mobile/views/Thread/components/CommunityHeader.js
  mobile/views/Thread/index.js
  mobile/views/User/profile.js
  mobile/yarn.lock
  package.json
  shared/graphql/constants.js
  shared/graphql/queries/channel/getChannelThreadConnection.js
  shared/graphql/queries/community/getCommunityThreadConnection.js
  shared/graphql/queries/user/getUserThreadConnection.js
  src/components/threadComposer/components/composer.js
  src/helpers/analytics/raven.js
  src/views/dashboard/components/inboxThread.js
  src/views/thread/components/sidebar.js
  yarn.lock
Labels: Ready for Review

#3285 Fix emails not sending to admins
  hermes/send-email.js
Labels: Ready for Review

#3286 Implement react-hot-loader
  config-overrides.js
  package.json
  src/index.js
  yarn.lock
Labels: Ready for Review

#3284 Unset z-index on SelectedUserPills
  src/views/directMessages/components/style.js
Labels: Ready for Review

#3287 Mobile misc cleanup
  mobile/components/Messages/index.js
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThread/index.js
  mobile/views/TabBar/BaseStack.js
  mobile/views/Thread/index.js
  mobile/views/User/index.js
  mobile/views/User/profile.js
  shared/time-formatting.js
  src/components/listItems/index.js
  src/components/messageGroup/index.js
  src/helpers/utils.js
  src/views/thread/components/threadDetail.js
  src/views/userSettings/components/recurringPaymentsList.js
Labels: Ready for Review

#3291 Make Amplitude work on mobile
  analytics/utils/transformations.js
  mobile/utils/analytics.js
  shared/clients/analytics/index.js
  shared/clients/analytics/raven.js
  shared/clients/analytics/setUser.js
  shared/clients/analytics/track.js
  shared/clients/analytics/transformations.js
  shared/clients/analytics/unsetUser.js
  shared/truthy-values.js
  src/helpers/analytics/index.js
  src/helpers/utils.js
Labels: Ready for Review, WIP: Building

#3292 Track first mobile Amplitude events
  mobile/components/Login/index.js
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/Dashboard/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessages/index.js
  mobile/views/Thread/index.js
Labels: Ready for Review

#3295 Fix admin dash
  api/models/utils.js
  chronos/models/coreMetrics.js
  chronos/models/usersSettings.js
Labels: Ready for Review

#3294 Fix some icons, new tab bar icons
  mobile/components/ChatInput/input.js
  mobile/components/Icon/glyphs.js
  mobile/views/TabBar/style.js
Labels: Ready for Review

#3283 First pass at mobile toast system
  flow-typed/npm/electron-context-menu_vx.x.x.js
  mobile/App.js
  mobile/actions/toasts.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/Toasts/Toast.js
  mobile/components/Toasts/index.js
  mobile/components/Toasts/style.js
  mobile/components/Toasts/utils.js
  mobile/reducers/index.js
  mobile/reducers/store.js
  mobile/reducers/toasts.js
  mobile/views/TabBar/index.js
Labels: Ready for Review

#3298 Fix viewing new profiles on mobile
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThread/index.js
  mobile/views/TabBar/BaseStack.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/views/Thread/index.js
  mobile/views/User/profile.js
Labels: Ready for Review

#3308 Bug basheroo
  api/models/channel.js
  api/models/search.js
  api/queries/search/searchThreads.js
  api/queries/thread/rootThread.js
  mobile/package.json
  mobile/yarn.lock
  package.json
  src/components/chatInput/index.js
  src/components/messageGroup/index.js
  src/store/index.js
  src/views/communitySettings/components/editForm.js
  src/views/dashboard/components/sidebarChannels.js
  src/views/dashboard/components/threadSearch.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/newCommunity/components/editCommunityForm/index.js
  src/views/userSettings/components/editForm.js
  yarn.lock
Labels: Ready for Review

#3315 Fixes reference to Background Jobs in Table of Contents
  README.md
Labels: Ready for Review

#3319 Clean up PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Ready for Review

#3317 Fix e2e test
  cypress/integration/thread/action_bar_spec.js
Labels: Ready for Review

#3318 Clean up signed out menu, accessible login button
  src/views/pages/components/nav.js
  src/views/pages/style.js
Labels: Ready for Review

#3320 Fix t param redirect on client
  src/index.js
Labels: Ready for Review

#3322 Remove amplitude console warns
  shared/clients/analytics/raven.js
  shared/clients/analytics/setUser.js
  shared/clients/analytics/track.js
  shared/clients/analytics/unsetUser.js
Labels: Ready for Review

#3323 2.4.9
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  api/models/channel.js
  api/models/search.js
  api/queries/search/searchThreads.js
  api/queries/thread/rootThread.js
  cypress/integration/thread/action_bar_spec.js
  mobile/package.json
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThread/index.js
  mobile/views/TabBar/BaseStack.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/views/Thread/index.js
  mobile/views/User/profile.js
  mobile/yarn.lock
  package.json
  shared/clients/analytics/raven.js
  shared/clients/analytics/setUser.js
  shared/clients/analytics/track.js
  shared/clients/analytics/unsetUser.js
  src/components/chatInput/index.js
  src/components/messageGroup/index.js
  src/index.js
  src/store/index.js
  src/views/communitySettings/components/editForm.js
  src/views/dashboard/components/sidebarChannels.js
  src/views/dashboard/components/threadSearch.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/newCommunity/components/editCommunityForm/index.js
  src/views/pages/components/nav.js
  src/views/pages/style.js
  src/views/userSettings/components/editForm.js
  yarn.lock
Labels: Ready for Review

#3314 Mobile buttons
  mobile/components/Button/index.js
  mobile/components/Button/style.js
  mobile/components/ErrorBoundary/index.js
  mobile/components/Loading/index.js
  mobile/components/Loading/style.js
  shared/graphql/queries/user/getCurrentUserEverythingFeed.js
Labels: Ready for Review, WIP: Building

#3311 Join and leave communities from mobile app
  mobile/views/Community/JoinButton.js
  mobile/views/Community/index.js
  mobile/views/Community/style.js
  shared/graphql/mutations/communityMember/addCommunityMember.js
  shared/graphql/mutations/communityMember/removeCommunityMember.js
Labels: Ready for Review

#3312 Join and leave channels on mobile
  mobile/views/Channel/JoinButton.js
  mobile/views/Channel/index.js
  mobile/views/Channel/style.js
  shared/graphql/mutations/channel/toggleChannelSubscription.js
Labels: Ready for Review

#3325 swaps tab bar icons back to stroked versions
  mobile/views/TabBar/style.js
Labels: Ready for Review

#3299 Mobile Thread Composer
  api/mutations/thread/publishThread.js
  flow-typed/npm/react-native-picker-select_vx.x.x.js
  mobile/components/Select/index.js
  mobile/components/ThreadComposer/components/LocationPicker.js
  mobile/components/ThreadComposer/components/TextInputs.js
  mobile/components/ThreadComposer/components/Wrapper.js
  mobile/components/ThreadComposer/index.js
  mobile/package.json
  mobile/views/TabBar/HomeStack.js
  mobile/views/ThreadComposerModal/index.js
  mobile/yarn.lock
  shared/graphql/mutations/thread/publishThread.js
Labels: WIP: Building

#3316 Mobile DM composer
  api/mutations/directMessageThread/createDirectMessageThread.js
  mobile/components/ChatInput/input.js
  mobile/components/ChatInput/style.js
  mobile/components/InfiniteList/index.js
  mobile/components/Lists/ListItem.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/Lists/style.js
  mobile/components/NullStates/style.js
  mobile/package.json
  mobile/views/DirectMessageComposer/SelectedUser.js
  mobile/views/DirectMessageComposer/index.js
  mobile/views/DirectMessageComposer/style.js
  mobile/views/Search/CommunitiesSearchView.js
  mobile/views/Search/PeopleSearchView.js
  mobile/views/Search/SearchBar/index.js
  mobile/views/Search/SearchBar/style.js
  mobile/views/Search/ThreadsSearchView.js
  mobile/views/Search/index.js
  mobile/views/Search/style.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/yarn.lock
  shared/graphql/mutations/directMessageThread/createDirectMessageThread.js
Labels: Ready for Review

#3329 HOTFIX Twitter Auth
  api/authentication.js
Labels: Ready for Review

#3330 Actually hotfix twitter auth
  api/authentication.js
Labels: Ready for Review

#3326 Show login screen if mobile auth token is invalid
  mobile/App.js
Labels: Ready for Review

#3301 Thread view refactor
  mobile/actions/toasts.js
  mobile/components/Anchor/index.js
  mobile/components/Button/index.js
  mobile/components/ChatInput/index.js
  mobile/components/Codeblock/index.js
  mobile/components/Codeblock/style.js
  mobile/components/IFrame/index.js
  mobile/components/Lists/CommunityListItem.js
  mobile/components/Lists/ListItem.js
  mobile/components/Lists/ListItemWithButton.js
  mobile/components/Lists/ListItemWithTitle.js
  mobile/components/Lists/ListSection/index.js
  mobile/components/Lists/ListSection/style.js
  mobile/components/Lists/ListSectionDivider/index.js
  mobile/components/Lists/ListSectionDivider/style.js
  mobile/components/Lists/NotificationListItem.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/Lists/UserListItem.js
  mobile/components/Lists/index.js
  mobile/components/Lists/style.js
  mobile/components/Loading/index.js
  mobile/components/Login/style.js
  mobile/components/Message/QuotedMessage.js
  mobile/components/Message/style.js
  mobile/components/Messages/Author.js
  mobile/components/Messages/AuthorAvatar.js
  mobile/components/Messages/AuthorName.js
  mobile/components/Messages/RoboText.js
  mobile/components/Messages/index.js
  mobile/components/Messages/style.js
  mobile/components/MutationWrapper/index.js
  mobile/components/ThreadContent/renderer.js
  mobile/components/ThreadContent/style.js
  mobile/components/ThreadFeed/index.js
  mobile/components/Toasts/Toast.js
  mobile/components/Toasts/index.js
  mobile/components/Toasts/style.js
  mobile/views/Channel/JoinButton.js
  mobile/views/Community/JoinButton.js
  mobile/views/Community/index.js
  mobile/views/TabBar/BaseStack.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/views/TabBar/headerActions/NavigateToThreadDetails.js
  mobile/views/TabBar/index.js
  mobile/views/Thread/components/ActionBar.js
  mobile/views/Thread/components/Byline.js
  mobile/views/Thread/components/CommunityHeader.js
  mobile/views/Thread/index.js
  mobile/views/Thread/style.js
  mobile/views/ThreadDetail/index.js
  mobile/views/ThreadDetail/style.js
  shared/clients/draft-js/links-decorator/index.native.js
  shared/clients/draft-js/mentions-decorator/core.js
  shared/clients/draft-js/mentions-decorator/index.native.js
  shared/clients/draft-js/message/renderer.native.js
  shared/theme/index.js
Labels: WIP: Building

#3331 Community channel detail views
  mobile/components/Lists/LoadingListItem.js
  mobile/views/ChannelDetail/index.js
  mobile/views/ChannelDetail/style.js
  mobile/views/CommunityDetail/ChannelList.js
  mobile/views/CommunityDetail/ModeratorList.js
  mobile/views/CommunityDetail/index.js
  mobile/views/CommunityDetail/style.js
  mobile/views/TabBar/BaseStack.js
  mobile/views/TabBar/headerActions/NavigateToChannelDetails.js
  mobile/views/TabBar/headerActions/NavigateToCommunityDetails.js
Labels: Ready for Review

#3350 Make mobile app build on Android
  mobile/.babelrc
Labels: Ready for Review

#3349 Add unread styling to DM list items
  mobile/components/Lists/DirectMessageListItem/index.js
  mobile/components/Lists/style.js
  mobile/views/DirectMessages/components/DirectMessageThreadsList.js
Labels: Ready for Review

#3348 Add User Details Screen
  mobile/components/Lists/CommunityListItem.js
  mobile/views/TabBar/BaseStack.js
  mobile/views/TabBar/HomeStack.js
  mobile/views/TabBar/headerActions/NavigateToUserDetails.js
  mobile/views/User/profile.js
  mobile/views/UserDetail/index.js
Labels: Ready for Review

#3327 Mobile user onboarding
  api/mutations/communityMember/addCommunityMembers.js
  api/mutations/communityMember/index.js
  api/routes/middlewares/index.js
  api/types/CommunityMember.js
  mobile/App.js
  mobile/components/Button/index.js
  mobile/components/Button/style.js
  mobile/components/Icon/glyphs.js
  mobile/components/SafeAreaView/index.js
  mobile/components/WithCurrentUser/index.js
  mobile/package.json
  mobile/views/UserOnboarding/ExploreCommunities/CommunityProfileCard/LoadingCard.js
  mobile/views/UserOnboarding/ExploreCommunities/CommunityProfileCard/index.js
  mobile/views/UserOnboarding/ExploreCommunities/CommunityProfileCard/style.js
  mobile/views/UserOnboarding/ExploreCommunities/CommunityUpsellCards.js
  mobile/views/UserOnboarding/ExploreCommunities/ExploreCommunitiesHeader/index.js
  mobile/views/UserOnboarding/ExploreCommunities/ExploreCommunitiesHeader/style.js
  mobile/views/UserOnboarding/ExploreCommunities/ExploreSearchResults.js
  mobile/views/UserOnboarding/ExploreCommunities/context.js
  mobile/views/UserOnboarding/ExploreCommunities/index.js
  mobile/views/UserOnboarding/ExploreCommunities/style.js
  mobile/views/UserOnboarding/SetUsername.js
  mobile/views/UserOnboarding/index.js
  mobile/views/UserOnboarding/style.js
  mobile/yarn.lock
  shared/analytics/event-types/userOnboarding.js
  shared/graphql/mutations/communityMember/addCommunityMembers.js
  shared/graphql/mutations/user/editUser.js
  src/views/newUserOnboarding/components/discoverCommunities/index.js
  src/views/newUserOnboarding/components/setUsername/index.js
Labels: Ready for Review, WIP: Building

#3361 Rework mobile type system
  mobile/components/Message/index.js
  mobile/components/Text/getTypeConfigFromType.js
  mobile/components/Text/getWeightFromType.js
  mobile/components/Text/index.js
  mobile/views/UserOnboarding/ExploreCommunities/CommunityProfileCard/style.js
  mobile/views/UserOnboarding/ExploreCommunities/style.js
  mobile/views/UserOnboarding/style.js
Labels: Ready for Review

#3363 Dm view behavior cleanup
  mobile/components/InfiniteList/index.js
  mobile/components/Messages/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThreadDetail/index.js
  mobile/views/DirectMessageThreadDetail/style.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/views/TabBar/HomeStack.js
  mobile/views/TabBar/headerActions/NavigateToDirectMessageThreadDetails.js
Labels: Ready for Review

#3360 Clean up splash page
  mobile/App.js
  mobile/views/Login/index.js
  mobile/views/Login/style.js
Labels: Ready for Review

#3289 Make mobile push notifications work for realz
  mobile/views/Notifications/index.js
Labels: Ready for Review

#3371 Make mobile push notifications work for real real
  api/mutations/user/index.js
  mobile/views/Notifications/index.js
Labels: Ready for Review

#3373 Pull to Refresh for DM threads lists
  mobile/views/DirectMessages/components/DirectMessageThreadsList.js
Labels: Ready for Review

#3351 Mobile app Android fixes
  mobile/App.js
  mobile/app.json
  mobile/components/Avatar/style.js
  mobile/components/ChatInput/style.js
  mobile/components/Facepile/style.js
  mobile/components/Icon/glyphs.js
  mobile/components/Icon/index.js
  mobile/components/Icon/types.js
  mobile/components/Message/Reactions.js
  mobile/components/Message/index.js
  mobile/components/Message/style.js
  mobile/components/Messages/AuthorName.js
  mobile/components/Text/index.js
  mobile/components/theme/index.js
  mobile/package.json
  mobile/views/TabBar/BaseStack.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/views/TabBar/HomeStack.js
  mobile/views/TabBar/headerActions/Close.js
  mobile/views/TabBar/headerActions/Compose.js
  mobile/views/TabBar/headerActions/Info.js
  mobile/views/TabBar/headerActions/NavigateToChannelDetails.js
  mobile/views/TabBar/headerActions/NavigateToCommunityDetails.js
  mobile/views/TabBar/headerActions/NavigateToDirectMessageThreadDetails.js
  mobile/views/TabBar/headerActions/NavigateToThreadDetails.js
  mobile/views/TabBar/headerActions/NavigateToUserDetails.js
  mobile/views/Thread/index.js
  mobile/views/UserDetail/index.js
  mobile/yarn.lock
  shared/clients/draft-js/message/renderer.native.js
  shared/graphql/constants.native.js
Labels: Ready for Review, WIP: Building

#3378 Add leniency to admins and moderators for spam/toxicity checks
  api/mutations/thread/publishThread.js
Labels: Ready for Review

#3362 Fix DM pagination
  mobile/components/InfiniteList/index.js
  mobile/components/Messages/index.js
  mobile/components/ThreadFeed/index.js
  mobile/utils/deduplicate-children.js
  mobile/views/DirectMessages/components/DirectMessageThreadsList.js
  mobile/views/Notifications/index.js
Labels: Ready for Review

#3380 Fix SSR bugs
  src/views/directMessages/components/threadsList.js
  src/views/thread/container.js
  yarn.lock
Labels: Ready for Review, WIP: Building

#3384 Fix ServiceWorker caching
  config-overrides.js
Labels: Ready for Review

#3372 Upgrade mobile to Expo SDK 28
  mobile/.expo/settings.json
  mobile/.gitignore
  mobile/app.json
  mobile/package.json
  mobile/yarn.lock
Labels: Ready for Review

#3382 Fix dashboard SSR
  shared/middlewares/thread-param.js
  src/index.js
  src/reducers/index.js
  src/store/index.js
  src/views/dashboard/components/threadFeed.js
  src/views/dashboard/index.js
Labels: Ready for Review

#3385 2.4.11
  config-overrides.js
  mobile/.expo/settings.json
  mobile/.gitignore
  mobile/app.json
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/middlewares/thread-param.js
  src/index.js
  src/reducers/index.js
  src/store/index.js
  src/views/dashboard/components/threadFeed.js
  src/views/dashboard/index.js
Labels: Ready for Review

#3386 Stop ServiceWorker from returning app shell for /auth and /api
  config-overrides.js
Labels: Ready for Review

#3388 2.4.12
  config-overrides.js
  package.json
Labels: Ready for Review

#3387 Apollo package update time
  package.json
  src/views/thread/container.js
  yarn.lock
Labels: Ready for Review

#3392 Fix broken authentication
  config-overrides.js
Labels: Ready for Review

#3379 Refactor mobile navigation stack
  api/queries/directMessageThread/index.js
  api/queries/directMessageThread/rootDirectMessageThreadByUserId.js
  api/types/DirectMessageThread.js
  mobile/App.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/Toasts/style.js
  mobile/views/DirectMessageComposer/Composer.js
  mobile/views/DirectMessageComposer/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThread/index.js
  mobile/views/TabBar/App.js
  mobile/views/TabBar/BaseStack.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/views/TabBar/HomeStack.js
  mobile/views/TabBar/Icons.js
  mobile/views/TabBar/TabBar.js
  shared/graphql/queries/directMessageThread/getDirectMessageThreadByUserId.js
Labels: Ready for Review

#3393 Fix prop type value
  mobile/views/DirectMessageComposer/Composer.js
Labels: Ready for Review

#3394 2.4.13
  api/queries/directMessageThread/index.js
  api/queries/directMessageThread/rootDirectMessageThreadByUserId.js
  api/types/DirectMessageThread.js
  config-overrides.js
  mobile/App.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/Toasts/style.js
  mobile/views/DirectMessageComposer/Composer.js
  mobile/views/DirectMessageComposer/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThread/index.js
  mobile/views/TabBar/App.js
  mobile/views/TabBar/BaseStack.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/views/TabBar/HomeStack.js
  mobile/views/TabBar/Icons.js
  mobile/views/TabBar/TabBar.js
  package.json
  shared/graphql/queries/directMessageThread/getDirectMessageThreadByUserId.js
  src/views/thread/container.js
  yarn.lock
Labels: Ready for Review

#3370 Thread reactions
  analytics/models/reaction.js
  analytics/utils/getContext.js
  analytics/utils/transformations.js
  api/loaders/index.js
  api/loaders/threadReaction.js
  api/migrations/20180621001409-thread-likes-table.js
  api/models/threadReaction.js
  api/mutations/thread/addThreadReaction.js
  api/mutations/thread/index.js
  api/mutations/thread/removeThreadReaction.js
  api/queries/thread/index.js
  api/queries/thread/reactions.js
  api/types/Notification.js
  api/types/Thread.js
  athena/index.js
  athena/queues/constants.js
  athena/queues/thread-reaction-notification.js
  athena/utils/types.js
  mercury/constants.js
  mercury/functions/processMessageCreated.js
  mercury/functions/processMessageDeleted.js
  mercury/functions/processReactionCreated.js
  mercury/functions/processReactionDeleted.js
  mercury/functions/processThreadCreated.js
  mercury/functions/processThreadDeleted.js
  mercury/functions/processThreadDeletedByModeration.js
  mercury/functions/processThreadReactionCreated.js
  mercury/functions/processThreadReactionDeleted.js
  mercury/functions/types.js
  mercury/queues/processReputationEvent.js
  shared/analytics/event-types/index.js
  shared/analytics/event-types/threadReaction.js
  shared/bull/queues.js
  shared/bull/types.js
  shared/graphql/fragments/thread/threadInfo.js
  shared/graphql/mutations/thread/addThreadReaction.js
  shared/graphql/mutations/thread/removeThreadReaction.js
  shared/types.js
  src/components/icons/index.js
  src/components/threadLikes/index.js
  src/components/threadLikes/style.js
  src/views/dashboard/components/facepile.js
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/components/threadCommunityInfo.js
  src/views/dashboard/style.js
  src/views/notifications/components/newThreadReactionNotification.js
  src/views/notifications/components/notificationDropdownList.js
  src/views/notifications/index.js
  src/views/notifications/style.js
  src/views/notifications/utils.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/threadCommunityBanner.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/container.js
  src/views/thread/style.js
  src/views/titlebar/index.js
Labels: WIP: Building

#3399 had not saved with new icon that separates private from locked status…
  src/components/icons/index.js
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/style.js
Labels: Ready for Review

#3401 Remove lastActive check
  src/views/dashboard/components/inboxThread.js
Labels: Ready for Review

#3402 2.4.14
  analytics/models/reaction.js
  analytics/utils/getContext.js
  analytics/utils/transformations.js
  api/loaders/index.js
  api/loaders/threadReaction.js
  api/migrations/20180621001409-thread-likes-table.js
  api/models/threadReaction.js
  api/mutations/thread/addThreadReaction.js
  api/mutations/thread/index.js
  api/mutations/thread/removeThreadReaction.js
  api/queries/thread/index.js
  api/queries/thread/reactions.js
  api/types/Notification.js
  api/types/Thread.js
  athena/index.js
  athena/queues/constants.js
  athena/queues/thread-reaction-notification.js
  athena/utils/types.js
  mercury/constants.js
  mercury/functions/processMessageCreated.js
  mercury/functions/processMessageDeleted.js
  mercury/functions/processReactionCreated.js
  mercury/functions/processReactionDeleted.js
  mercury/functions/processThreadCreated.js
  mercury/functions/processThreadDeleted.js
  mercury/functions/processThreadDeletedByModeration.js
  mercury/functions/processThreadReactionCreated.js
  mercury/functions/processThreadReactionDeleted.js
  mercury/functions/types.js
  mercury/queues/processReputationEvent.js
  package.json
  shared/analytics/event-types/index.js
  shared/analytics/event-types/threadReaction.js
  shared/bull/queues.js
  shared/bull/types.js
  shared/graphql/fragments/thread/threadInfo.js
  shared/graphql/mutations/thread/addThreadReaction.js
  shared/graphql/mutations/thread/removeThreadReaction.js
  shared/types.js
  src/components/icons/index.js
  src/components/threadLikes/index.js
  src/components/threadLikes/style.js
  src/views/dashboard/components/facepile.js
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/components/threadCommunityInfo.js
  src/views/dashboard/style.js
  src/views/notifications/components/newThreadReactionNotification.js
  src/views/notifications/components/notificationDropdownList.js
  src/views/notifications/index.js
  src/views/notifications/style.js
  src/views/notifications/utils.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/threadCommunityBanner.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/container.js
  src/views/thread/style.js
  src/views/titlebar/index.js
Labels: Ready for Review

#3405 Clean thread likes
  src/components/chatInput/index.js
  src/components/chatInput/input.js
  src/components/draft-js-plugins-editor/index.js
  src/components/icons/index.js
  src/components/threadLikes/index.js
  src/components/threadLikes/style.js
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/components/threadCommunityInfo.js
  src/views/dashboard/components/threadFeed.js
  src/views/dashboard/style.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/style.js
Labels: Ready for Review

#3406 2.4.15
  package.json
  src/components/chatInput/index.js
  src/components/chatInput/input.js
  src/components/draft-js-plugins-editor/index.js
  src/components/icons/index.js
  src/components/threadLikes/index.js
  src/components/threadLikes/style.js
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/components/threadCommunityInfo.js
  src/views/dashboard/components/threadFeed.js
  src/views/dashboard/style.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/style.js
Labels: Ready for Review

#3400 Dont send mentions in private communities for non members
  athena/queues/mention-notification.js
Labels: Ready for Review

#3407 Refactor and simplify thread feed cards
  cypress/integration/community/view/profile_spec.js
  src/components/avatar/style.js
  src/components/icons/index.js
  src/components/message/style.js
  src/components/profile/style.js
  src/components/threadComposer/style.js
  src/components/threadFeed/index.js
  src/components/threadLikes/index.js
  src/components/threadLikes/style.js
  src/views/channel/components/search.js
  src/views/channel/index.js
  src/views/channel/style.js
  src/views/community/components/search.js
  src/views/community/index.js
  src/views/community/style.js
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/components/inboxThread/activity.js
  src/views/dashboard/components/inboxThread/header/index.js
  src/views/dashboard/components/inboxThread/header/style.js
  src/views/dashboard/components/inboxThread/header/threadHeader.js
  src/views/dashboard/components/inboxThread/header/timestamp.js
  src/views/dashboard/components/inboxThread/header/userProfileThreadHeader.js
  src/views/dashboard/components/inboxThread/index.js
  src/views/dashboard/components/inboxThread/messageCount.js
  src/views/dashboard/components/inboxThread/style.js
  src/views/dashboard/components/threadCommunityInfo.js
  src/views/dashboard/components/threadFeed.js
  src/views/dashboard/style.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/threadCommunityBanner.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/user/components/search.js
  src/views/user/index.js
  src/views/user/style.js
Labels: Ready for Review

#3411 2.4.16
  athena/queues/mention-notification.js
  cypress/integration/community/view/profile_spec.js
  package.json
  src/components/avatar/style.js
  src/components/icons/index.js
  src/components/message/style.js
  src/components/profile/style.js
  src/components/threadComposer/style.js
  src/components/threadFeed/index.js
  src/components/threadLikes/index.js
  src/components/threadLikes/style.js
  src/views/channel/components/search.js
  src/views/channel/index.js
  src/views/channel/style.js
  src/views/community/components/search.js
  src/views/community/index.js
  src/views/community/style.js
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/components/inboxThread/activity.js
  src/views/dashboard/components/inboxThread/header/index.js
  src/views/dashboard/components/inboxThread/header/style.js
  src/views/dashboard/components/inboxThread/header/threadHeader.js
  src/views/dashboard/components/inboxThread/header/timestamp.js
  src/views/dashboard/components/inboxThread/header/userProfileThreadHeader.js
  src/views/dashboard/components/inboxThread/index.js
  src/views/dashboard/components/inboxThread/messageCount.js
  src/views/dashboard/components/inboxThread/style.js
  src/views/dashboard/components/threadCommunityInfo.js
  src/views/dashboard/components/threadFeed.js
  src/views/dashboard/style.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/threadCommunityBanner.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/user/components/search.js
  src/views/user/index.js
  src/views/user/style.js
Labels: Ready for Review

#3420 Show "Team" on badges for moderators and admins
  src/components/badges/index.js
  src/components/badges/style.js
Labels: Ready for Review

#3421 Fix icon and text alignment on thread cards
  src/views/dashboard/components/inboxThread/style.js
Labels: Ready for Review

#3395 Fix email validation email redirects for users without usernames
  api/routes/api/email.js
Labels: Ready for Review

#3396 Cache external JS files (Amplitude, GA)
  config-overrides.js
Labels: Ready for Review, WIP: Building
