Repository withspectrum/spectrum, pull requests merged in 2018-05, with the labels that each got.

#2985 Make Google Analytics GDPR compliant
  hyperion/renderer/html-template.js
  index.html
  public/index.html
  src/actions/authentication.js
  src/helpers/events.js
Labels: Ready for Review

#2984 Fix CD maybe
  .circleci/config.yml
Labels: Ready for Review, WIP: Needs Testing

#2986 Remove local Danger
  .circleci/config.yml
  dangerfile.js
  package.json
  yarn.lock
Labels: Ready for Review

#2972 GraphQL error logging improvement
  api/test/utils/__mocks__/debug.js
  api/test/utils/__snapshots__/create-graphql-error-formatter.test.js.snap
  api/test/utils/create-graphql-error-formatter.test.js
  api/utils/create-graphql-error-formatter.js
Labels: Ready for Review

#2989 [Mobile] Tab navigation styling
  mobile/views/TabBar/index.js
  mobile/views/TabBar/style.js
Labels: Ready for Review, WIP: Building

#2880 [Mobile v1] Splash page #2329
  mobile/components/Login/index.js
  mobile/components/Login/style.js
  mobile/components/theme/index.js
Labels: Ready for Review, WIP: Building

#2993 Fix CD once and for all
  .circleci/config.yml
Labels: Ready for Review, WIP: Needs Testing

#2995 Removed multiple whitespaces and changed to simular syntax for blockquotes in Markdown-Files
  admin/README.md
  docs/deployments.md
Labels: Ready for Review

#2997 Use svg icon instead of image for slack icon
  src/components/icons/index.js
  src/components/settingsViews/style.js
  src/views/communitySettings/components/slack/channelConnection.js
  src/views/communitySettings/components/slack/connectSlack.js
  src/views/communitySettings/components/slack/sendInvitations.js
Labels: Ready for Review

#2990 Filter deleted channels everywhere #2950
  api/migrations/seed/default/threads.js
  api/migrations/seed/default/usersChannels.js
  api/models/channel.js
  api/models/test/__snapshots__/channel.test.js.snap
  api/models/test/channel.test.js
  cypress/integration/channel/view/threads_spec.js
  cypress/integration/community_spec.js
  cypress/integration/inbox_spec.js
  package.json
Labels: Ready for Review

#3007 Fallback to plaintext textarea for thread publishing on Android
  api/mutations/message/addMessage.js
  api/mutations/thread/publishThread.js
  api/package.json
  api/types/Thread.js
  api/yarn.lock
  package.json
  src/components/composer/index.js
  src/components/draft-js-plugins-editor/index.js
  src/components/rich-text-editor/container.js
  src/components/threadComposer/components/composer.js
  yarn.lock
Labels: Ready for Review

#3006 Fix Android fallback input styling
  src/components/draft-js-plugins-editor/index.js
Labels: Ready for Review

#3009 fix(api/hyperion): remove unused isomorphic-fetch
  api/package.json
  api/yarn.lock
  flow-typed/npm/isomorphic-fetch_v2.x.x.js
  hyperion/index.js
  package.json
  yarn.lock
Labels: Ready for Review

#3016 Truncate long quoted replies
  src/components/message/style.js
  src/components/message/view.js
Labels: Ready for Review

#3025 Fix error formatter
  api/utils/create-graphql-error-formatter.js
Labels: Ready for Review

#3028 Fix null results from crashing user profiles
  api/queries/community/brandedLogin.js
Labels: Ready for Review

#3029 Check for existence of user in isAdmin resolver
  api/queries/meta/isAdmin.js
Labels: Ready for Review

#3003 [GDPR] Allow users to download their personal data
  api/routes/api/export-user-data.js
  api/routes/api/index.js
  src/views/userSettings/components/downloadDataForm.js
  src/views/userSettings/components/overview.js
Labels: Ready for Review

#2977 Changes to make direct messages deletable
  shared/graphql/mutations/message/deleteMessage.js
  src/components/messageGroup/index.js
Labels: Ready for Review, WIP: Building

#3030 Sanitize filenames in image uploads
  api/utils/s3.js
  package.json
  yarn.lock
Labels: Ready for Review

#3023 Dont show network status bar on marketing pages
  src/helpers/is-viewing-marketing-page.js
  src/views/navbar/index.js
  src/views/status/index.js
Labels: Ready for Review

#3037 fix(hyperion): remove unnecessary flow suppress
  hyperion/index.js
Labels: Ready for Review

#3036 refactor(flow-typed): tab to whitespace
  flow-typed/react-native.js
Labels: Ready for Review

#3035 Quote messages per-thread
  api/routes/api/graphql.js
  src/actions/message.js
  src/components/chatInput/index.js
  src/components/message/index.js
  src/components/message/view.js
  src/reducers/message.js
Labels: Ready for Review

#2905 Make mobile app run on deviceagain
  mobile/.expo/settings.json
  mobile/app.json
  mobile/components/Login/index.js
  mobile/components/ThreadContent/renderer.js
  shared/graphql/constants.js
  shared/graphql/constants.native.js
  shared/graphql/index.js
Labels: WIP: Building, WIP: Needs Testing

#3041 Fix running mobile app on device
  shared/graphql/constants.native.js
Labels: Ready for Review

#3045 Fix ServiceWorker caching issue
  hyperion/index.js
  hyperion/renderer/html-template.js
Labels: Ready for Review

#3047 Add tests for navbar links signed in and signed out
  cypress/integration/navbar_spec.js
  src/views/navbar/components/messagesTab.js
  src/views/navbar/components/notificationsTab.js
  src/views/navbar/index.js
  src/views/pages/components/nav.js
Labels: Ready for Review

#3015 Encryption decryption - first implementation
  api/migrations/20180504003702-encrypt-existing-slack-data.js
  api/models/communitySettings.js
  api/mutations/thread/publishThread.js
  api/queries/communitySlackSettings/teamName.js
  api/routes/api/slackImporter.js
  athena/models/communitySettings.js
  now.json
  package.json
  shared/encryption/index.js
  shared/test/encryption.test.js
  yarn.lock
Labels: Ready for Review

#3052 Features improvements
  src/views/pages/features/index.js
  src/views/pages/features/style.js
  src/views/pages/style.js
Labels: Ready for Review

#3054 Fix packages for prod deploy
  api/package.json
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
Labels: Ready for Review

#3055 Fix thread composer
  src/components/threadComposer/components/composer.js
Labels: Ready for Review

#3056 Fix channel slack notifications
  athena/queues/thread-notification.js
Labels: Ready for Review

#3061 Fix media messages in quote replies breaking client
  src/components/message/view.js
Labels: Ready for Review

#3062 2.2.11
  package.json
  src/components/message/view.js
Labels: Ready for Review

#3083 moves send button outside of the chatInput. fixes some overflow cases.
  src/components/chatInput/style.js
  src/components/messageGroup/style.js
  src/views/thread/style.js
Labels: Ready for Review

#3082 fixed some padding issues left over from the firefox fixes
  src/views/pages/pricing/style.js
  src/views/pages/support/index.js
  src/views/pages/view.js
Labels: Ready for Review

#3081 updates footer to be more scalable and less weird
  src/views/pages/components/footer.js
  src/views/pages/style.js
Labels: Ready for Review

#3079 fix(now.json): tab to whitespace
  now.json
Labels: Ready for Review

#3080 fix(src/views/newUserOnboarding/index) unintended untype
  src/views/newUserOnboarding/index.js
Labels: Ready for Review

#3077 fix(Routes): improve props type
  src/routes.js
Labels: Ready for Review

#3076 handles CodePen embeds better
  src/components/rich-text-editor/Embed.js
  src/helpers/regexps.js
Labels: Ready for Review

#3089 Fix analytics build
  analytics/package.json
  analytics/utils/transformations.js
  analytics/utils/truthy-values.js
  analytics/yarn.lock
  src/index.js
Labels: Ready for Review

#3090 Firefox is cool and handles padding exactly how you'd expect.
  src/views/pages/features/index.js
  src/views/pages/features/style.js
Labels: Ready for Review

#3092 Update .eslintignore
  .eslintignore
Labels: Ready for Review

#3066 Reset thread.lastActive if the last messages is deleted
  api/mutations/message/deleteMessage.js
Labels: Ready for Review

#3024 Force watercoolers to always fetch the last 50 messages
  shared/graphql/queries/thread/getThreadMessageConnection.js
  src/views/thread/container.js
Labels: Ready for Review

#3063 local storage clear on newDirectMessageThread
  src/components/chatInput/index.js
Labels: Ready for Review, WIP: Needs Testing

#3075 fix(message): always return false condition
  src/components/message/view.js
Labels: Ready for Review

#3094 Fix amplitude on frontend
  shared/analytics/event-types/index.js
  shared/analytics/event-types/page-features.js
  src/components/illustrations/index.js
  src/helpers/analytics/setUser.js
  src/helpers/analytics/track.js
  src/helpers/analytics/unsetUser.js
  src/index.js
  src/routes.js
  src/views/pages/features/index.js
Labels: WIP: Building

#3099 Buffer tracking calls until Amplitude has loaded on the web
  hyperion/renderer/html-template.js
Labels: Ready for Review

#3072 [Mobile v1] Overlay thread participant heads
  mobile/components/Avatar/index.js
  mobile/components/Avatar/style.js
  mobile/components/ThreadItem/Facepile.js
  mobile/components/ThreadItem/style.js
Labels: Ready for Review

#3112 2.2.13
  api/mutations/message/addMessage.js
  mobile/components/Avatar/index.js
  mobile/components/Avatar/style.js
  mobile/components/ThreadItem/Facepile.js
  mobile/components/ThreadItem/style.js
  package.json
Labels: Ready for Review

#3126 add cypress media to .gitignore
  .gitignore
Labels: Ready for Review

#3128 Add fallback draft state for threads without a body
  api/queries/thread/content.js
  api/queries/thread/index.js
Labels: Ready for Review

#3118 Update CSS transitions
  admin/src/components/globals/index.js
  src/components/chatInput/components/style.js
  src/components/chatInput/style.js
  src/components/gallery/style.js
  src/components/globals/index.js
  src/components/mediaInput/style.js
  src/components/newActivityIndicator/index.js
  src/components/rich-text-editor/Image.js
  src/reset.css.js
  src/views/dashboard/style.js
  src/views/newUserOnboarding/style.js
  src/views/pages/features/style.js
  src/views/pages/pricing/style.js
  src/views/pages/style.js
  src/views/search/style.js
Labels: Ready for Review

#3119 feat(mobile): done todo sentry
  mobile/App.js
Labels: Ready for Review

#3131 Error boundaries
  email-templates/privateCommunityRequestApproved.html
  package.json
  src/components/emailInvitationForm/index.js
  src/components/error/ErrorBoundary.js
  src/components/error/SettingsFallback.js
  src/components/error/index.js
  src/components/message/messageErrorFallback.js
  src/components/message/style.js
  src/components/messageGroup/index.js
  src/components/threadFeed/index.js
  src/routes.js
  src/views/channel/index.js
  src/views/channelSettings/components/overview.js
  src/views/community/index.js
  src/views/communityAnalytics/index.js
  src/views/communityBilling/index.js
  src/views/communityMembers/index.js
  src/views/communitySettings/components/overview.js
  src/views/dashboard/components/communityList.js
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/components/sidebarChannels.js
  src/views/dashboard/components/threadFeed.js
  src/views/dashboard/index.js
  src/views/directMessages/components/messages.js
  src/views/directMessages/components/threadsList.js
  src/views/directMessages/containers/existingThread.js
  src/views/explore/index.js
  src/views/explore/view.js
  src/views/notifications/components/notificationDropdownList.js
  src/views/notifications/index.js
  src/views/thread/components/messages.js
  src/views/thread/components/sidebar.js
  src/views/thread/components/threadDetail.js
  src/views/thread/container.js
  src/views/threadSlider/index.js
  src/views/user/index.js
  src/views/userSettings/components/overview.js
  yarn.lock
Labels: Ready for Review

#3135 Ensure user exists in search tracking events
  api/queries/search/searchCommunities.js
  api/queries/search/searchCommunityMembers.js
  api/queries/search/searchThreads.js
  api/queries/search/searchUsers.js
Labels: Ready for Review

#3136 2.3.1
  api/queries/search/searchCommunities.js
  api/queries/search/searchCommunityMembers.js
  api/queries/search/searchThreads.js
  api/queries/search/searchUsers.js
  package.json
Labels: Ready for Review

#3064 Update markdown implementation
  package.json
  src/components/chatInput/index.js
  yarn.lock
Labels: WIP: Building, WIP: Needs Testing

#3143 clean: api/index.js
  api/index.js
Labels: Ready for Review

#3141 fix(eslint): warning Expected '===' and instead saw '==' eqeqeq
  api/models/channel.js
Labels: Ready for Review

#3132 Mobile direct messages view
  athena/utils/push-notifications/notification-formatting.js
  mobile/components/Avatar/index.js
  mobile/components/Avatar/style.js
  mobile/components/Flex/Column.js
  mobile/components/Flex/Row.js
  mobile/components/Message/index.js
  mobile/components/Messages/index.js
  mobile/components/Text/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessageThread/index.js
  mobile/views/DirectMessageThread/style.js
  mobile/views/DirectMessages/components/DirectMessageThreadListItem.js
  mobile/views/DirectMessages/components/DirectMessageThreadsList.js
  mobile/views/DirectMessages/index.js
  mobile/views/DirectMessages/style.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/views/TabBar/index.js
  mobile/views/Thread/components/Byline.js
  package.json
  shared/clients/group-messages.js
  shared/graphql/fragments/directMessageThread/directMessageThreadInfo.js
  shared/graphql/mutations/message/sendDirectMessage.js
  shared/graphql/queries/directMessageThread/getDirectMessageThreadMessageConnection.js
  shared/time-difference.js
  src/helpers/utils.js
  src/views/communitySettings/components/slack/sendInvitations.js
  src/views/directMessages/components/messageThreadListItem.js
  src/views/notifications/utils.js
  src/views/thread/components/threadDetail.js
  yarn.lock
Labels: WIP: Building

#3088 Render mobile message replies
  flow-typed/npm/@expo/react-native-action-sheet_vx.x.x.js
  mobile/.expo/settings.json
  mobile/App.js
  mobile/components/ChatInput/index.js
  mobile/components/ChatInput/input.js
  mobile/components/ChatInput/style.js
  mobile/components/Message/QuotedMessage.js
  mobile/components/Message/index.js
  mobile/components/Message/style.js
  mobile/components/Messages/Author.js
  mobile/components/Messages/index.js
  mobile/package.json
  mobile/reducers/index.js
  mobile/views/Thread/index.js
  mobile/yarn.lock
  shared/clients/draft-js/utils/isShort.js
  shared/only-contains-emoji.js
  src/components/message/view.js
  src/helpers/utils.js
Labels: Ready for Review, WIP: Building

#3149 Update draft-js-markdown-plugin to v2.0.3
  package.json
  yarn.lock
Labels: Ready for Review

#3121 Fix E2E memory shortage on CircleCI
  .circleci/config.yml
  package.json
Labels: Ready for Review

#3151 clean(api/types/Channel.js): convert tab to whitespace
  api/types/Channel.js
Labels: Ready for Review

#3155 Fix some collapsing listitems
  mobile/components/Lists/style.js
Labels: Ready for Review

#3156 Mobile polish day
  mobile/components/Facepile/index.js
  mobile/components/Icon/glyphs.js
  mobile/components/Icon/index.js
  mobile/components/Lists/CommunityListItem.js
  mobile/components/Lists/DirectMessageListItem/index.js
  mobile/components/Lists/DirectMessageListItem/style.js
  mobile/components/Lists/ListItem.js
  mobile/components/Lists/NotificationListItem.js
  mobile/components/Lists/ThreadListItem/ThreadCommunityInfo.js
  mobile/components/Lists/ThreadListItem/index.js
  mobile/components/Lists/ThreadListItem/style.js
  mobile/components/Lists/UserListItem.js
  mobile/components/Lists/index.js
  mobile/components/Lists/style.js
  mobile/components/Loading/index.js
  mobile/components/Messages/index.js
  mobile/components/SafeAreaView/index.js
  mobile/components/SearchInput/index.js
  mobile/components/SearchInput/style.js
  mobile/components/ThreadFeed/index.js
  mobile/components/ThreadItem/index.js
  mobile/components/ThreadItem/utils.js
  mobile/components/TouchableHighlight/index.js
  mobile/components/TouchableOpacity/index.js
  mobile/components/WithCurrentUser/index.js
  mobile/package.json
  mobile/views/Channel/index.js
  mobile/views/Community/index.js
  mobile/views/Dashboard/index.js
  mobile/views/DirectMessageThread/components/DirectMessageThread.js
  mobile/views/DirectMessages/components/DirectMessageThreadsList.js
  mobile/views/DirectMessages/index.js
  mobile/views/Notifications/index.js
  mobile/views/Search/CommunitiesSearchView.js
  mobile/views/Search/PeopleSearchView.js
  mobile/views/Search/ThreadsSearchView.js
  mobile/views/Search/index.js
  mobile/views/Search/style.js
  mobile/views/TabBar/BaseStack.js
  mobile/views/TabBar/DirectMessageStack.js
  mobile/views/TabBar/HomeStack.js
  mobile/views/TabBar/NotificationsStack.js
  mobile/views/TabBar/ProfileStack.js
  mobile/views/TabBar/SearchStack.js
  mobile/views/TabBar/index.js
  mobile/views/Thread/components/Byline.js
  mobile/views/Thread/components/CommunityHeader.js
  mobile/views/Thread/index.js
  mobile/views/User/index.js
  mobile/views/User/profile.js
  mobile/yarn.lock
Labels: Ready for Review

#3157 Run all e2e tests
  cypress/integration/channel/settings/private_invite_link_spec.js
  cypress/integration/community/settings/create_spec.js
  cypress/integration/community/view/profile_spec.js
  cypress/integration/user_spec.js
Labels: Ready for Review

#3160 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Ready for Review

#3123 fix:(src,api,hyperion) Remove all unused maintenance mode code #3087
  api/schema.js
  hyperion/renderer/index.js
  src/components/emailInvitationForm/index.js
  src/components/maintenance/index.js
  src/index.js
  src/routes.js
Labels: Ready for Review

#3168 Flaky cypress test
  cypress/integration/community/view/profile_spec.js
Labels: Ready for Review

#3169 Fix flaky e2e tests
  cypress/integration/channel/settings/edit_spec.js
  cypress/integration/channel/view/membership_spec.js
  cypress/integration/community/settings/private_invite_link_spec.js
  cypress/integration/thread/action_bar_spec.js
Labels: Ready for Review

#3167 Add links decorator to mobile
  shared/clients/draft-js/links-decorator/index.native.js
  shared/clients/draft-js/message/renderer.native.js
Labels: Ready for Review

#3166 Update draft-js-markdown-plugin
  package.json
  yarn.lock
Labels: Ready for Review

#3153 updates privacy policy to specifically address GDPR issues and simpli…
  src/views/pages/privacy/index.js
Labels: Ready for Review

#3161 Mobile message reactions
  mobile/components/Message/Reactions.js
  mobile/components/Message/index.js
  mobile/components/Message/style.js
Labels: Ready for Review

#2825 Desktop app
  .circleci/config.yml
  .gitignore
  README.md
  api/models/notification.js
  athena/utils/push-notifications/index.js
  desktop/README.md
  desktop/package.json
  desktop/resources/background.tiff
  desktop/resources/icons/mac/icon.icns
  desktop/resources/icons/png/icon-512x512.png
  desktop/resources/icons/win/icon.ico
  desktop/src/autoUpdate.js
  desktop/src/config.js
  desktop/src/main.js
  desktop/src/menu.js
  desktop/src/preload.js
  desktop/src/splash.html
  desktop/yarn.lock
  package.json
  shared/notification-to-text.js
  shared/test/__snapshots__/notification-to-text.test.js.snap
  shared/test/fixtures/CHANNEL_CREATED.json
  shared/test/fixtures/COMMUNITY_INVITE.json
  shared/test/fixtures/DIRECT_MESSAGE_CREATED.json
  shared/test/fixtures/MENTION_MESSAGE.json
  shared/test/fixtures/MENTION_THREAD.json
  shared/test/fixtures/MESSAGE_CREATED.json
  shared/test/fixtures/REACTION_CREATED.json
  shared/test/fixtures/THREAD_CREATED.json
  shared/test/fixtures/USER_JOINED_COMMUNITY.json
  shared/test/notification-to-text.test.js
  src/helpers/is-desktop-app.js
  src/index.js
  src/subscribe-to-desktop-push.js
  src/views/navbar/components/messagesTab.js
  src/views/navbar/components/notificationsTab.js
  yarn.lock
Labels: Ready for Review, WIP: Building, WIP: Needs Testing

#3170 Eslint cleanup
  src/components/message/view.js
  src/views/pages/privacy/index.js
Labels: Ready for Review

#3175 Attribute desktop analytics to desktop client
  src/helpers/analytics/track.js
Labels: Ready for Review

#3188 Bug bash day
  api/mutations/community/updateAdministratorEmail.js
  api/mutations/message/addMessage.js
  athena/queues/private-channel-request-approved.js
  athena/queues/private-channel-request-sent.js
  athena/queues/private-community-request-approved.js
  athena/queues/private-community-request-sent.js
  athena/queues/send-slack-invitations.js
  hermes/send-email.js
  hyperion/renderer/html-template.js
  src/components/chatInput/components/mediaUploader.js
  src/components/composer/index.js
  src/components/threadComposer/components/composer.js
  src/views/community/components/channelList.js
  src/views/explore/components/search.js
  src/views/newUserOnboarding/components/communitySearch/index.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#3200 Hide web push prompt while in desktop app
  src/views/notifications/index.js
  src/views/userSettings/components/overview.js
Labels: Ready for Review

#3199 Continuous deployment for desktop app
  .circleci/config.yml
  desktop/README.md
  desktop/package.json
  desktop/resources/release-notes.md
  desktop/yarn.lock
  package.json
Labels: Ready for Review

#3192 Desktop polish
  desktop/src/config.js
  desktop/src/main.js
  desktop/src/menu.js
  desktop/src/splash.html
  src/components/menu/style.js
  src/views/dashboard/style.js
  src/views/navbar/components/messagesTab.js
  src/views/navbar/components/notificationsTab.js
  src/views/navbar/index.js
  src/views/navbar/style.js
  src/views/titlebar/style.js
Labels: Ready for Review

#3202 2.4.2
  .circleci/config.yml
  api/mutations/community/updateAdministratorEmail.js
  api/mutations/message/addMessage.js
  athena/queues/private-channel-request-approved.js
  athena/queues/private-channel-request-sent.js
  athena/queues/private-community-request-approved.js
  athena/queues/private-community-request-sent.js
  athena/queues/send-slack-invitations.js
  config-overrides.js
  desktop/README.md
  desktop/package.json
  desktop/resources/release-notes.md
  desktop/src/config.js
  desktop/src/main.js
  desktop/src/menu.js
  desktop/src/splash.html
  desktop/yarn.lock
  hermes/send-email.js
  hyperion/index.js
  hyperion/renderer/html-template.js
  package.json
  src/components/chatInput/components/mediaUploader.js
  src/components/composer/index.js
  src/components/menu/style.js
  src/components/threadComposer/components/composer.js
  src/views/community/components/channelList.js
  src/views/dashboard/style.js
  src/views/explore/components/search.js
  src/views/navbar/components/messagesTab.js
  src/views/navbar/components/notificationsTab.js
  src/views/navbar/index.js
  src/views/navbar/style.js
  src/views/newUserOnboarding/components/communitySearch/index.js
  src/views/notifications/index.js
  src/views/thread/components/threadDetail.js
  src/views/titlebar/style.js
  src/views/userSettings/components/overview.js
  yarn.lock
Labels: Ready for Review

#3205 Fix 2.4.2
  desktop/package.json
  hermes/package.json
  hermes/yarn.lock
  yarn.lock
Labels: Ready for Review

#3206 Fix prod 2.4.2
  desktop/package.json
  hermes/package.json
  hermes/yarn.lock
  yarn.lock
Labels: Ready for Review

#3117 fix upload images tooltip hover state
  src/views/thread/style.js
Labels: Ready for Review

#3219 Refactoring
  src/views/community/index.js
  src/views/dashboard/index.js
  src/views/pages/terms/index.js
Labels: Ready for Review

#3027 Dont show deleted threads in notifications dropdown
  src/components/profile/thread.js
  src/views/notifications/components/newThreadNotification.js
Labels: Ready for Review

#3226 Fix focussing body when pressing enter in title in composer
  src/components/rich-text-editor/container.js
Labels: Ready for Review

#3069 Add hover profile to mentions
  shared/clients/draft-js/mentions-decorator/core.js
  src/components/avatar/hoverProfile.js
  src/components/rich-text-editor/style.js
  src/views/thread/components/sidebar.js
Labels: Ready for Review, WIP: Building

#3039 Update banning-users.md to include mutations to disable feature flags…
  docs/operations/banning-users.md
Labels: Ready for Review

#3222 Fix desktop auto updating maybe
  desktop/package.json
  desktop/src/autoUpdate.js
  desktop/src/main.js
  desktop/src/menu.js
  desktop/yarn.lock
Labels: Ready for Review

#3220 Add desktop deployment docs
  desktop/deployment.md
Labels: Ready for Review

#3221 Run desktop CD from the alpha branch
  .circleci/config.yml
Labels: Ready for Review

#3227 Don't server-side render for desktop app
  config-overrides.js
  hyperion/index.js
Labels: Ready for Review

#3223 Persist desktop app window state on reopen
  desktop/package.json
  desktop/src/config.js
  desktop/src/main.js
  desktop/yarn.lock
Labels: Ready for Review

#3198 Show login as first view on desktop startup
  .github/PULL_REQUEST_TEMPLATE.md
  desktop/src/config.js
  src/routes.js
Labels: Ready for Review

#3232 Bump desktop version
  desktop/package.json
Labels: Ready for Review

#3233 2.4.3
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  config-overrides.js
  desktop/deployment.md
  desktop/package.json
  desktop/src/autoUpdate.js
  desktop/src/config.js
  desktop/src/main.js
  desktop/src/menu.js
  desktop/yarn.lock
  docs/operations/banning-users.md
  hyperion/index.js
  package.json
  shared/clients/draft-js/mentions-decorator/core.js
  src/components/avatar/hoverProfile.js
  src/components/profile/thread.js
  src/components/rich-text-editor/container.js
  src/components/rich-text-editor/style.js
  src/routes.js
  src/views/community/index.js
  src/views/dashboard/index.js
  src/views/notifications/components/newThreadNotification.js
  src/views/pages/terms/index.js
  src/views/thread/components/sidebar.js
  src/views/thread/style.js
Labels: Ready for Review

#3026 Scroll to bottom of messages if user has seen thread before
  src/views/communityMembers/index.js
  src/views/notifications/components/notificationDropdownList.js
  src/views/thread/components/messages.js
  src/views/thread/container.js
Labels: Ready for Review
