Repository withspectrum/spectrum, pull requests merged in 2018-04, with the labels that each got.

#2623 Add license
  LICENSE
  README.md
Labels: TBD: Needs Discussion

#2688 [A11Y] - Add empty alt attribute to homepage images
  src/components/illustrations/index.js
  src/views/pages/components/logos.js
  src/views/pages/view.js
  yarn.lock
Labels: WIP: Ready for Review

#2687 Hotfix message subscriptions
  api/subscriptions/message.js
Labels: WIP: Ready for Review

#2701 Rename docs/graphql -> docs/api
  README.md
  docs/backend/api/README.md
  docs/backend/api/fragments.md
  docs/backend/api/pagination.md
  docs/backend/api/testing.md
  docs/backend/api/tips-and-tricks.md
Labels: WIP: Ready for Review

#2703 Fix a stripe error that crashes frontend while doing local dev
  shared/stripe/utils.js
Labels: WIP: Ready for Review

#2712 Cache all public files
  config-overrides.js
Labels: WIP: Ready for Review

#2710 Move all athena queues to shared/queues
  athena/queues/constants.js
  athena/queues/create-thread-notification-email.js
  athena/queues/direct-message-notification.js
  athena/queues/mention-notification.js
  athena/queues/moderationEvents/message.js
  athena/queues/moderationEvents/thread.js
  athena/queues/new-message-in-thread/buffer-email.js
  athena/queues/new-message-in-thread/index.js
  athena/queues/private-channel-request-approved.js
  athena/queues/private-channel-request-sent.js
  athena/queues/thread-notification.js
  athena/utils/addQueue.js
  hermes/queues/send-mention-message-email.js
  hermes/queues/send-mention-thread-email.js
  hermes/queues/send-new-direct-message-email.js
  hermes/queues/send-new-message-email.js
  hermes/queues/send-private-channel-request-approved-email.js
  hermes/queues/send-private-channel-request-sent-email.js
  shared/bull/queues.js
  shared/bull/types.js
  shared/types.js
Labels: WIP: Ready for Review

#2699 #2645: Only update the threadLastSeen if its later than the current one
  athena/queues/track-user-thread-last-seen.js
  shared/types.js
Labels: WIP: Ready for Review

#2717 [A11Y] - Add empty alt to Avatar component
  mercury/yarn.lock
  mobile/yarn.lock
  src/components/avatar/image.js
  vulcan/yarn.lock
  yarn.lock
Labels: WIP: Ready for Review

#2715 Add development tokens for stripe
  now-secrets.example.json
  now.json
  shared/stripe/index.js
  src/api/constants.js
Labels: WIP: Ready for Review

#2730 Fix typo in Mercury documentation
  docs/workers/mercury/intro.md
Labels: WIP: Ready for Review

#2718 Fix thread badge treatment
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/style.js
Labels: WIP: Ready for Review

#2719 Adds channel pill to thread view sidebar component
  src/views/thread/components/sidebar.js
  src/views/thread/style.js
Labels: WIP: Ready for Review

#2722 Add timeout to prevent disconnected status bar flashing
  src/views/status/index.js
Labels: WIP: Ready for Review

#2727 Ensure that localStorage is in scope anywhere we get or set an item
  src/components/chatInput/index.js
  src/components/composer/index.js
  src/components/threadComposer/components/composer.js
  src/helpers/localStorage.js
Labels: WIP: Ready for Review

#2729 Remove fetch policy from slack import mutation
  athena/index.js
  athena/queues/constants.js
  shared/bull/queues.js
  shared/graphql/mutations/slackImport/sendSlackInvitations.js
Labels: WIP: Ready for Review

#2737 [A11Y] - Introduce VisuallyHidden component
  src/components/visuallyHidden/index.js
  yarn.lock
Labels: WIP: Ready for Review

#2720 Fix community image order
  shared/graphql/fragments/user/userCommunityConnection.js
  src/views/dashboard/components/communityList.js
Labels: WIP: Ready for Review

#2739 Add flow type to new visually hidden component
  src/components/visuallyHidden/index.js
Labels: WIP: Ready for Review

#2721 Fix channel rep count
  src/components/granularUserProfile/style.js
  src/components/settingsViews/style.js
  src/views/channel/components/memberGrid.js
  src/views/channel/style.js
  src/views/channelSettings/components/blockedUsers.js
  src/views/channelSettings/components/channelMembers.js
  src/views/channelSettings/components/overview.js
  src/views/channelSettings/components/pendingUsers.js
  src/views/channelSettings/index.js
  src/views/channelSettings/style.js
  src/views/community/components/moderatorList.js
Labels: WIP: Ready for Review

#2713 Rework athena buffering
  athena/queues/new-message-in-thread/buffer-email.js
  athena/queues/new-message-in-thread/format-data.js
  athena/queues/new-message-in-thread/index.js
  shared/bull/queues.js
  shared/bull/types.js
Labels: WIP: Ready for Review

#2736 Activate last thread after closing new thread composer
  src/components/composer/index.js
Labels: WIP: Ready for Review

#2746 Fix plural '1 new messages'
  hermes/queues/send-new-message-email.js
Labels: WIP: Ready for Review

#2724 Catch more worker errors
  athena/queues/channel-notification.js
  athena/queues/community-invite.js
  athena/queues/community-invoice-paid.js
  athena/queues/community-notification.js
  athena/queues/mention-notification.js
  athena/queues/pro-invoice-paid.js
  athena/queues/reaction-notification.js
  athena/queues/send-push-notifications.js
  athena/queues/slack-import.js
  athena/queues/track-user-thread-last-seen.js
  chronos/queues/coreMetrics/activeCommunityAdminReport.js
  chronos/queues/coreMetrics/index.js
  chronos/queues/digests/index.js
  chronos/queues/digests/processDigestEmail.js
  hermes/queues/send-admin-active-community-report-email.js
  hermes/queues/send-admin-community-created-email.js
  hermes/queues/send-admin-slack-import-email.js
  hermes/queues/send-admin-toxic-content-email.js
  hermes/queues/send-administrator-email-validation-email.js
  hermes/queues/send-community-card-expiring-warning-email.js
  hermes/queues/send-community-invite-email.js
  hermes/queues/send-community-invoice-receipt-email.js
  hermes/queues/send-community-payment-failed-email.js
  hermes/queues/send-community-payment-succeeded-email.js
  hermes/queues/send-digest-email.js
  hermes/queues/send-email-validation-email.js
  hermes/queues/send-mention-message-email.js
  hermes/queues/send-new-community-welcome-email.js
  hermes/queues/send-new-direct-message-email.js
  hermes/queues/send-new-message-email.js
  hermes/queues/send-new-thread-email.js
  hermes/queues/send-private-channel-request-approved-email.js
  hermes/queues/send-private-channel-request-sent-email.js
  hermes/queues/send-pro-invoice-receipt-email.js
  hermes/queues/send-user-welcome-email.js
  mercury/queues/processReputationEvent.js
  pluto/queues/processAdministratorEmailChanged.js
  pluto/queues/processAnalyticsAdded.js
  pluto/queues/processAnalyticsRemoved.js
  pluto/queues/processCardExpiringWarning.js
  pluto/queues/processCommunityCreated.js
  pluto/queues/processCommunityDeleted.js
  pluto/queues/processCommunityEdited.js
  pluto/queues/processModeratorAdded.js
  pluto/queues/processModeratorRemoved.js
  pluto/queues/processOssStatusActivated.js
  pluto/queues/processOssStatusDisabled.js
  pluto/queues/processOssStatusEnabled.js
  pluto/queues/processPaymentFailed.js
  pluto/queues/processPaymentSucceeded.js
  pluto/queues/processPrioritySupportAdded.js
  pluto/queues/processPrioritySupportRemoved.js
  pluto/queues/processPrivateChannelAdded.js
  pluto/queues/processPrivateChannelRemoved.js
  pluto/queues/removeAllPaidFeatures.js
Labels: WIP: Ready for Review

#2740 Remove unsed puppeteer dep
  package.json
  yarn.lock
Labels: WIP: Ready for Review

#2738 Dont fetch deleted messages when loading image gallery
  api/models/message.js
Labels: WIP: Ready for Review

#2728 Fix invalid token response when using accessToken authentication
  api/routes/auth/create-signin-routes.js
Labels: WIP: Ready for Review

#2751 Add platform check for dependency install script
  shared/install-dependencies.js
Labels: WIP: Ready for Review

#2756 Fix author avatar on watercoolers
  src/views/dashboard/components/inboxThread.js
Labels: WIP: Ready for Review

#2731 Close toolbar on image add or editor focus
  src/components/draftjs-editor/index.js
Labels: WIP: Ready for Review

#2764 Also delete profile photos
  docs/operations/deleting-users.md
Labels: WIP: Ready for Review

#2757 Dont cache image assets in serviceworker
  config-overrides.js
  public/_redirects
Labels: WIP: Ready for Review

#2772 2.2.5
  config-overrides.js
  package.json
  public/_redirects
Labels: WIP: Ready for Review

#2784 Display sign in buttons in a grid
  src/components/loginButtonSet/style.js
Labels: WIP: Ready for Review

#2765 🎨 Truncate link attachments in thread inbox component
  src/views/dashboard/components/inboxThread.js
  src/views/dashboard/style.js
Labels: WIP: Ready for Review

#2762 Problem cloning using ssh so add http link
  README.md
Labels: WIP: Ready for Review

#2786 Possibly fix broken chat input layout
  src/views/thread/index.js
Labels: WIP: Ready for Review

#2787 Fix broken links in docs ToC
  docs/readme.md
Labels: WIP: Ready for Review

#2791 fix: Improved "on hover" user cards positioning
  .flowconfig
  .gitignore
  package.json
  src/components/avatar/hoverProfile.js
  src/components/avatar/image.js
  src/components/avatar/index.js
  src/components/avatar/style.js
  yarn.lock
Labels: WIP: Ready for Review

#2774 First implementation of platform level blocking
  api/queries/user/rootCurrentUser.js
  api/routes/api/graphql.js
  docs/operations/banning-users.md
  docs/operations/deleting-users.md
  docs/operations/importing-rethinkdb-backups.md
  docs/operations/intro.md
  pluto/changefeeds/privateChannel.js
  shared/changefeed-utils/index.js
  vulcan/index.js
  vulcan/models/user.js
Labels: WIP: Ready for Review

#2788 Add toobusy handling to worker servers
  shared/bull/create-worker.js
  shared/middlewares/toobusy.js
Labels: WIP: Building

#2758 Stop thread spam
  api/models/thread.js
  api/mutations/thread/publishThread.js
  api/package.json
  api/yarn.lock
  athena/queues/moderationEvents/perspective.js
  athena/queues/moderationEvents/spectrum.js
  email-templates/adminUserSpammingThreadsNotification.html
  flow-typed/npm/string-similarity_vx.x.x.js
  hermes/index.js
  hermes/queues/constants.js
  hermes/queues/send-admin-user-spamming-threads-notification-email.js
  package.json
  shared/bull/queues.js
  shared/bull/types.js
  shared/types.js
  yarn.lock
Labels: Ready for Review

#2778 Paste image from clipboard into chat input
  src/components/chatInput/components/mediaUploader.js
  src/components/chatInput/index.js
  src/components/chatInput/input.js
  src/components/chatInput/style.js
Labels: Ready for Review, WIP: Needs Testing

#2797 Fix opacity on media preview
  src/components/chatInput/style.js
Labels: WIP: Ready for Review

#2799 Fix messages tab
  shared/graphql/queries/directMessageThread/getDirectMessageThreadMessageConnection.js
Labels: WIP: Ready for Review

#2798 Fix thread view auth links
  src/views/thread/components/sidebar.js
Labels: WIP: Ready for Review

#2709 Restrict deployments to SFO
  now.json
Labels: WIP: Needs Testing

#2809 Fix mobile cold start
  mobile/views/Notifications/index.js
Labels: Ready for Review

#2811 Swap spectrum secrets
  athena/queues/moderationEvents/message.js
  athena/queues/moderationEvents/perspective.js
  athena/queues/moderationEvents/spectrum.js
  athena/queues/moderationEvents/thread.js
  now.json
Labels: Ready for Review

#2812 Swap spectrum api keys in alpha to keep in sync with prod hotfix
  athena/queues/moderationEvents/message.js
  athena/queues/moderationEvents/perspective.js
  athena/queues/moderationEvents/spectrum.js
  athena/queues/moderationEvents/thread.js
  now.json
Labels: Ready for Review

#2808 Fix "Blob undefined"
  src/components/chatInput/components/mediaUploader.js
  src/components/chatInput/index.js
Labels: Ready for Review

#2752 Improve NavBar’s a11y
  src/components/link/index.js
  src/components/link/props.js
  src/components/menu/index.js
  src/components/menu/style.js
  src/routes.js
  src/views/dashboard/index.js
  src/views/directMessages/style.js
  src/views/navbar/components/messagesTab.js
  src/views/navbar/components/notificationsTab.js
  src/views/navbar/index.js
  src/views/navbar/style.js
  src/views/notifications/index.js
  src/views/thread/index.js
  src/views/thread/style.js
Labels: WIP: Needs Testing

#2674 Fix e2e tests
  .circleci/config.yml
  api/models/db.js
  api/queries/channel/rootChannel.js
  api/queries/community/hasChargeableSource.js
  api/routes/api/graphql.js
  cypress.json
  cypress/integration/channel/settings/create_spec.js
  cypress/integration/channel/settings/delete_spec.js
  cypress/integration/channel/settings/edit_spec.js
  cypress/integration/channel/settings/private_invite_link_spec.js
  cypress/integration/channel/view/composer_spec.js
  cypress/integration/channel/view/members_spec.js
  cypress/integration/channel/view/membership_spec.js
  cypress/integration/channel/view/notifications_spec.js
  cypress/integration/channel/view/profile_spec.js
  cypress/integration/channel/view/search_spec.js
  cypress/integration/channel/view/threads_spec.js
  cypress/integration/community_settings_billing_spec.js
  cypress/integration/home_spec.js
  cypress/integration/inbox_spec.js
  cypress/integration/pricing_spec.js
  cypress/integration/privacy_page_spec.js
  cypress/integration/terms_page_spec.js
  cypress/integration/thread/action_bar_spec.js
  cypress/integration/thread/chat_input_spec.js
  cypress/integration/thread/create_spec.js
  cypress/integration/thread/view_spec.js
  cypress/integration/user_spec.js
  cypress/support/index.js
  package.json
  shared/graphql/fragments/channel/channelMemberConnection.js
  shared/graphql/queries/channel/getChannelBlockedUsers.js
  shared/graphql/queries/channel/getChannelMemberConnection.js
  shared/middlewares/toobusy.js
  shared/testing/setup.js
  shared/testing/teardown.js
  src/views/channel/components/memberGrid.js
  src/views/channelSettings/components/blockedUsers.js
  src/views/channelSettings/components/channelMembers.js
  src/views/channelSettings/components/pendingUsers.js
  src/views/newUserOnboarding/components/discoverCommunities/index.js
  yarn.lock
Labels: WIP: Building

#2801 Swap out sentry dsn to secret ones
  now.json
  shared/raven/index.js
  src/helpers/events.js
Labels: Ready for Review

#2816 Sort and preserve order of participant heads
  src/views/dashboard/components/facepile.js
Labels: Ready for Review

#2783 Better validation for username and logic behind the calls to API in SetUsername component
  src/components/editForm/user.js
  src/components/usernameSearch/index.js
  src/components/usernameSearch/style.js
  src/views/newUserOnboarding/components/setUsername/index.js
  src/views/newUserOnboarding/components/setUsername/style.js
Labels: Ready for Review

#2807 Update blacklist with routes currently in use
  shared/slug-blacklists.js
Labels: Ready for Review

#2823 Fix token-based auth for mobile apps
  api/routes/auth/create-signin-routes.js
  mobile/components/ThreadFeed/index.js
Labels: Ready for Review

#2824 Implement close modal handler for create/restore channel modals
  src/components/modals/CreateChannelModal/index.js
  src/components/modals/RestoreChannelModal/index.js
Labels: Ready for Review

#2826 Update draft-js-markdown-plugin
  package.json
  yarn.lock
Labels: Ready for Review

#2818 Fixes all the <main> changes by replacing the wrappers with <main> vs adding an extra element
  src/components/gallery/index.js
  src/components/menu/index.js
  src/components/menu/style.js
  src/components/modals/modalRoot.js
  src/components/settingsViews/style.js
  src/routes.js
  src/views/channel/index.js
  src/views/channel/style.js
  src/views/channelSettings/index.js
  src/views/community/index.js
  src/views/community/style.js
  src/views/communitySettings/index.js
  src/views/dashboard/index.js
  src/views/dashboard/style.js
  src/views/directMessages/style.js
  src/views/explore/index.js
  src/views/explore/style.js
  src/views/notifications/index.js
  src/views/pages/index.js
  src/views/pages/style.js
  src/views/thread/index.js
  src/views/thread/style.js
  src/views/user/index.js
  src/views/user/style.js
Labels: WIP: Needs Testing

#2781 adds membership lists to the left profile column on mid-size displays
  src/components/granularUserProfile/index.js
  src/components/granularUserProfile/style.js
  src/components/toggleCommunityMembership/index.js
  src/views/channel/components/memberGrid.js
  src/views/channel/style.js
  src/views/channelSettings/components/blockedUsers.js
  src/views/channelSettings/components/pendingUsers.js
  src/views/community/components/memberGrid.js
  src/views/community/components/moderatorList.js
  src/views/community/index.js
  src/views/community/style.js
  src/views/user/index.js
  src/views/user/style.js
Labels: WIP: Building

#2836 Work around DraftJS on Android in the chat input
  api/mutations/message/addMessage.js
  package.json
  shared/clients/draft-js/message/renderer.web.js
  shared/clients/draft-js/message/test/__snapshots__/renderer.test.js.snap
  shared/clients/draft-js/message/test/renderer.test.js
  shared/draft-utils.js
  src/components/chatInput/index.js
  src/components/chatInput/input.js
  src/components/chatInput/style.js
  src/components/message/view.js
  yarn.lock
Labels: Ready for Review

#2840 Clean up pending and blocked users styling and layout
  src/components/settingsViews/style.js
  src/views/channelSettings/components/blockedUsers.js
  src/views/channelSettings/components/editDropdown.js
  src/views/channelSettings/components/pendingUsers.js
Labels: Ready for Review

#2845 Fix the deprecation warning of Draft.js
  src/components/draftjs-editor/Embed.js
Labels: Ready for Review

#2849 Fix local mobile singin
  api/utils/is-spectrum-url.js
  now-secrets.example.json
Labels: Ready for Review

#2855 Add styling for code blocks
  src/components/chatInput/style.js
  src/components/message/style.js
Labels: Ready for Review

#2848 Add pointer when hovering over message images
  src/components/message/style.js
Labels: Ready for Review

#2856 Fixes login modal grid on desktop
  src/components/modals/ChatInputLoginModal/index.js
Labels: Ready for Review

#2857 remove linter warnings
  src/components/chatInput/index.js
  src/components/chatInput/input.js
  src/components/chatInput/style.js
  src/components/message/view.js
Labels: Ready for Review

#2833 Smarter lowercase checks and storage for users, communities, and channels
  api/migrations/20180411183454-lowercase-all-the-slugs.js
  api/models/user.js
  api/types/Channel.js
  api/types/Community.js
  api/types/User.js
  api/types/custom-scalars/LowercaseString.js
  api/types/general.js
  api/types/scalars.js
  shared/graphql/mutations/user/updateUserEmail.js
  shared/graphql/queries/channel/getChannel.js
  shared/graphql/queries/community/getCommunities.js
  shared/graphql/queries/community/getCommunity.js
  shared/graphql/queries/community/getCommunitySettings.js
  shared/graphql/queries/user/getUser.js
  shared/graphql/schema.json
Labels: Ready for Review

#2860 Fix broken deployment link
  README.md
Labels: Ready for Review

#2868 Create android-friendly wrapper around draft-js-plugins-editor
  shared/clients/draft-js/mentions-decorator/index.web.js
  src/components/chatInput/input.js
  src/components/chatInput/style.js
  src/components/composer/index.js
  src/components/draft-js-plugins-editor/index.js
  src/components/rich-text-editor/Embed.js
  src/components/rich-text-editor/Image.js
  src/components/rich-text-editor/index.js
  src/components/rich-text-editor/prism-theme.css
  src/components/rich-text-editor/style.js
  src/components/rich-text-editor/toolbar.js
  src/components/threadComposer/components/composer.js
  src/reset.css.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#2866 Maybe fix DM badge not showing up
  src/views/navbar/index.js
Labels: Ready for Review

#2865 Cache homescreen icons from the ServiceWorker
  config-overrides.js
Labels: Ready for Review

#2847 Delete users
  api/migrations/seed/default/index.js
  api/migrations/seed/default/usersSettings.js
  api/models/user.js
  api/models/usersChannels.js
  api/models/usersCommunities.js
  api/models/usersThreads.js
  api/mutations/recurringPayment/upgradeToPro.js
  api/mutations/recurringPayment/utils.js
  api/mutations/user/deleteCurrentUser.js
  api/mutations/user/index.js
  api/types/User.js
  cypress/integration/faq_page_spec.js
  cypress/integration/user/delete_user_spec.js
  docs/operations/deleting-users.md
  shared/graphql/mutations/user/deleteCurrentUser.js
  src/components/editForm/index.js
  src/components/settingsViews/header.js
  src/routes.js
  src/views/navbar/index.js
  src/views/pages/faq/index.js
  src/views/pages/faq/style.js
  src/views/pages/index.js
  src/views/user/index.js
  src/views/userSettings/components/deleteAccountForm.js
  src/views/userSettings/components/editForm.js
  src/views/userSettings/components/emailSettings.js
  src/views/userSettings/components/invoices.js
  src/views/userSettings/components/notificationSettings.js
  src/views/userSettings/components/overview.js
  src/views/userSettings/components/recurringPaymentsList.js
  src/views/userSettings/index.js
  src/views/userSettings/style.js
Labels: Ready for Review

#2863 Update draft-js-markdown-plugin
  package.json
  src/components/chatInput/input.js
  src/components/rich-text-editor/LanguageSelect.js
  src/components/rich-text-editor/index.js
  src/reset.css.js
  yarn.lock
Labels: Ready for Review

#2875 Disabeling CI Danger run for forks
  .circleci/config.yml
Labels: Ready for Review

#2879 Update README.md
  README.md
Labels: Ready for Review

#2876 Fix fallback Android input in DMs
  src/components/chatInput/index.js
Labels: Ready for Review

#2870 shows a cheat sheet of supported markdown features
  cypress/integration/thread/chat_input_spec.js
  src/components/chatInput/index.js
  src/components/chatInput/style.js
  src/components/message/style.js
Labels: Ready for Review

#2871 Request screenshots in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Ready for Review

#2891 returns the gradients to the text bubbles
  src/components/message/style.js
Labels: Ready for Review

#2888 Fix packages for deploying workers
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  mercury/package.json
  mercury/yarn.lock
  pluto/package.json
  pluto/yarn.lock
  vulcan/package.json
  vulcan/yarn.lock
Labels: Ready for Review

#2889 Add pluto as deploy option in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Ready for Review

#2881 Fixing tests
  .circleci/config.yml
  shared/stripe/index.js
  src/views/communitySettings/components/channelList.js
Labels: WIP: Building

#2869 [Mobile v1] Thread Card improvements & styling
  mobile/components/Avatar/image.js
  mobile/components/Avatar/img/default_avatar.svg
  mobile/components/Avatar/img/default_community.svg
  mobile/components/Avatar/index.js
  mobile/components/Avatar/style.js
  mobile/components/Avatar/utils.js
  mobile/components/ThreadFeed/index.js
  mobile/components/ThreadFeed/style.js
  mobile/components/ThreadItem/Facepile.js
  mobile/components/ThreadItem/index.js
  mobile/components/ThreadItem/style.js
  mobile/views/Splash/index.js
  mobile/views/Splash/style.js
Labels: WIP: Building

#2902 Use the users username for the `return to profile` link
  src/views/userSettings/index.js
Labels: Ready for Review

#2899 Update banning users docs
  docs/operations/banning-users.md
Labels: Ready for Review

#2903 Add configs to cypress and circleci
  .circleci/config.yml
  cypress.json
Labels: Ready for Review

#2481 Make it possible for admin to import from shared/
  admin/package.json
Labels: WIP: Needs Testing

#2915 Temporarily disable delete user integration test
  .circleci/config.yml
  cypress/integration/user/delete_user_spec.js
Labels: Ready for Review

#2911 fix focus of the chatinput after a user composes a new DM #2493
  src/views/directMessages/containers/existingThread.js
Labels: Ready for Review

#2890 Pagination on tall screens
  src/components/chatInput/index.js
  src/components/chatInput/input.js
  src/components/infiniteScroll/index.js
  src/components/infiniteScroll/tallViewports.js
  src/components/threadFeed/index.js
  src/components/toggleCommunityMembership/index.js
  src/views/community/components/memberGrid.js
  src/views/community/style.js
  src/views/dashboard/components/threadFeed.js
  src/views/directMessages/components/threadsList.js
  src/views/directMessages/index.js
  src/views/notifications/index.js
  src/views/thread/components/messages.js
Labels: WIP: Needs Testing

#2916 fix(src/components/loading/style): align indent
  src/components/loading/style.js
Labels: Ready for Review

#2909 Security middleware implementation
  api/index.js
  api/package.json
  api/yarn.lock
  hyperion/index.js
  package.json
  shared/middlewares/security.js
  yarn.lock
Labels: Ready for Review

#2926 fix(src/views/login/style.js): css syntax error. add expected colon
  src/views/login/style.js
Labels: Ready for Review

#2930 Fix Cypress for forks
  .circleci/config.yml
Labels: Ready for Review

#2919 Show photo size error on image added and neater error positioning
  src/components/chatInput/index.js
  src/components/chatInput/style.js
Labels: Ready for Review

#2931 Maybe fix user thread last seen tracking
  athena/queues/track-user-thread-last-seen.js
Labels: Ready for Review

#2922 Fix infinite loop in rich text editor
  src/components/rich-text-editor/toolbar.js
Labels: Ready for Review

#2932 Private channel mod fixes
  api/mutations/channel/disableChannelTokenJoin.js
  api/mutations/channel/enableChannelTokenJoin.js
  api/mutations/channel/resetChannelJoinToken.js
  api/mutations/channel/togglePendingUser.js
  api/mutations/channel/unblockUser.js
  api/mutations/community/disableBrandedLogin.js
  api/mutations/community/enableBrandedLogin.js
  api/mutations/community/saveBrandedLoginSettings.js
  api/queries/community/billingSettings.js
  api/queries/community/hasChargeableSource.js
  athena/models/usersChannels.js
  athena/models/usersCommunities.js
  athena/queues/private-channel-request-approved.js
  athena/queues/private-channel-request-sent.js
  cypress/integration/community_settings_overview_spec.js
  shared/bull/queues.js
  shared/bull/types.js
  src/components/toasts/index.js
  src/views/channel/index.js
  src/views/communitySettings/components/brandedLogin.js
  src/views/communitySettings/components/brandedLoginToggle.js
  src/views/communitySettings/components/editForm.js
Labels: Ready for Review

#2935 Use a .prettierrc to allow editors to pick up Prettier config.
  .prettierignore
  .prettierrc
  package.json
Labels: Ready for Review

#2933 Update readme with yarn run db:reset
  README.md
Labels: Ready for Review

#2928 Add local file storage for dev environments
  .gitignore
  api/models/community.js
  api/models/user.js
  api/mutations/directMessageThread/createDirectMessageThread.js
  api/mutations/message/addMessage.js
  api/mutations/thread/editThread.js
  api/mutations/thread/publishThread.js
  api/utils/file-storage.js
  api/utils/file-system.js
  api/utils/s3.js
  package.json
  shared/types.js
Labels: Ready for Review, WIP: Needs Testing

#2938 Closes #2748 - Write test for sending messages in private channels.
  cypress/integration/thread_spec.js
Labels: Ready for Review

#2946 Deduplicate threads once and for all
  src/components/infiniteScroll/deduplicateChildren.js
  src/components/infiniteScroll/index.js
  src/components/threadFeed/index.js
  src/views/community/components/memberGrid.js
  src/views/dashboard/components/threadFeed.js
  src/views/directMessages/components/threadsList.js
  src/views/navbar/components/notificationsTab.js
  src/views/notifications/index.js
  src/views/notifications/utils.js
  src/views/thread/components/messages.js
Labels: Ready for Review

#2948 Update searchInput.js
  src/views/search/searchInput.js
Labels: Ready for Review

#2951 Update fragments.md
  docs/api/graphql/fragments.md
Labels: Ready for Review

#2955 Add syntax highlighting in Deleting Users
  docs/operations/deleting-users.md
Labels: Ready for Review

#2949 Resolve collapsing chat input for DMs
  src/components/chatInput/style.js
Labels: Ready for Review

#2960 Fix/GitHub theme
  src/components/loginButtonSet/style.js
  src/components/theme/index.js
Labels: Ready for Review

#2959 chore(src): replace tab-charactor to whitespace
  src/components/globals/index.js
  src/components/linkPreview/style.js
  src/components/loginButtonSet/style.js
  src/components/reaction/style.js
  src/components/scrollRow/style.js
  src/components/toasts/style.js
  src/components/upsell/style.js
  src/views/pages/style.js
Labels: Ready for Review

#2954 Fix url link mention
  shared/clients/draft-js/mentions-decorator/core.js
  shared/get-mentions.js
  shared/regexps.js
  shared/test/get-mentions.test.js
Labels: Ready for Review

#2924 Message replies
  api/loaders/index.js
  api/loaders/message.js
  api/models/message.js
  api/mutations/message/addMessage.js
  api/queries/message/index.js
  api/queries/message/parent.js
  api/queries/message/rootMessage.js
  api/types/Message.js
  athena/queues/new-message-in-thread/index.js
  cypress/integration/thread/chat_input_spec.js
  shared/graphql/fragments/message/directMessageInfo.js
  shared/graphql/fragments/message/messageInfo.js
  shared/graphql/mutations/message/sendMessage.js
  shared/graphql/queries/message/getMessage.js
  shared/types.js
  src/actions/message.js
  src/components/chatInput/components/style.js
  src/components/chatInput/index.js
  src/components/chatInput/input.js
  src/components/chatInput/style.js
  src/components/icons/index.js
  src/components/message/index.js
  src/components/message/style.js
  src/components/message/view.js
  src/reducers/index.js
  src/reducers/message.js
  src/views/directMessages/components/messages.js
  src/views/navbar/components/messagesTab.js
  src/views/navbar/components/notificationsTab.js
Labels: Ready for Review

#2895 Mobile thread view
  flow-typed/npm/react-native-keyboard-spacer_vx.x.x.js
  mobile/.expo/settings.json
  mobile/components/Anchor/index.js
  mobile/components/ChatInput/index.js
  mobile/components/Message/index.js
  mobile/components/Message/style.js
  mobile/components/Messages/Author.js
  mobile/components/Messages/RoboText.js
  mobile/components/Messages/index.js
  mobile/components/Text/index.js
  mobile/components/ThreadItem/Facepile.js
  mobile/package.json
  mobile/views/TabBar/index.js
  mobile/views/Thread/components/ActionBar.js
  mobile/views/Thread/components/Byline.js
  mobile/views/Thread/components/CommunityHeader.js
  mobile/views/Thread/index.js
  mobile/views/Thread/style.js
  mobile/yarn.lock
  shared/clients/draft-js/mentions-decorator/index.native.js
  shared/clients/draft-js/message/renderer.native.js
  shared/clients/draft-js/message/renderer.web.js
  shared/clients/draft-js/message/types.js
  shared/graphql/mutations/message/sendMessage.js
Labels: Ready for Review, WIP: Building

#2832 Local storage clear 2723
  cypress/integration/messages_spec.js
  cypress/integration/thread/chat_input_spec.js
  cypress/integration/thread_spec.js
  src/components/chatInput/index.js
  src/components/composer/index.js
  src/components/threadComposer/components/composer.js
  src/views/thread/index.js
Labels: Ready for Review, WIP: Building, WIP: Needs Testing

#2939 Frontend bundle size improvements
  config-overrides.js
  package.json
  src/components/rich-text-editor/container.js
  src/components/rich-text-editor/index.js
  src/helpers/utils.js
  src/routes.js
  src/views/communityBilling/components/administratorEmailForm.js
  src/views/directMessages/containers/index.js
  src/views/directMessages/index.js
  src/views/thread/container.js
  src/views/thread/index.js
  yarn.lock
Labels: Ready for Review

#2937 Fix the thread flyout behavior
  package.json
  src/components/flyout/index.js
  src/views/thread/components/actionBar.js
  src/views/thread/style.js
Labels: Ready for Review

#2974 Include SENTRY_DSN_CLIENT in webpack config - Closes #2908
  config-overrides.js
Labels: Ready for Review

#2964 Send notifications for watercooler threads
  api/mutations/message/addMessage.js
  src/views/thread/components/sidebar.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/container.js
  src/views/thread/style.js
Labels: Ready for Review

#2771 Media type and file size server validation
  api/models/community.js
  api/models/user.js
  api/mutations/directMessageThread/createDirectMessageThread.js
  api/mutations/message/addMessage.js
  api/mutations/thread/editThread.js
  api/mutations/thread/publishThread.js
  api/routes/middlewares/index.js
  api/utils/s3.js
Labels: Ready for Review, WIP: Needs Testing

#2978 Add continuous deployment for alpha
  .circleci/config.yml
Labels: Ready for Review, WIP: Building, WIP: Needs Testing

#2976 Fix nested mentions
  docs/testing/unit.md
  shared/clients/draft-js/mentions-decorator/core.js
  shared/clients/draft-js/mentions-decorator/test/core.test.js
Labels: Ready for Review, WIP: Building

#2981 Updated Apollo dependencies for Mobile App
  mobile/package.json
  mobile/yarn.lock
Labels: Ready for Review
