Repository withspectrum/spectrum, pull requests merged in 2018-08, with the labels that each got.

#3701 Enable host validation in API, fix CSRF
  api/index.js
  api/package.json
  api/yarn.lock
  package.json
  shared/middlewares/csrf.js
  yarn.lock
Labels: Ready for Review, WIP: Needs Testing

#3700 Fix CORS configuration
  shared/middlewares/cors.js
Labels: Ready for Review

#3699 Escape thread title before sharing to facebook
  src/views/newCommunity/components/share/index.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/watercoolerActionBar.js
Labels: Ready for Review

#3697 Force cookies to be same site
  shared/middlewares/session.js
Labels: Ready for Review

#3696 Use now CDN for SSR'd pages
  hyperion/cache.js
  hyperion/create-cache-stream.js
  hyperion/index.js
  hyperion/redis.js
  hyperion/renderer/index.js
Labels: Ready for Review

#3702 Remove snarky copy
  src/components/usernameSearch/index.js
Labels: Ready for Review

#3607 remove unnecessary $FlowFixMe
  src/components/toasts/index.js
Labels: Ready for Review

#3499 Fix GraphQL getEverythingThreads error for userId BRIAN_ID in test data
  README.md
  api/migrations/seed/default/threads.js
Labels: Ready for Review

#3704 2.4.22
  README.md
  api/index.js
  api/migrations/seed/default/threads.js
  api/package.json
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  hyperion/cache.js
  hyperion/create-cache-stream.js
  hyperion/index.js
  hyperion/redis.js
  hyperion/renderer/index.js
  mercury/package.json
  mercury/yarn.lock
  mobile/components/ThreadComposer/components/LocationPicker.js
  mobile/package.json
  mobile/yarn.lock
  package.json
  pluto/package.json
  pluto/yarn.lock
  shared/middlewares/cors.js
  shared/middlewares/csrf.js
  shared/middlewares/session.js
  src/components/threadLikes/style.js
  src/components/toasts/index.js
  src/components/usernameSearch/index.js
  src/helpers/directMessageThreads.js
  src/views/community/index.js
  src/views/newCommunity/components/share/index.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/watercoolerActionBar.js
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review

#3705 Fix message actions zindex
  src/views/thread/style.js
Labels: Ready for Review

#3709 Enable now CDN for static files
  hyperion/index.js
Labels: Ready for Review

#3716 Custom ServiceWorker caching configuration
  config-overrides.js
Labels: Ready for Review

#3720 Fix thread SSR
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#3721 v2.4.23
  api/package.json
  api/yarn.lock
  config-overrides.js
  hyperion/index.js
  mobile/package.json
  mobile/yarn.lock
  src/views/thread/components/threadDetail.js
  src/views/thread/style.js
Labels: Ready for Review

#3511 ✨ Add signin link in navbar for loggedout user
  src/views/navbar/index.js
  src/views/navbar/style.js
Labels: Ready for Review

#3495 Community Analytics v1.1
  api/models/reputationEvents.js
  api/queries/community/conversationGrowth.js
  api/queries/community/topAndNewThreads.js
  api/queries/community/topMembers.js
  shared/graphql/queries/community/getCommunityTopAndNewThreads.js
  shared/graphql/queries/community/getCommunityTopMembers.js
  src/components/settingsViews/style.js
  src/views/communityAnalytics/components/analyticsUpsell/index.js
  src/views/communityAnalytics/components/analyticsUpsell/style.js
  src/views/communityAnalytics/components/topAndNewThreads.js
  src/views/communityAnalytics/components/topMembers.js
  src/views/communityAnalytics/index.js
  src/views/dashboard/components/sidebarChannels.js
Labels: WIP: Building

#3480 Pro user upsells
  src/actions/modals.js
  src/components/modals/modalRoot.js
  src/views/navbar/components/profileDropdown.js
  src/views/navbar/index.js
Labels: Ready for Review

#2878 improve DM empty state
  src/views/directMessages/components/style.js
  src/views/directMessages/components/threadsList.js
  src/views/directMessages/containers/index.js
  src/views/directMessages/containers/newThread.js
  src/views/directMessages/style.js
Labels: Ready for Review

#3042 Encourage social media share
  shared/graphql/fragments/thread/threadInfo.js
  shared/graphql/fragments/thread/threadMessageConnection.js
  src/views/thread/components/messages.js
  src/views/thread/style.js
Labels: Ready for Review, WIP: Building, WIP: Needs Testing

#3725 Implement Community.metaData.onlineMembers
  api/loaders/community.js
  api/loaders/index.js
  api/models/community.js
  api/models/user.js
  api/queries/community/metaData.js
  api/routes/create-subscription-server.js
  api/types/Community.js
Labels: Ready for Review

#3728 Fix flex on short dm snippets
  src/views/directMessages/components/style.js
Labels: Ready for Review

#3729 Dont show hover profiles on direct message items
  src/views/directMessages/components/avatars.js
Labels: Ready for Review

#3730 FIx double hover profiles, small styling nits
  src/components/badges/style.js
  src/components/granularUserProfile/index.js
  src/components/granularUserProfile/style.js
Labels: Ready for Review

#3734 Add zeit.co to CORS whitelist
  shared/middlewares/cors.js
Labels: Ready for Review

#3735 Fix mobile menu gap
  src/components/menu/style.js
  src/views/thread/components/messages.js
  src/views/thread/style.js
Labels: Ready for Review

#3741 Update markdown-plugin
  package.json
  yarn.lock
Labels: Ready for Review

#3740 Fix alpha continuous deployment
  .circleci/config.yml
Labels: Ready for Review

#3739 Prod cut
  .circleci/config.yml
  api/loaders/community.js
  api/loaders/index.js
  api/models/community.js
  api/models/reputationEvents.js
  api/models/user.js
  api/package.json
  api/queries/community/conversationGrowth.js
  api/queries/community/metaData.js
  api/queries/community/topAndNewThreads.js
  api/queries/community/topMembers.js
  api/routes/create-subscription-server.js
  api/types/Community.js
  api/yarn.lock
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/graphql/fragments/thread/threadInfo.js
  shared/graphql/fragments/thread/threadMessageConnection.js
  shared/graphql/queries/community/getCommunityTopAndNewThreads.js
  shared/graphql/queries/community/getCommunityTopMembers.js
  shared/middlewares/cors.js
  src/actions/modals.js
  src/components/badges/style.js
  src/components/granularUserProfile/index.js
  src/components/granularUserProfile/style.js
  src/components/menu/style.js
  src/components/modals/modalRoot.js
  src/components/settingsViews/style.js
  src/views/community/components/moderatorList.js
  src/views/communityAnalytics/components/analyticsUpsell/index.js
  src/views/communityAnalytics/components/analyticsUpsell/style.js
  src/views/communityAnalytics/components/topAndNewThreads.js
  src/views/communityAnalytics/components/topMembers.js
  src/views/communityAnalytics/index.js
  src/views/dashboard/components/sidebarChannels.js
  src/views/directMessages/components/avatars.js
  src/views/directMessages/components/style.js
  src/views/directMessages/components/threadsList.js
  src/views/directMessages/containers/index.js
  src/views/directMessages/containers/newThread.js
  src/views/directMessages/style.js
  src/views/navbar/components/profileDropdown.js
  src/views/navbar/index.js
  src/views/navbar/style.js
  src/views/thread/components/messages.js
  src/views/thread/style.js
  yarn.lock
Labels: Ready for Review

#3753 Fix forwarding to newest version of JS bundle chunks
  hyperion/index.js
Labels: Ready for Review

#3754 Fix emoji message replies
  src/components/message/view.js
Labels: Ready for Review

#3758 Prod cut
  analytics/package.json
  analytics/yarn.lock
  hyperion/index.js
  mobile/package.json
  mobile/yarn.lock
  now.json
  package.json
  pluto/package.json
  pluto/yarn.lock
  src/components/message/view.js
Labels: Ready for Review

#3761 Fix API logging undefined over and over
  api/routes/create-subscription-server.js
  api/utils/session-store.js
Labels: Ready for Review

#3742 Better thread meta images
  src/helpers/generate-image-from-text.js
  src/views/thread/container.js
Labels: Ready for Review

#3764 Allow Zeit staging domain to access API
  shared/middlewares/cors.js
Labels: Ready for Review

#3765 2.4.25
  api/routes/create-subscription-server.js
  api/utils/session-store.js
  now.json
  package.json
  shared/middlewares/cors.js
  src/helpers/generate-image-from-text.js
  src/views/notifications/utils.js
  src/views/thread/container.js
Labels: Ready for Review

#3768 Fix thread meta image title
  src/helpers/generate-image-from-text.js
  src/views/thread/container.js
Labels: Ready for Review, WIP: Building

#3790 Fix thread url in notifications card
  src/views/notifications/utils.js
Labels: Ready for Review

#3791 Add spacing to narrow viewport slack channel settings list
  src/views/communitySettings/components/slack/style.js
Labels: Ready for Review

#3792 2.4.26
  api/index.js
  api/mutations/user/index.js
  api/mutations/user/reportUser.js
  api/package.json
  api/queries/community/metaData.js
  api/routes/api/graphql.js
  api/types/Community.js
  api/types/User.js
  api/yarn.lock
  cypress/integration/navbar_spec.js
  desktop/package.json
  desktop/yarn.lock
  email-templates/adminUserReported.html
  hermes/index.js
  hermes/models/user.js
  hermes/package.json
  hermes/queues/constants.js
  hermes/queues/send-admin-user-reported-email.js
  hermes/yarn.lock
  mercury/package.json
  mercury/yarn.lock
  mobile/package.json
  mobile/yarn.lock
  package.json
  pluto/package.json
  pluto/yarn.lock
  shared/analytics/event-types/user.js
  shared/bull/queues.js
  shared/bull/types.js
  shared/graphql/mutations/user/reportUser.js
  src/components/modals/ReportUserModal/index.js
  src/components/modals/ReportUserModal/style.js
  src/components/modals/modalRoot.js
  src/helpers/generate-image-from-text.js
  src/views/communitySettings/components/slack/style.js
  src/views/navbar/index.js
  src/views/navbar/style.js
  src/views/notifications/utils.js
  src/views/thread/container.js
  src/views/user/index.js
Labels: Ready for Review

#3809 Properly guard generating thread meta images
  src/helpers/generate-image-from-text.js
  src/views/thread/container.js
Labels: Ready for Review

#3810 Fix thread meta images with emojis in them
  flow-typed/npm/b2a_vx.x.x.js
  package.json
  shared/graphql/mutations/message/sendDirectMessage.js
  shared/graphql/mutations/message/sendMessage.js
  shared/graphql/queries/directMessageThread/getDirectMessageThreadMessageConnection.js
  shared/graphql/queries/thread/getThreadMessageConnection.js
  src/components/message/index.js
  src/helpers/generate-image-from-text.js
  yarn.lock
Labels: Ready for Review

#3805 Maybe fix perpetually being signed out
  src/helpers/signed-out-fallback.js
  src/routes.js
  src/views/authViewHandler/index.js
Labels: Ready for Review

#3814 2.4.27
  analytics/package.json
  analytics/yarn.lock
  docs/operations/importing-rethinkdb-backups.md
  flow-typed/npm/b2a_vx.x.x.js
  hyperion/renderer/html-template.js
  mobile/package.json
  mobile/yarn.lock
  package.json
  pluto/package.json
  pluto/yarn.lock
  public/index.html
  shared/graphql/mutations/message/sendDirectMessage.js
  shared/graphql/mutations/message/sendMessage.js
  shared/graphql/queries/community/getCommunities.js
  shared/graphql/queries/directMessageThread/getDirectMessageThreadMessageConnection.js
  shared/graphql/queries/thread/getThreadMessageConnection.js
  src/components/head/index.js
  src/components/message/index.js
  src/helpers/generate-image-from-text.js
  src/helpers/signed-out-fallback.js
  src/routes.js
  src/views/authViewHandler/index.js
  src/views/explore/collections.js
  src/views/explore/view.js
  src/views/thread/container.js
  src/views/user/index.js
  yarn.lock
Labels: Ready for Review

#3766 Fix list items overflows
  api/models/usersChannels.js
  api/mutations/channel/toggleChannelNotifications.js
  src/components/granularUserProfile/style.js
  src/components/listItems/channel/index.js
  src/components/listItems/channel/style.js
  src/components/listItems/index.js
  src/components/modals/CreateChannelModal/index.js
  src/components/profile/channel.js
  src/components/profile/index.js
  src/views/channel/index.js
  src/views/channel/style.js
  src/views/community/components/channelList.js
  src/views/community/style.js
  src/views/communitySettings/components/channelList.js
  src/views/communitySettings/style.js
  src/views/notifications/components/newChannelNotification.js
  src/views/notifications/style.js
Labels: WIP: Building

#3817 Update to draft-js-markdown-plugin@3.0.3
  package.json
  yarn.lock
Labels: Ready for Review

#3818 Fix perpetually being signed out AGAIN
  api/routes/auth/create-signin-routes.js
Labels: Ready for Review

#3798 Frecency thread feeds (second try)
  api/models/thread.js
  api/mutations/message/addMessage.js
  api/mutations/message/deleteMessage.js
  api/mutations/thread/addThreadReaction.js
  api/mutations/thread/removeThreadReaction.js
  api/queries/community/threadConnection.js
  api/queries/thread/rootThread.js
  api/types/Community.js
  mercury/constants.js
  mercury/index.js
  mercury/models/thread.js
  mercury/queues/calculateThreadScore.js
  shared/bull/queues.js
  shared/bull/types.js
  shared/types.js
Labels: Ready for Review, WIP: Building

#3816 Add context to team badge on hover
  cypress/integration/community/view/profile_spec.js
  src/components/badges/index.js
Labels: Ready for Review

#3819 2.4.28
  api/models/thread.js
  api/models/usersChannels.js
  api/mutations/channel/toggleChannelNotifications.js
  api/mutations/message/addMessage.js
  api/mutations/message/deleteMessage.js
  api/mutations/thread/addThreadReaction.js
  api/mutations/thread/removeThreadReaction.js
  api/queries/community/threadConnection.js
  api/queries/thread/rootThread.js
  api/routes/auth/create-signin-routes.js
  api/types/Community.js
  cypress/integration/community/view/profile_spec.js
  mercury/constants.js
  mercury/index.js
  mercury/models/thread.js
  mercury/queues/calculateThreadScore.js
  package.json
  shared/bull/queues.js
  shared/bull/types.js
  shared/types.js
  src/components/badges/index.js
  src/components/granularUserProfile/style.js
  src/components/listItems/channel/index.js
  src/components/listItems/channel/style.js
  src/components/listItems/index.js
  src/components/modals/CreateChannelModal/index.js
  src/components/profile/channel.js
  src/components/profile/index.js
  src/views/channel/index.js
  src/views/channel/style.js
  src/views/community/components/channelList.js
  src/views/community/style.js
  src/views/communitySettings/components/channelList.js
  src/views/communitySettings/style.js
  src/views/notifications/components/newChannelNotification.js
  src/views/notifications/style.js
  yarn.lock
Labels: Ready for Review

#3826 Fix db load on usersCommunities table
  .gitignore
  api/migrations/20180823115847-add-users-communities-indexes.js
  api/models/usersCommunities.js
  api/queries/community/members.js
  api/test/__snapshots__/community.test.js.snap
  athena/models/usersCommunities.js
  cacert
  chronos/models/community.js
  mercury/models/usersCommunities.js
  pluto/models/usersCommunities.js
Labels: Ready for Review

#3838 athena: use userIdAndThreadId index on usersThread
  athena/models/usersThreads.js
Labels: Ready for Review

#3837 Fix pasting text into code blocks
  package.json
  yarn.lock
Labels: Ready for Review

#3836 Don't scroll empty threads to bottom
  src/views/thread/components/messages.js
Labels: Ready for Review

#3835 Fix new messages indicator
  src/views/thread/container.js
Labels: Ready for Review

#3834 Clean up thread top area
  shared/time-formatting.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#3833 Always show reputation on user profile
  src/components/profile/user.js
Labels: Ready for Review

#3832 Small UI copy changes
  src/views/dashboard/components/communityList.js
  src/views/dashboard/components/sidebarChannels.js
  src/views/dashboard/style.js
Labels: Ready for Review

#3844 2.4.29
  .gitignore
  api/index.js
  api/migrations/20180823115847-add-users-communities-indexes.js
  api/models/usersCommunities.js
  api/package.json
  api/queries/community/members.js
  api/routes/api/graphql.js
  api/test/__snapshots__/community.test.js.snap
  api/types/Community.js
  api/yarn.lock
  athena/models/usersCommunities.js
  athena/models/usersThreads.js
  cacert
  chronos/models/community.js
  hermes/package.json
  hermes/yarn.lock
  mercury/models/usersCommunities.js
  mobile/package.json
  mobile/yarn.lock
  package.json
  pluto/models/usersCommunities.js
  shared/time-formatting.js
  src/components/profile/user.js
  src/views/dashboard/components/communityList.js
  src/views/dashboard/components/sidebarChannels.js
  src/views/dashboard/style.js
  src/views/thread/components/messages.js
  src/views/thread/components/threadDetail.js
  src/views/thread/container.js
  yarn.lock
Labels: Ready for Review

#3845 Community login redirect
  cypress/integration/login_spec.js
  src/views/communityLogin/index.js
Labels: Ready for Review

#3846 Remove unnecessary zindex
  src/components/chatInput/style.js
  src/components/message/style.js
  src/views/thread/style.js
Labels: Ready for Review

#3847 Fix link location on reaction notifications
  src/views/notifications/utils.js
Labels: Ready for Review

#3848 Make user rported email subject lines a bit more clear
  hermes/queues/send-admin-user-reported-email.js
Labels: Ready for Review

#3850 Fix loading state on community search
  src/views/explore/components/search.js
Labels: Ready for Review

#3851 v2.4.30
  cypress/integration/login_spec.js
  hermes/queues/send-admin-user-reported-email.js
  mobile/package.json
  mobile/yarn.lock
  package.json
  src/components/chatInput/style.js
  src/components/message/style.js
  src/views/communityLogin/index.js
  src/views/explore/components/search.js
  src/views/notifications/utils.js
  src/views/thread/style.js
Labels: Ready for Review

#3858 Redirect logged-in users when accessing the community login page (#3841)
  src/routes.js
Labels: Ready for Review

#3853 Clean up thread view and inbox thread loading shimmers
  src/components/loading/index.js
  src/components/loading/style.js
  src/routes.js
  src/views/dashboardThread/index.js
  src/views/thread/components/sidebar.js
  src/views/thread/container.js
  src/views/thread/index.js
  src/views/threadSlider/index.js
Labels: Ready for Review

#3865 Only trigger notifications and reputation events for thread non-authors
  api/models/threadReaction.js
Labels: Ready for Review

#3866 Fix explore perf + nits
  shared/graphql/queries/community/getCommunities.js
  src/components/profile/style.js
  src/views/explore/components/search.js
  src/views/thread/components/sidebar.js
Labels: Ready for Review

#3868 2.4.32
  api/models/threadReaction.js
  desktop/package.json
  desktop/yarn.lock
  package.json
  shared/graphql/queries/community/getCommunities.js
  src/components/granularUserProfile/style.js
  src/components/loading/index.js
  src/components/loading/style.js
  src/components/profile/style.js
  src/components/upsell/index.js
  src/routes.js
  src/views/community/components/moderatorList.js
  src/views/dashboardThread/index.js
  src/views/explore/components/search.js
  src/views/thread/components/sidebar.js
  src/views/thread/container.js
  src/views/thread/index.js
  src/views/threadSlider/index.js
Labels: Ready for Review

#3869 Fix dom nesting error on explore
  src/components/profile/community.js
Labels: Ready for Review

#3870 2.4.33
  package.json
  src/components/profile/community.js
Labels: Ready for Review

#3873 Enable Apollo Engine again
  api/index.js
  api/routes/api/graphql.js
  api/types/Community.js
Labels: Ready for Review

#3840 Turn off SW caching
  config-overrides.js
  src/components/link/index.js
  src/components/link/props.js
  src/index.js
Labels: Ready for Review, WIP: Building, WIP: Needs Testing
