Repository withspectrum/spectrum, pull requests merged in 2018-10, with the labels that each got.

#3726 Denormalize thread meta data (message & reaction counts)
  api/loaders/index.js
  api/loaders/thread.js
  api/migrations/20180807060551-thread-metadata-denormalization.js
  api/migrations/seed/default/threads.js
  api/models/message.js
  api/models/thread.js
  api/models/threadReaction.js
  api/queries/thread/index.js
  api/queries/thread/messageCount.js
  shared/types.js
Labels: Ready for Review

#3969 2.4.38
  api/authentication.js
  api/loaders/index.js
  api/loaders/thread.js
  api/migrations/20180807060551-thread-metadata-denormalization.js
  api/migrations/seed/default/threads.js
  api/models/message.js
  api/models/thread.js
  api/models/threadReaction.js
  api/package.json
  api/queries/thread/index.js
  api/queries/thread/messageCount.js
  api/utils/session-store.js
  api/yarn.lock
  hyperion/index.js
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/types.js
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review

#3972 Re-order migrations for prod migration
  api/migrations/20181001061156-thread-metadata-denormalization.js
Labels: Ready for Review

#3973 Add migration to fix message counts on threads
  api/migrations/20181001064151-fix-thread-metadata-message-counts.js
Labels: Ready for Review

#3984 Investigate auth issues
  api/authentication.js
Labels: WIP: Building

#3985 Fix auth
  api/mutations/user/editUser.js
Labels: Ready for Review

#3986 2.4.40
  api/authentication.js
  api/mutations/user/editUser.js
  package.json
Labels: Ready for Review

#3987 Maybe fix user onboarding?
  src/views/dashboard/index.js
Labels: WIP: Needs Testing

#3988 2.4.41
  package.json
  src/views/dashboard/index.js
Labels: Ready for Review

#3989 Reduce load on threads table in daily digests
  chronos/models/thread.js
  chronos/queues/digests/processThreads.js
Labels: Ready for Review

#3993 Upgrade apollo-engine to latest
  api/package.json
  api/yarn.lock
Labels: Ready for Review

#3990 Remove "✌️Spectrum Team" message from notification emails
  email-templates/communityInvite.html
  email-templates/mentionInMessage.html
  email-templates/mentionInThread.html
  email-templates/newThreadNotification.html
  email-templates/privateChannelRequestApproved.html
  email-templates/privateChannelRequestSent.html
  email-templates/privateCommunityRequestApproved.html
  email-templates/privateCommunityRequestSent.html
  email-templates/weeklyDigest.html
Labels: Ready for Review

#3974 Stop loading all thread reactions, use denormalized count
  api/migrations/20181003233411-thread-reactions-useridandthreadid-index.js
  api/models/threadReaction.js
  api/queries/thread/reactions.js
Labels: Ready for Review

#3855 Upgrade to Apollo Server v2
  admin/package.json
  api/apollo-server.js
  api/index.js
  api/loaders/types.js
  api/models/usersChannels.js
  api/package.json
  api/routes/api/graphiql.js
  api/routes/api/graphql.js
  api/routes/api/index.js
  api/routes/create-subscription-server.js
  api/routes/middlewares/index.js
  api/subscriptions/thread.js
  api/test/utils/__snapshots__/create-graphql-error-formatter.test.js.snap
  api/types/Channel.js
  api/types/Community.js
  api/types/CommunityMember.js
  api/types/DirectMessageThread.js
  api/types/Notification.js
  api/types/Search.js
  api/types/Thread.js
  api/types/User.js
  api/types/general.js
  api/types/scalars.js
  api/yarn.lock
  package.json
  shared/middlewares/cors.js
  shared/middlewares/error-handler.js
  yarn.lock
Labels: Ready for Review

#3752 Guard DM subscription properly
  shared/graphql/queries/notification/getDirectMessageNotifications.js
Labels: Ready for Review

#3998 Ban users
  api/models/directMessageThread.js
  api/models/user.js
  api/models/usersCommunities.js
  api/models/usersSettings.js
  api/mutations/user/banUser.js
  api/mutations/user/deleteCurrentUser.js
  api/mutations/user/index.js
  api/types/User.js
  docs/operations/banning-users.md
  docs/operations/deleting-users.md
  shared/analytics/event-types/user.js
  shared/graphql/mutations/user/banUser.js
  src/components/modals/BanUserModal/index.js
  src/components/modals/BanUserModal/style.js
  src/components/modals/modalRoot.js
  src/helpers/is-admin.js
  src/views/user/index.js
Labels: Ready for Review

#3977 Denormalize member counts
  api/loaders/channel.js
  api/loaders/community.js
  api/loaders/index.js
  api/migrations/20181001073107-denormalize-channel-community-member-counts.js
  api/migrations/seed/default/channels.js
  api/migrations/seed/default/communities.js
  api/models/channel.js
  api/models/community.js
  api/models/test/__snapshots__/channel.test.js.snap
  api/models/test/channel.test.js
  api/models/usersChannels.js
  api/models/usersCommunities.js
  api/mutations/communityMember/addCommunityMember.js
  api/mutations/communityMember/removeCommunityMember.js
  api/queries/channel/memberCount.js
  api/queries/channel/metaData.js
  api/queries/community/memberGrowth.js
  api/queries/community/metaData.js
  shared/types.js
Labels: Ready for Review, WIP: Building

#4016 Reorder migrations
  api/migrations/20181004222636-denormalize-channel-community-member-counts.js
Labels: Ready for Review

#4025 Initialize new communities and channels with memberCount: 1
  api/models/channel.js
  api/models/community.js
Labels: Ready for Review

#4024 Publish threads with reaction/messageCount 0
  api/models/thread.js
Labels: Ready for Review

#4020 Deprecate Channel.metaData.threads
  api/queries/channel/metaData.js
  api/types/Channel.js
Labels: Ready for Review

#4028 DirectMessageThread.snippet can be null
  api/types/DirectMessageThread.js
Labels: Ready for Review

#4033 Use apollo-link-schema for SSR
  hyperion/renderer/index.js
  package.json
  yarn.lock
Labels: Ready for Review

#4057 Use em dashes & rich quote
  src/views/thread/components/messages.js
Labels: Ready for Review

#4060 Add privacy and terms links to login views
  src/components/modals/ChatInputLoginModal/index.js
  src/components/modals/ChatInputLoginModal/style.js
  src/views/login/index.js
  src/views/login/style.js
Labels: Ready for Review

#4072 Bug smashing
  api/models/usersSettings.js
  api/queries/channel/channelPermissions.js
  api/queries/channel/communityPermissions.js
  api/queries/community/communityPermissions.js
  api/queries/user/settings.js
  api/types/CommunityMember.js
  athena/queues/moderationEvents/thread.js
  athena/queues/private-channel-request-approved.js
  package.json
  src/components/gallery/browser.js
  src/views/user/index.js
  yarn.lock
Labels: WIP: Building

#4082 2.4.44
  api/mutations/message/addMessage.js
  api/mutations/thread/addThreadReaction.js
  api/mutations/thread/removeThreadReaction.js
  api/queries/channel/community.js
  api/queries/channel/joinSettings.js
  api/queries/channel/memberConnection.js
  api/queries/channel/memberCount.js
  api/queries/channel/metaData.js
  api/queries/channel/moderators.js
  api/queries/channel/owners.js
  api/queries/channel/rootChannel.js
  api/queries/channel/threadConnection.js
  api/queries/community/joinSettings.js
  api/queries/directMessageThread/messageConnection.js
  api/queries/directMessageThread/participants.js
  api/queries/directMessageThread/rootDirectMessageThread.js
  api/queries/directMessageThread/snippet.js
  api/queries/directMessageThread/utils.js
  api/test/channel/queries/__snapshots__/pendingUsers.test.js.snap
  api/test/channel/queries/channelSettings.test.js
  api/utils/permissions.js
  cypress/integration/channel/view/membership_spec.js
  cypress/integration/channel/view/profile_spec.js
  mobile/app.json
  package.json
  src/components/threadLikes/index.js
Labels: Ready for Review

#4078 Remove unused access token authentication
  api/routes/auth/create-signin-routes.js
  api/routes/middlewares/index.js
Labels: Ready for Review

#4079 Add state to GitHub auth
  api/routes/auth/github.js
Labels: Ready for Review

#4081 Sanitize URLs
  package.json
  shared/normalize-url.js
  shared/test/normalize-url.test.js
  yarn.lock
Labels: Ready for Review

#4080 Enable CSP
  api/index.js
  hyperion/index.js
  hyperion/renderer/html-template.js
  hyperion/renderer/index.js
  shared/middlewares/security.js
Labels: Ready for Review, WIP: Building, WIP: Needs Testing

#4084 2.4.45
  api/index.js
  api/routes/auth/create-signin-routes.js
  api/routes/auth/github.js
  api/routes/middlewares/index.js
  hyperion/index.js
  hyperion/renderer/html-template.js
  hyperion/renderer/index.js
  package.json
  shared/middlewares/security.js
  shared/normalize-url.js
  shared/test/normalize-url.test.js
  yarn.lock
Labels: Ready for Review

#4085 Fix cover photo uploads breaking
  api/mutations/user/editUser.js
Labels: Ready for Review

#4089 Allow data local image uploads to work with CSP
  shared/middlewares/security.js
Labels: Ready for Review

#4090 2.4.47
  package.json
  shared/middlewares/security.js
Labels: Ready for Review

#4092 Fix bad community member count
  api/migrations/20181023160027-update-denormalized-member-counts.js
  api/models/channel.js
  api/models/community.js
  cypress/integration/thread/view_spec.js
Labels: Ready for Review

#4093 Fix evaluating null channel if channel doesn't exist in db
  api/queries/channel/rootChannel.js
Labels: Ready for Review

#4095 Update shim and dependencies
  hyperion/renderer/browser-shim.js
  package.json
  yarn.lock
Labels: Ready for Review

#4096 Fix shared db queries
  api/mutations/user/editUser.js
  cypress/integration/user/edit_user_spec.js
  shared/db/create-query.js
  src/actions/authentication.js
  src/components/usernameSearch/index.js
  src/components/usernameSearch/style.js
  src/views/userSettings/components/editForm.js
Labels: Ready for Review

#4097 2.4.48
  api/mutations/user/editUser.js
  cypress/integration/user/edit_user_spec.js
  hyperion/renderer/browser-shim.js
  package.json
  shared/db/create-query.js
  src/actions/authentication.js
  src/components/usernameSearch/index.js
  src/components/usernameSearch/style.js
  src/views/userSettings/components/editForm.js
  yarn.lock
Labels: Ready for Review

#4098 Update packages for workers that are deployed with shared queries
  analytics/package.json
  analytics/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  hermes/package.json
  hermes/yarn.lock
Labels: Ready for Review

#4101 Fix user query if bad id is sent
  shared/db/queries/user.js
Labels: Ready for Review

#4099 Prevent undefined from possibly being passed into identifyQueue
  analytics/queues/identify-analytics.js
  shared/db/queries/user.js
Labels: Ready for Review

#4100 Downgrade react
  package.json
  yarn.lock
Labels: Ready for Review

#4102 2.4.49
  analytics/package.json
  analytics/queues/identify-analytics.js
  analytics/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  package.json
  shared/db/queries/user.js
  yarn.lock
Labels: Ready for Review

#4052 Implement fix for profile dropdown bug
  src/components/hoverProfile/style.js
  src/components/hoverProfile/userContainer.js
Labels: Ready for Review

#4107 Return user errors if image uploads fail
  api/utils/s3.js
Labels: Ready for Review

#4104 Temporarily fix auth
  shared/db/queries/user.js
Labels: Ready for Review

#4103 Disable alpha deployments via ci
  .circleci/config.yml
Labels: Ready for Review

#4115 Fix user not having id field in storeUser function
  analytics/utils/track.js
  shared/db/queries/user.js
Labels: Ready for Review

#4116 2.4.50
  .circleci/config.yml
  analytics/utils/track.js
  api/package.json
  api/utils/s3.js
  api/yarn.lock
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/db/queries/user.js
  src/components/hoverProfile/style.js
  src/components/hoverProfile/userContainer.js
Labels: Ready for Review

#4118 addresses a regression in firefox 62 that breaks scrolling
  src/views/pages/style.js
Labels: Ready for Review

#4117 Perf improvements for daily and weekly digests
  api/migrations/20181024173616-indexes-for-digests.js
  chronos/models/community.js
  chronos/models/coreMetrics.js
  chronos/models/usersSettings.js
  chronos/queues/coreMetrics/index.js
  chronos/queues/digests/index.js
Labels: Ready for Review

#4124 Hide notifs button on action bar signed out
  cypress/integration/thread/action_bar_spec.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/watercoolerActionBar.js
Labels: Ready for Review

#4122 Static fixes
  src/components/threadComposer/components/composer.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/newCommunity/index.js
  src/views/notifications/components/newThreadNotification.js
  src/views/notifications/components/sortAndGroupNotificationMessages.js
  src/views/notifications/index.js
  src/views/notifications/utils.js
  src/views/thread/components/messages.js
  src/views/thread/components/threadDetail.js
  src/views/thread/container.js
  src/views/user/index.js
  src/views/userSettings/components/editForm.js
  src/views/userSettings/index.js
Labels: Ready for Review

#4126 Remove link previews from threads
  src/components/composer/index.js
  src/components/linkPreview/index.js
  src/components/linkPreview/style.js
  src/components/rich-text-editor/container.js
  src/components/threadComposer/components/composer.js
  src/components/threadFeedCard/index.js
  src/components/threadFeedCard/style.js
  src/helpers/utils.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#4127 2.4.51
  api/migrations/20181024173616-indexes-for-digests.js
  chronos/models/community.js
  chronos/models/coreMetrics.js
  chronos/models/usersSettings.js
  chronos/queues/coreMetrics/index.js
  chronos/queues/digests/index.js
  cypress/integration/thread/action_bar_spec.js
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/middlewares/security.js
  src/components/composer/index.js
  src/components/linkPreview/index.js
  src/components/linkPreview/style.js
  src/components/rich-text-editor/container.js
  src/components/threadComposer/components/composer.js
  src/components/threadFeedCard/index.js
  src/components/threadFeedCard/style.js
  src/helpers/utils.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/newCommunity/index.js
  src/views/notifications/components/newThreadNotification.js
  src/views/notifications/components/sortAndGroupNotificationMessages.js
  src/views/notifications/index.js
  src/views/notifications/utils.js
  src/views/pages/style.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/messages.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/container.js
  src/views/user/index.js
  src/views/userSettings/components/editForm.js
  src/views/userSettings/index.js
Labels: Ready for Review

#4130 DB lookup on mutations for banned and deleted users
  api/utils/permissions.js
Labels: Ready for Review

#4133 Prevent qq emails from receiving notifications
  hermes/send-email.js
Labels: Ready for Review

#4137 Fully deprecate attachments on thread model
  api/migrations/20181027050052-remove-attachments-from-thread-model.js
  api/migrations/seed/default/messages.js
  api/migrations/seed/default/threads.js
  api/migrations/seed/generate.js
  api/models/thread.js
  api/mutations/thread/editThread.js
  api/mutations/thread/publishThread.js
  api/queries/thread/attachments.js
  api/test/channel/mutations/deleteChannel.test.js
  api/types/Thread.js
Labels: Ready for Review

#4142 2.4.52
  api/migrations/20181027050052-remove-attachments-from-thread-model.js
  api/migrations/seed/default/messages.js
  api/migrations/seed/default/threads.js
  api/migrations/seed/generate.js
  api/models/thread.js
  api/mutations/thread/editThread.js
  api/mutations/thread/publishThread.js
  api/package.json
  api/queries/thread/attachments.js
  api/test/channel/mutations/deleteChannel.test.js
  api/types/Thread.js
  api/utils/permissions.js
  api/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  docs/workers/background-jobs.md
  hermes/send-email.js
  mobile/package.json
  mobile/yarn.lock
  package.json
Labels: Ready for Review

#4146 Expire cookies after a week, refresh on every request
  api/routes/middlewares/index.js
  shared/middlewares/session.js
Labels: Ready for Review

#4153 Add image expiration context to hyperion schemalink
  hyperion/renderer/index.js
Labels: Ready for Review

#4155 Dont set acl at upload time
  api/utils/s3.js
Labels: Ready for Review

#4156 2.4.53 fix 2
  api/utils/s3.js
Labels: Ready for Review

#4159 Fix editing threads with image signing
  api/mutations/thread/editThread.js
  api/queries/thread/content/body.js
  shared/imgix/index.js
  src/views/thread/components/threadDetail.js
Labels: WIP: Building

#4160 2.4.54
  api/mutations/thread/editThread.js
  api/queries/thread/content/body.js
  package.json
  shared/imgix/index.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#4161 Fix dms
  api/mutations/directMessageThread/createDirectMessageThread.js
  api/queries/directMessageThread/participants.js
Labels: Ready for Review

#4162 2.5.55
  api/mutations/directMessageThread/createDirectMessageThread.js
  api/queries/directMessageThread/participants.js
  package.json
Labels: Ready for Review

#4165 Edit messages
  api/models/message.js
  api/models/thread.js
  api/mutations/message/editMessage.js
  api/mutations/message/index.js
  api/types/Message.js
  shared/analytics/event-types/directMessage.js
  shared/analytics/event-types/message.js
  shared/graphql/fragments/message/directMessageInfo.js
  shared/graphql/fragments/message/messageInfo.js
  shared/graphql/mutations/message/editMessage.js
  shared/types.js
  src/components/message/editingBody.js
  src/components/message/index.js
  src/components/message/style.js
Labels: Ready for Review

#4166 Edit messages tests
  cypress/integration/thread_spec.js
  src/components/message/editingBody.js
  src/components/message/index.js
Labels: Ready for Review

#4167 2.4.56
  api/models/message.js
  api/models/thread.js
  api/mutations/message/editMessage.js
  api/mutations/message/index.js
  api/types/Message.js
  cypress/integration/thread_spec.js
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/analytics/event-types/directMessage.js
  shared/analytics/event-types/message.js
  shared/graphql/fragments/message/directMessageInfo.js
  shared/graphql/fragments/message/messageInfo.js
  shared/graphql/mutations/message/editMessage.js
  shared/types.js
  src/components/message/editingBody.js
  src/components/message/index.js
  src/components/message/style.js
Labels: Ready for Review
