Repository withspectrum/spectrum, pull requests merged in 2018-11, with the labels that each got.

#4169 Add engine field in api package to make it deployable
  api/package.json
Labels: Ready for Review

#3645 Desktop release
  .circleci/config.yml
  desktop/package.json
  desktop/yarn.lock
  package.json
  src/components/profile/user.js
  src/views/channel/index.js
  src/views/communityAnalytics/components/topAndNewThreads.js
  src/views/communityAnalytics/components/topMembers.js
  src/views/pages/components/nav.js
  src/views/thread/components/threadByline.js
Labels: WIP: Building

#4176 Legacy images
  api/migrations/20181102025454-fix-old-image-urls-in-messages.js
  api/migrations/20181102040518-fix-old-image-urls-in-threads.js
  api/migrations/20181102044407-fix-old-image-urls-in-communities.js
  api/migrations/20181102045821-fix-old-image-urls-in-users.js
  api/migrations/20181102054523-fix-aws-static-url-community-photos.js
  api/utils/get-random-default-photo.js
  src/components/formElements/index.js
  src/views/dashboard/components/communityList.js
  src/views/dashboard/components/upsellExploreCommunities.js
  src/views/dashboard/style.js
Labels: Ready for Review

#4181 Fix broken field in optimistic response
  shared/graphql/mutations/message/sendDirectMessage.js
  shared/graphql/mutations/message/sendMessage.js
Labels: Ready for Review

#4177 Convert vulcan worker to redis jobs
  api/models/community.js
  api/models/message.js
  api/models/thread.js
  shared/bull/queues.js
  shared/bull/types.js
  shared/db/queries/community.js
  shared/db/queries/message.js
  shared/db/queries/notifications.js
  shared/db/queries/thread.js
  shared/db/queries/user.js
  vulcan/index.js
  vulcan/models/community.js
  vulcan/models/db.js
  vulcan/models/message.js
  vulcan/models/thread.js
  vulcan/models/user.js
  vulcan/queues/constants.js
  vulcan/queues/events/created.js
  vulcan/queues/events/deleted.js
  vulcan/queues/events/edited.js
  vulcan/queues/index.js
  vulcan/queues/types/community.js
  vulcan/queues/types/message.js
  vulcan/queues/types/thread/index.js
  vulcan/queues/types/thread/moved.js
  vulcan/queues/types/user.js
  vulcan/utils/get-queue-from-type.js
  vulcan/utils/index.js
  vulcan/utils/text-parsing.js
Labels: WIP: Needs Testing

#4192 Add packages to make vulcan deployable
  vulcan/package.json
  vulcan/yarn.lock
Labels: Ready for Review

#4193 Fix media message previews across the board
  api/queries/directMessageThread/snippet.js
  athena/queues/new-message-in-thread/format-data.js
  shared/notification-to-text.js
  shared/test/__snapshots__/notification-to-text.test.js.snap
  shared/test/fixtures/MEDIA_MESSAGE_CREATED.json
  shared/test/notification-to-text.test.js
Labels: Ready for Review

#4200 2.4.60
  analytics/package.json
  analytics/yarn.lock
  api/models/community.js
  api/models/message.js
  api/models/thread.js
  api/package.json
  api/queries/directMessageThread/snippet.js
  api/yarn.lock
  athena/package.json
  athena/queues/new-message-in-thread/format-data.js
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/bull/queues.js
  shared/bull/types.js
  shared/db/queries/community.js
  shared/db/queries/message.js
  shared/db/queries/notifications.js
  shared/db/queries/thread.js
  shared/db/queries/user.js
  shared/notification-to-text.js
  shared/test/__snapshots__/notification-to-text.test.js.snap
  shared/test/fixtures/MEDIA_MESSAGE_CREATED.json
  shared/test/notification-to-text.test.js
  vulcan/index.js
  vulcan/models/community.js
  vulcan/models/db.js
  vulcan/models/message.js
  vulcan/models/thread.js
  vulcan/models/user.js
  vulcan/package.json
  vulcan/queues/constants.js
  vulcan/queues/events/created.js
  vulcan/queues/events/deleted.js
  vulcan/queues/events/edited.js
  vulcan/queues/index.js
  vulcan/queues/types/community.js
  vulcan/queues/types/message.js
  vulcan/queues/types/thread/index.js
  vulcan/queues/types/thread/moved.js
  vulcan/queues/types/user.js
  vulcan/utils/get-queue-from-type.js
  vulcan/utils/index.js
  vulcan/utils/text-parsing.js
  vulcan/yarn.lock
Labels: Ready for Review

#4202 Fix mobile menu
  src/views/pages/components/nav.js
  src/views/pages/style.js
Labels: Ready for Review

#4203 2.4.62
  package.json
  src/views/pages/components/nav.js
  src/views/pages/style.js
Labels: Ready for Review

#4204 Fix desktop app upsells
  src/helpers/is-os.js
  src/views/dashboard/components/desktopAppUpsell/index.js
  src/views/thread/components/desktopAppUpsell/index.js
Labels: Ready for Review

#4205 2.4.63
  package.json
  src/helpers/is-os.js
  src/views/dashboard/components/desktopAppUpsell/index.js
  src/views/thread/components/desktopAppUpsell/index.js
Labels: Ready for Review

#4207 Fix collapsing header on explore view
  src/components/themedSection/index.js
  src/views/explore/components/communitySearchWrapper.js
Labels: Ready for Review

#4208 2.4.64
  package.json
  src/components/themedSection/index.js
  src/views/explore/components/communitySearchWrapper.js
Labels: Ready for Review

#4206 Fix composer bugs
  src/components/threadComposer/components/composer.js
  src/views/community/index.js
  src/views/thread/components/messages.js
Labels: Ready for Review

#4209 2.4.65
  package.json
  src/components/threadComposer/components/composer.js
  src/views/community/index.js
  src/views/thread/components/messages.js
Labels: Ready for Review

#4215 Fix filtering on member pagination in community settings
  shared/graphql/queries/community/getCommunityMembers.js
  src/views/communityMembers/components/communityMembers.js
Labels: Ready for Review

#4216 2.4.66
  api/package.json
  api/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/graphql/queries/community/getCommunityMembers.js
  src/views/communityMembers/components/communityMembers.js
Labels: Ready for Review

#4230 Remove zeit from cors list
  shared/middlewares/cors.js
Labels: Ready for Review

#4231 2.4.67
  api/package.json
  api/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  docs/hyperion (server side rendering)/intro.md
  hermes/package.json
  hermes/yarn.lock
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/middlewares/cors.js
Labels: Ready for Review

#4223 Allow user to edit their own email address
  api/mutations/user/editUser.js
  api/types/User.js
  cypress/integration/user/edit_user_spec.js
  shared/db/queries/user.js
  src/views/userSettings/components/editForm.js
Labels: Ready for Review

#4242 2.4.68
  analytics/package.json
  analytics/yarn.lock
  api/mutations/user/editUser.js
  api/package.json
  api/types/User.js
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  cypress/integration/user/edit_user_spec.js
  desktop/package.json
  desktop/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  mobile/package.json
  mobile/yarn.lock
  package.json
  shared/db/queries/user.js
  src/views/userSettings/components/editForm.js
  vulcan/package.json
  vulcan/yarn.lock
Labels: Ready for Review

#4243 Let workflows pass again
  .circleci/config.yml
Labels: Ready for Review

#4244 Update the user cookie when confirming an email
  api/queries/user/rootCurrentUser.js
  api/routes/api/email.js
Labels: Ready for Review

#4245 2.4.68 1
  .circleci/config.yml
  api/queries/user/rootCurrentUser.js
  api/routes/api/email.js
Labels: Ready for Review

#4253 Use passport logout function in req instead of manual session invalidation
  api/routes/auth/logout.js
Labels: Ready for Review

#4255 Use uuidv4 instead of shortid for crypto secure tokens
  analytics/package.json
  analytics/yarn.lock
  api/models/channelSettings.js
  api/models/communitySettings.js
  api/package.json
  api/utils/file-system.js
  api/utils/s3.js
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  package.json
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review

#4256 More secure isSpectrumUrl check for auth redirects
  api/utils/is-spectrum-url.js
Labels: Ready for Review

#4254 Dont let mods block community owners
  api/mutations/communityMember/blockCommunityMember.js
  api/utils/permissions.js
Labels: Ready for Review

#4252 Update yarnlocks and debug deps
  admin/yarn.lock
  analytics/package.json
  analytics/yarn.lock
  api/package.json
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  mercury/package.json
  mercury/yarn.lock
  mobile/yarn.lock
  package.json
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review

#4258 Whitelist subdomains for cors list
  shared/middlewares/cors.js
Labels: Ready for Review

#4257 Enforce ssl and hsts in prod
  api/package.json
  api/yarn.lock
  flow-typed/npm/express-enforces-ssl_vx.x.x.js
  flow-typed/npm/hsts_vx.x.x.js
  package.json
  shared/middlewares/security.js
  yarn.lock
Labels: Ready for Review

#4261 2.4.69
  admin/yarn.lock
  analytics/package.json
  analytics/yarn.lock
  api/authentication.js
  api/migrations/20181116173949-add-terms-last-accepted-field-to-users.js
  api/models/channelSettings.js
  api/models/communitySettings.js
  api/mutations/communityMember/blockCommunityMember.js
  api/package.json
  api/routes/auth/logout.js
  api/utils/file-system.js
  api/utils/is-spectrum-url.js
  api/utils/permissions.js
  api/utils/s3.js
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  flow-typed/npm/express-enforces-ssl_vx.x.x.js
  flow-typed/npm/hsts_vx.x.x.js
  hermes/package.json
  hermes/yarn.lock
  mercury/package.json
  mercury/yarn.lock
  mobile/yarn.lock
  package.json
  shared/db/queries/user.js
  shared/middlewares/cors.js
  shared/middlewares/security.js
  src/views/login/index.js
  src/views/login/style.js
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review

#4262 Fix DM badge rendering/updating
  api/yarn.lock
  shared/db/queries/usersNotifications.js
  shared/notification-to-text.js
  src/views/navbar/components/messagesTab.js
  src/views/navbar/components/profileDropdown.js
Labels: Ready for Review

#4264 Dont track specific auth-bound routes with postmark
  email-templates/mentionInMessage.html
  email-templates/mentionInThread.html
  email-templates/newDirectMessage.html
  email-templates/newRepliesInThreads.html
  email-templates/newThreadNotification.html
  email-templates/privateChannelRequestApproved.html
  email-templates/privateChannelRequestSent.html
  email-templates/privateCommunityRequestApproved.html
  email-templates/privateCommunityRequestSent.html
Labels: Ready for Review

#3762 Better thread slugs
  cypress/integration/thread_spec.js
  src/components/message/index.js
  src/components/messageGroup/index.js
  src/helpers/get-thread-link.js
  src/routes.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/messages.js
  src/views/thread/components/sidebar.js
  src/views/thread/components/threadCommunityBanner.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/container.js
  src/views/thread/redirect-old-route.js
Labels: Ready for Review, WIP: Building

#4267 Workaround desktop push issues for new message notifications
  shared/notification-to-text.js
  src/subscribe-to-desktop-push.js
Labels: Ready for Review

#4269 Fix copy on login modal
  src/components/modals/ChatInputLoginModal/index.js
  src/components/modals/ChatInputLoginModal/style.js
Labels: Ready for Review

#4270 Fix badge cursor misc
  src/components/badges/style.js
  src/components/rich-text-editor/style.js
  src/views/thread/components/messages.js
  src/views/thread/components/threadCommunityBanner.js
Labels: Ready for Review

#4271 2.4.71
  cypress/integration/thread_spec.js
  email-templates/mentionInMessage.html
  email-templates/mentionInThread.html
  email-templates/newDirectMessage.html
  email-templates/newRepliesInThreads.html
  email-templates/newThreadNotification.html
  email-templates/privateChannelRequestApproved.html
  email-templates/privateChannelRequestSent.html
  email-templates/privateCommunityRequestApproved.html
  email-templates/privateCommunityRequestSent.html
  package.json
  shared/notification-to-text.js
  src/components/badges/style.js
  src/components/message/index.js
  src/components/messageGroup/index.js
  src/components/modals/ChatInputLoginModal/index.js
  src/components/modals/ChatInputLoginModal/style.js
  src/components/rich-text-editor/style.js
  src/helpers/get-thread-link.js
  src/routes.js
  src/subscribe-to-desktop-push.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/messages.js
  src/views/thread/components/sidebar.js
  src/views/thread/components/threadCommunityBanner.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/container.js
  src/views/thread/redirect-old-route.js
Labels: Ready for Review

#4266 Reduce db connection counts across the board
  analytics/models/db.js
  athena/models/db.js
  chronos/models/db.js
  hermes/models/db.js
  mercury/models/db.js
  shared/db/db.js
Labels: WIP: Needs Testing

#4272 2.4.72
  analytics/models/db.js
  athena/models/db.js
  chronos/models/db.js
  hermes/models/db.js
  mercury/models/db.js
  package.json
  shared/db/db.js
Labels: Ready for Review

#4274 Fix static JS file browser caching
  hyperion/index.js
Labels: Ready for Review

#4275 Don't double-load raven-js
  api/package.json
  api/yarn.lock
  package.json
  public/index.html
  shared/clients/analytics/index.js
  shared/clients/analytics/raven.js
  src/actions/authentication.js
  src/components/emailInvitationForm/index.js
  src/components/error/ErrorBoundary.js
  src/components/hoverProfile/channelProfile.js
  src/components/hoverProfile/communityProfile.js
  src/components/message/index.js
  src/components/profile/community.js
  src/helpers/sentry-redux-middleware.js
  src/views/channel/components/memberGrid.js
  src/views/channelSettings/components/blockedUsers.js
  src/views/channelSettings/components/channelMembers.js
  src/views/channelSettings/components/pendingUsers.js
  src/views/community/components/channelList.js
  src/views/community/components/memberGrid.js
  src/views/community/components/moderatorList.js
  src/views/community/index.js
  src/views/communityAnalytics/components/topMembers.js
  src/views/communityMembers/components/communityMembers.js
  src/views/notifications/index.js
  src/views/thread/container.js
  src/views/user/index.js
  yarn.lock
Labels: Ready for Review

#4280 Fix online indicators
  src/components/avatar/communityAvatar.js
  src/components/avatar/style.js
  src/components/avatar/userAvatar.js
  src/components/granularUserProfile/index.js
  src/components/profile/style.js
  src/components/profile/user.js
  src/views/channel/components/memberGrid.js
  src/views/channelSettings/components/blockedUsers.js
  src/views/channelSettings/components/channelMembers.js
  src/views/channelSettings/components/pendingUsers.js
  src/views/community/components/memberGrid.js
  src/views/community/components/moderatorList.js
  src/views/communityAnalytics/components/topMembers.js
  src/views/communityMembers/components/communityMembers.js
  src/views/dashboard/components/inboxThread/index.js
  src/views/directMessages/components/avatars.js
  src/views/directMessages/components/header.js
  src/views/navbar/index.js
Labels: Ready for Review

#4288 Resync member counts
  api/migrations/20181121054300-resync-community-member-counts.js
Labels: Ready for Review

#4282 Add online and member counts to community and channel profiles
  api/loaders/channel.js
  api/loaders/index.js
  api/models/channel.js
  api/queries/channel/metaData.js
  api/types/Channel.js
  shared/graphql/fragments/channel/channelMetaData.js
  shared/graphql/fragments/community/communityMetaData.js
  src/components/granularUserProfile/index.js
  src/components/profile/community.js
  src/components/profile/style.js
  src/components/profile/user.js
  src/components/settingsViews/header.js
  src/views/channel/components/memberGrid.js
  src/views/channel/index.js
  src/views/channel/style.js
  src/views/community/components/moderatorList.js
  src/views/community/index.js
  src/views/notifications/components/actorsRow.js
Labels: Ready for Review

#4297 Fix posting threads from community view on mobile
  src/components/composer/index.js
  src/views/channel/index.js
  src/views/community/index.js
  src/views/compose/index.js
  src/views/compose/style.js
  src/views/titlebar/index.js
Labels: Ready for Review

#4289 Don't cache the app shell in the browser
  hyperion/index.js
Labels: Ready for Review

#4296 Show trending threads in thread view "More conversations" upsell
  shared/graphql/fragments/community/communityThreadConnection.js
  shared/graphql/queries/community/getCommunityThreadConnection.js
  src/views/community/index.js
  src/views/thread/components/sidebar.js
  src/views/thread/container.js
Labels: Ready for Review

#4292 Add "Trending" and "Latest" tabs to community views
  shared/graphql/fragments/community/communityThreadConnection.js
  shared/graphql/queries/community/getCommunityThreadConnection.js
  src/views/community/index.js
Labels: Ready for Review

#4295 Show total rep in desktop navbar
  src/views/navbar/index.js
  src/views/navbar/style.js
Labels: Ready for Review

#4293 Preload important JS bundles while browser idle
  hyperion/renderer/browser-shim.js
  src/helpers/p-queue.js
  src/routes.js
Labels: Ready for Review

#4309 Select first thread on dashboard on SSR
  src/views/dashboard/components/threadFeed.js
Labels: Ready for Review

#4305 Fix community segment control overflow on mobile
  src/views/community/index.js
Labels: Ready for Review

#4294 Add reputation information back to digest emails
  chronos/queues/digests/processReputation.js
  chronos/queues/digests/test/__snapshots__/reputation-string.test.js.snap
  chronos/queues/digests/test/reputation-string.test.js
  email-templates/weeklyDigest.html
Labels: Ready for Review

#4306 Dont match users by email on signin
  shared/db/queries/user.js
Labels: Ready for Review

#4304 Remove apollo engine
  api/apollo-server.js
  api/index.js
Labels: Ready for Review

#4325 Fix reputation counts
  api/models/usersCommunities.js
  src/components/reputation/index.js
  src/views/navbar/index.js
Labels: Ready for Review

#4326 Fix radix param
  src/views/navbar/index.js
Labels: Ready for Review

#4327 2.4.75
  api/models/usersCommunities.js
  hyperion/renderer/browser-shim.js
  package.json
  src/components/reputation/index.js
  src/helpers/p-queue.js
  src/routes.js
  src/views/dashboard/components/threadFeed.js
  src/views/navbar/index.js
Labels: Ready for Review

#4333 2.4.77
  hyperion/index.js
  package.json
Labels: Ready for Review

#4334 Bug fixes
  athena/queues/moderationEvents/message.js
  package.json
  src/components/avatar/communityAvatar.js
  src/components/avatar/image.js
  src/components/avatar/userAvatar.js
  src/components/hoverProfile/communityContainer.js
  src/components/hoverProfile/communityProfile.js
  src/components/hoverProfile/userContainer.js
  src/components/listItems/index.js
  src/components/listItems/style.js
  src/components/profile/community.js
  src/reducers/newUserOnboarding.js
  src/views/community/index.js
  src/views/dashboard/components/upsellExploreCommunities.js
  src/views/directMessages/components/avatars.js
  src/views/navbar/index.js
  src/views/navbar/style.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/newUserOnboarding/components/setUsername/index.js
  src/views/newUserOnboarding/index.js
  src/views/pages/view.js
  yarn.lock
Labels: Ready for Review

#4336 Fix thread share meta images
  api/queries/thread/index.js
  api/queries/thread/metaImage.js
  api/types/Thread.js
  api/utils/generate-thread-meta-image-from-text.js
  shared/graphql/fragments/thread/threadInfo.js
  src/views/thread/container.js
Labels: Ready for Review

#4341 Fix DMThread.snippet database performance
  api/loaders/directMessageThread.js
  api/models/message.js
  api/queries/directMessageThread/snippet.js
Labels: Ready for Review

#4339 Don't double-connect to db from workers
  analytics/models/channel.js
  analytics/models/community.js
  analytics/models/db.js
  analytics/models/message.js
  analytics/models/notification.js
  analytics/models/reaction.js
  analytics/models/thread.js
  analytics/models/usersChannels.js
  analytics/models/usersCommunities.js
  analytics/models/usersThreads.js
  api/models/channel.js
  api/models/usersChannels.js
  athena/models/channel.js
  athena/models/channelSettings.js
  athena/models/community.js
  athena/models/communitySettings.js
  athena/models/db.js
  athena/models/directMessageThread.js
  athena/models/message.js
  athena/models/notification.js
  athena/models/thread.js
  athena/models/usersChannels.js
  athena/models/usersCommunities.js
  athena/models/usersDirectMessageThreads.js
  athena/models/usersSettings.js
  athena/models/usersThreads.js
  athena/models/web-push-subscription.js
  chronos/models/channel.js
  chronos/models/community.js
  chronos/models/coreMetrics.js
  chronos/models/db.js
  chronos/models/message.js
  chronos/models/reputationEvent.js
  chronos/models/thread.js
  chronos/models/usersChannels.js
  chronos/models/usersCommunities.js
  chronos/models/usersSettings.js
  hermes/models/db.js
  hermes/models/usersSettings.js
  mercury/models/db.js
  mercury/models/message.js
  mercury/models/reaction.js
  mercury/models/reputationEvent.js
  mercury/models/thread.js
  mercury/models/usersCommunities.js
Labels: Ready for Review

#4343 fixes issue where scrollbar appears under segmented controls on desktop obscuring the tab indicator
  src/components/segmentedControl/index.js
  src/views/community/index.js
Labels: Ready for Review

#4335 Warn team members before leaving owned-community
  cypress/integration/community/view/profile_spec.js
  src/components/modals/DeleteDoubleCheckModal/index.js
  src/components/toggleCommunityMembership/index.js
  src/views/community/index.js
  src/views/community/style.js
Labels: Ready for Review

#4290 Refetch critical data when a network connection is lost and restored
  api/package.json
  api/yarn.lock
  package.json
  src/components/threadFeed/index.js
  src/hooks/useConnectionRestored.js
  src/reducers/connectionStatus.js
  src/views/dashboard/components/threadFeed.js
  src/views/directMessages/containers/existingThread.js
  src/views/directMessages/containers/index.js
  src/views/navbar/components/messagesTab.js
  src/views/navbar/components/notificationsTab.js
  src/views/navbar/index.js
  src/views/notifications/index.js
  src/views/status/index.js
  src/views/thread/components/messages.js
Labels: Ready for Review, WIP: Needs Testing

#4344 Fix settings buttons on community/channel views
  src/views/channel/index.js
  src/views/community/index.js
  src/views/community/style.js
  yarn.lock
Labels: Ready for Review

#4346 Add analytics as server option in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Ready for Review

#4349 Add communities "memberCount" index, rewrite chronos queries
  api/migrations/20181127090014-communities-member-count-index.js
  chronos/models/community.js
Labels: Ready for Review

#4350 Use message threadIdAndTimestamp index for getNewMessageCount query
  chronos/models/message.js
Labels: Ready for Review

#4352 Use threadIdAndTimestamp index in mercury db query
  mercury/models/thread.js
Labels: WIP: Needs Testing

#4354 Fix channel join leave buttons
  cypress/integration/channel/view/membership_spec.js
  src/views/channel/index.js
  src/views/community/index.js
  src/views/communityLogin/index.js
Labels: Ready for Review

#4358 Fix chronos jobs
  .eslintrc.js
  chronos/index.js
  chronos/jobs/index.js
  chronos/jobs/utils.js
  chronos/models/channel.js
  chronos/models/community.js
  chronos/models/coreMetrics.js
  chronos/models/message.js
  chronos/models/reputationEvent.js
  chronos/models/thread.js
  chronos/models/usersChannels.js
  chronos/models/usersCommunities.js
  chronos/models/usersSettings.js
  chronos/models/utils.js
  chronos/package.json
  chronos/queues/constants.js
  chronos/queues/coreMetrics/activeCommunityAdminReport.js
  chronos/queues/coreMetrics/index.js
  chronos/queues/digests/dailyDigest.js
  chronos/queues/digests/getReputationString.js
  chronos/queues/digests/getUpsellCommunities.js
  chronos/queues/digests/index.js
  chronos/queues/digests/processDigest.js
  chronos/queues/digests/processDigestEmail.js
  chronos/queues/digests/processIndividualDigest.js
  chronos/queues/digests/processThreads.js
  chronos/queues/digests/processUsers.js
  chronos/queues/digests/test/__snapshots__/message-count-string.test.js.snap
  chronos/queues/digests/test/message-count-string.test.js
  chronos/queues/digests/test/reputation-string.test.js
  chronos/queues/digests/types.js
  chronos/queues/digests/weeklyDigest.js
  chronos/types.js
  chronos/yarn.lock
  desktop/package.json
  email-templates/adminActiveCommunityReport.html
  email-templates/weeklyDigest.html
  hermes/queues/send-admin-active-community-report-email.js
  hermes/queues/send-digest-email.js
  mobile/package.json
  shared/bull/queues.js
  shared/bull/types.js
  shared/db/queries/channel.js
  shared/db/queries/community.js
  shared/db/queries/message.js
  shared/db/queries/thread.js
  shared/db/queries/user.js
  shared/types.js
Labels: Ready for Review

#4369 Dont generate data in deleted communities
  api/migrations/seed/index.js
Labels: Ready for Review

#4368 Dont use page visibility to determine a refetch
  src/components/threadFeed/index.js
  src/hooks/useConnectionRestored.js
  src/reducers/connectionStatus.js
  src/views/dashboard/components/threadFeed.js
  src/views/directMessages/containers/existingThread.js
  src/views/directMessages/containers/index.js
  src/views/navbar/components/messagesTab.js
  src/views/navbar/components/notificationsTab.js
  src/views/navbar/index.js
  src/views/notifications/index.js
  src/views/thread/components/messages.js
Labels: Ready for Review

#4374 New cache headers
  hyperion/index.js
  hyperion/renderer/index.js
Labels: Ready for Review

#4380 Gh banner
  src/components/icons/index.js
  src/routes.js
  src/views/announcementBanner/index.js
  src/views/announcementBanner/style.js
Labels: Ready for Review

#4381 Fix mobile gh banner
  src/views/announcementBanner/style.js
Labels: Ready for Review
