Repository withspectrum/spectrum, pull requests merged in 2019-02, with the labels that each got.

#4616 Preserve redirectPath prop for join token routes
  src/views/communityLogin/index.js
Labels: Ready for Review

#4615 Monitor server instance memory to DataDog
  shared/statsd.js
Labels: Ready for Review

#4619 remove active overlay / focus state from image in composer
  src/components/rich-text-editor/Image.js
Labels: Ready for Review

#4623 Fix editing "text" messages
  src/components/message/editingBody.js
Labels: Ready for Review

#4408 Debounce communities search query on front page instead of throttling
  src/views/directMessages/components/style.js
  src/views/directMessages/containers/newThread.js
  src/views/explore/components/search.js
  src/views/newUserOnboarding/components/communitySearch/index.js
Labels: Ready for Review

#4625 Break words while editing messages on mobile
  src/components/message/style.js
Labels: Ready for Review

#4564 Move thread editor to plaintext
  api/mutations/files/index.js
  api/mutations/files/uploadImage.js
  api/mutations/thread/publishThread.js
  api/schema.js
  api/types/general.js
  cypress/integration/channel/view/composer_spec.js
  cypress/integration/community/view/profile_spec.js
  cypress/integration/thread/action_bar_spec.js
  cypress/integration/thread_spec.js
  flow-typed/npm/react-dropzone_vx.x.x.js
  package.json
  shared/clients/draft-js/links-decorator/core.js
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/index.js
  shared/draft-utils/process-thread-content.js
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
  shared/graphql/mutations/uploadImage.js
  src/components/chatInput/index.js
  src/components/chatInput/style.js
  src/components/composer/index.js
  src/components/composer/style.js
  src/components/globals/index.js
  src/components/markdownHint/index.js
  src/components/markdownHint/style.js
  src/components/mentionsInput/index.js
  src/components/mentionsInput/style.js
  src/components/rich-text-editor/Image.js
  src/components/rich-text-editor/container.js
  src/components/rich-text-editor/style.js
  src/components/segmentedControl/index.js
  src/components/threadComposer/components/composer.js
  src/components/threadComposer/index.js
  src/components/threadComposer/style.js
  src/views/channel/index.js
  src/views/community/index.js
  src/views/dashboard/components/emptyThreadFeed.js
  src/views/dashboard/components/threadSelectorHeader.js
  src/views/dashboard/index.js
  src/views/thread/index.js
  src/views/thread/style.js
  yarn.lock
Labels: Ready for Review

#4627 v2.7.0
  analytics/package.json
  analytics/yarn.lock
  api/mutations/files/index.js
  api/mutations/files/uploadImage.js
  api/mutations/thread/publishThread.js
  api/package.json
  api/schema.js
  api/types/general.js
  api/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  cypress/integration/channel/view/composer_spec.js
  cypress/integration/community/view/profile_spec.js
  cypress/integration/thread/action_bar_spec.js
  cypress/integration/thread_spec.js
  flow-typed/npm/react-dropzone_vx.x.x.js
  package.json
  shared/clients/draft-js/links-decorator/core.js
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/index.js
  shared/draft-utils/process-thread-content.js
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
  shared/graphql/mutations/uploadImage.js
  shared/statsd.js
  src/components/chatInput/index.js
  src/components/chatInput/style.js
  src/components/composer/index.js
  src/components/composer/style.js
  src/components/globals/index.js
  src/components/markdownHint/index.js
  src/components/markdownHint/style.js
  src/components/mentionsInput/index.js
  src/components/mentionsInput/style.js
  src/components/message/editingBody.js
  src/components/message/style.js
  src/components/rich-text-editor/Image.js
  src/components/rich-text-editor/container.js
  src/components/rich-text-editor/style.js
  src/components/segmentedControl/index.js
  src/components/threadComposer/components/composer.js
  src/components/threadComposer/index.js
  src/components/threadComposer/style.js
  src/views/channel/index.js
  src/views/community/index.js
  src/views/communityLogin/index.js
  src/views/dashboard/components/emptyThreadFeed.js
  src/views/dashboard/components/threadSelectorHeader.js
  src/views/dashboard/index.js
  src/views/directMessages/components/style.js
  src/views/directMessages/containers/newThread.js
  src/views/explore/components/search.js
  src/views/newUserOnboarding/components/communitySearch/index.js
  src/views/thread/index.js
  src/views/thread/style.js
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review

#3800 fixed mention regex to respect dots in usernames
  shared/clients/draft-js/mentions-decorator/test/mentions-decorator.test.js
  shared/regexps.js
Labels: Ready for Review

#4621 Import emails to invite to community
  cypress/integration/community/settings/private_invite_link_spec.js
  package.json
  src/components/emailInvitationForm/index.js
  src/components/emailInvitationForm/style.js
  src/components/icons/index.js
  src/components/mediaInput/index.js
  upload.svg
  yarn.lock
Labels: Ready for Review

#4638 fix composer z-index bug safari
  src/components/composer/style.js
Labels: Ready for Review

#4640 Fix edit message mentions
  src/components/message/editingBody.js
Labels: Ready for Review

#4641 Rework automatic embeds to operate on raw content state
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/process-thread-content.js
Labels: Ready for Review

#4642 Clean up job queue metrics tracking
  shared/bull/create-queue.js
Labels: Ready for Review

#4648 Do not call `markSingleNotificationSeen` for all client-side notifications
  src/views/navbar/components/notificationsTab.js
Labels: Ready for Review

#4647 Add request-level rate limiting
  api/index.js
  api/package.json
  api/yarn.lock
  flow-typed/npm/ratelimiter_vx.x.x.js
  hyperion/index.js
  package.json
  shared/middlewares/rate-limiter.js
  yarn.lock
Labels: Ready for Review

#4656 fix 「 post your first thread 」Button in emptyThreadFeed on mobile .
  src/views/dashboard/components/emptyThreadFeed.js
Labels: Ready for Review

#4659 [HOTFIX] Fix editing messages
  api/mutations/message/editMessage.js
Labels: Ready for Review

#4662 Track db connection count to statsd
  shared/bull/create-queue.js
  shared/db/db.js
Labels: Ready for Review

#4680 Add support for simplecast urls to convert to embeds
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
Labels: Ready for Review

#4671 Deployment script :sparkles:
  package.json
  scripts/deploy.js
  scripts/introspection-query.js
  scripts/utils/error.js
  scripts/utils/parse-argv.js
Labels: Ready for Review

#4695 Fix missing close method in community create upsell
  src/components/upsell/index.js
Labels: Ready for Review

#4689 Fix hyperion alpha deploy with script
  scripts/deploy.js
Labels: Ready for Review

#4696 Ensure users have emails before trying to send community approval email
  athena/queues/private-community-request-approved.js
Labels: Ready for Review

#4682 Fix presigned images in thread body
  shared/imgix/signThread.js
Labels: Ready for Review

#4694 fix: popper menu can't be hide on iOS safari & remove gray backgroud when click
  src/components/outsideClickHandler/index.js
  src/reset.css.js
Labels: Ready for Review

#4698 Higher res cover photos
  shared/imgix/signCommunity.js
  shared/imgix/signUser.js
  src/components/loading/style.js
  src/views/channel/style.js
  src/views/community/style.js
  src/views/user/style.js
Labels: Ready for Review

#4699 Fix mention unsub link
  api/routes/api/email.js
  athena/queues/mention-notification.js
Labels: Ready for Review

#4691 Improve db connection count tracking
  shared/db/db.js
Labels: Ready for Review

#4703 2.7.3
  api/routes/api/email.js
  athena/queues/mention-notification.js
  athena/queues/private-community-request-approved.js
  package.json
  scripts/deploy.js
  shared/db/db.js
  shared/imgix/signCommunity.js
  shared/imgix/signThread.js
  shared/imgix/signUser.js
  src/components/loading/style.js
  src/components/outsideClickHandler/index.js
  src/components/upsell/index.js
  src/reset.css.js
  src/views/channel/style.js
  src/views/community/style.js
  src/views/user/style.js
Labels: Ready for Review

#4706 Hot fix signthread bug
  shared/imgix/signThread.js
Labels: Ready for Review

#4707 Dont use firstnamelastname on empty user profile thread feed
  src/views/user/index.js
Labels: Ready for Review

#4679 GitHub connection error
  api/authentication.js
  api/routes/api/email.js
  api/routes/auth/create-signin-routes.js
  cypress/integration/toasts_spec.js
  src/actions/toasts.js
  src/components/formElements/style.js
  src/components/toasts/index.js
  src/components/toasts/style.js
  src/routes.js
  src/views/queryParamToastDispatcher/index.js
  src/views/userSettings/index.js
Labels: Ready for Review

#4709 Do not log statsd (or any other middleware) from workers
  package.json
Labels: Ready for Review

#4687 Run now rm --safe after deploys
  analytics/package.json
  athena/package.json
  scripts/deploy.js
Labels: Ready for Review

#4708 feat: Add button to hide thread upsell
  cypress/integration/thread/chat_input_spec.js
  cypress/integration/thread_spec.js
  src/components/buttons/index.js
  src/components/buttons/style.js
  src/components/upsell/joinChannel.js
  src/components/upsell/style.js
  src/views/thread/components/threadCommunityBanner.js
Labels: Ready for Review

#4716 Better spam protection on thread publish
  api/mutations/thread/publishThread.js
Labels: Ready for Review

#4719 Add logout button to mobile user settings
  src/views/userSettings/components/logout.js
  src/views/userSettings/components/overview.js
  src/views/userSettings/style.js
Labels: Ready for Review

#4715 Fix unsubscribe redirects for individual entity mutes
  api/routes/api/email.js
Labels: Ready for Review

#4717 Fix loading state on DMs
  src/views/directMessages/components/threadsList.js
Labels: Ready for Review

#4718 Persist last selected inbox community between sessions
  src/actions/dashboardFeed.js
  src/views/dashboard/components/communityList.js
Labels: Ready for Review

#4692 Re-enable request-level rate limiting
  api/index.js
  api/package.json
  api/yarn.lock
  flow-typed/npm/ratelimiter_vx.x.x.js
  hyperion/index.js
  package.json
  shared/middlewares/rate-limiter.js
  yarn.lock
Labels: WIP: Building

#4629 Thread renderer
  api/mutations/thread/editThread.js
  api/utils/create-graphql-error-formatter.js
  cypress/integration/thread/action_bar_spec.js
  flow-typed/npm/prism-react-renderer_vx.x.x.js
  package.json
  shared/clients/draft-js/message/types.js
  shared/clients/draft-js/thread/renderer.js
  src/components/composer/index.js
  src/components/composer/inputs.js
  src/components/composer/style.js
  src/components/draft-js-plugins-editor/index.js
  src/components/globals/index.js
  src/components/message/editingBody.js
  src/components/message/view.js
  src/components/rich-text-editor/Embed.js
  src/components/rich-text-editor/Image.js
  src/components/rich-text-editor/LanguageSelect.js
  src/components/rich-text-editor/container.js
  src/components/rich-text-editor/index.js
  src/components/rich-text-editor/toolbar.js
  src/components/segmentedControl/index.js
  src/components/threadComposer/style.js
  src/components/threadRenderer/index.js
  src/reset.css.js
  src/views/thread/components/threadDetail.js
  src/views/thread/style.js
  yarn.lock
Labels: Ready for Review

#4734 Fix renderer imports
  .flowconfig
  shared/clients/draft-js/links-decorator/index.js
  shared/clients/draft-js/mentions-decorator/index.js
  shared/clients/draft-js/mentions-decorator/test/mentions-decorator.test.js
  shared/clients/draft-js/message/renderer.js
  shared/clients/draft-js/message/test/renderer.test.js
  src/components/message/view.js
Labels: Ready for Review

#4735 2.7.4
  .flowconfig
  shared/clients/draft-js/links-decorator/index.js
  shared/clients/draft-js/mentions-decorator/index.js
  shared/clients/draft-js/mentions-decorator/test/mentions-decorator.test.js
  shared/clients/draft-js/message/renderer.js
  shared/clients/draft-js/message/test/renderer.test.js
  src/components/message/view.js
Labels: Ready for Review

#4738 Fix force scroll
  src/components/composer/index.js
  src/components/composer/inputs.js
  src/components/composer/style.js
  src/views/thread/components/threadDetail.js
  src/views/thread/container.js
  src/views/thread/style.js
Labels: Ready for Review

#4739 Fix join token redirect issue for private communities
  src/views/communityLogin/index.js
Labels: Ready for Review

#4740 2.7.5
  package.json
  src/components/composer/index.js
  src/components/composer/inputs.js
  src/components/composer/style.js
  src/views/communityLogin/index.js
  src/views/thread/components/threadDetail.js
  src/views/thread/container.js
  src/views/thread/style.js
Labels: Ready for Review

#4752 Fix static tests on alpha
  src/routes.js
Labels: Ready for Review

#4684 Post new threads to watercooler as links
  api/migrations/20190226085909-bot-user-sam.js
  api/mutations/message/addMessage.js
  api/mutations/thread/publishThread.js
Labels: Ready for Review

#4757 Disable API rate limiting during e2e tests
  api/index.js
Labels: Ready for Review

#4683 Render embeds for linked threads in messages
  shared/theme/index.js
  src/components/chatInput/style.js
  src/components/globals/index.js
  src/components/message/ThreadAttachment/Attachment.js
  src/components/message/ThreadAttachment/index.js
  src/components/message/ThreadAttachment/style.js
  src/components/message/style.js
  src/components/message/view.js
Labels: Ready for Review

#4737 Add shift key listener when deleting messages
  src/components/message/index.js
  src/components/modals/DeleteDoubleCheckModal/index.js
Labels: Ready for Review

#4742 Render slider at full thread URLs on the client-side
  src/actions/dashboardFeed.js
  src/actions/threadSlider.js
  src/components/composer/index.js
  src/components/profile/thread.js
  src/helpers/notifications.js
  src/index.js
  src/reducers/threadSlider.js
  src/routes.js
  src/views/communityAnalytics/components/threadListItem.js
  src/views/dashboard/components/inboxThread/header/index.js
  src/views/dashboard/components/inboxThread/index.js
  src/views/dashboard/components/threadFeed.js
  src/views/navbar/components/notificationsTab.js
  src/views/notifications/components/mentionMessageNotification.js
  src/views/notifications/components/mentionThreadNotification.js
  src/views/notifications/components/newMessageNotification.js
  src/views/notifications/components/newReactionNotification.js
  src/views/notifications/components/newThreadReactionNotification.js
  src/views/notifications/utils.js
  src/views/thread/components/sidebar.js
  src/views/threadSlider/index.js
Labels: Ready for Review, WIP: Building

#4755 Use parallelism
  .circleci/config.yml
Labels: Ready for Review
