Repository withspectrum/spectrum, pull requests merged in 2019-03, with the labels that each got.

#4766 Fix thread attachment link
  src/components/message/ThreadAttachment/Attachment.js
Labels: Ready for Review

#4767 Fix repeating heading in digest emails
  built-email-templates/weeklyDigest.html
  email-template-scripts/sendgrid-sync.js
  email-templates/weeklyDigest.html
Labels: Ready for Review

#4771 Fix unreliable DM thread subscriptions
  api/models/directMessageThread.js
  api/models/usersDirectMessageThreads.js
Labels: Ready for Review

#4773 Run e2e tests in parallel
  .circleci/config.yml
Labels: WIP: Building

#4774 Remove usage of browser history on server
  src/actions/dashboardFeed.js
  src/views/dashboard/components/inboxThread/index.js
Labels: Ready for Review

#4779 Fix join link redirectpath default state
  src/views/communityLogin/index.js
Labels: Ready for Review

#4780 Fix mobile dm compose
  cypress/integration/messages_spec.js
  src/routes.js
  src/views/directMessages/containers/index.js
  src/views/directMessages/containers/newThread.js
  src/views/titlebar/index.js
  src/views/user/index.js
Labels: Ready for Review

#4782 Dont post links about new threads in private channels to watercooler
  api/mutations/thread/publishThread.js
Labels: Ready for Review

#4784 Polish
  src/components/composer/style.js
  src/views/navbar/style.js
  src/views/thread/style.js
Labels: Ready for Review

#4785 2.8.1
  api/mutations/thread/publishThread.js
  package.json
  src/components/composer/style.js
  src/views/dashboard/components/inboxThread/index.js
  src/views/navbar/style.js
  src/views/thread/style.js
Labels: Ready for Review

#4759 Message syntax highlighting
  api/mutations/directMessageThread/createDirectMessageThread.js
  api/mutations/message/addMessage.js
  api/mutations/message/editMessage.js
  api/queries/directMessageThread/snippet.js
  athena/queues/direct-message-notification.js
  athena/queues/moderationEvents/message.js
  athena/queues/new-message-in-thread/index.js
  shared/clients/draft-js/message/renderer.js
  shared/clients/draft-js/thread/renderer.js
  shared/clients/draft-js/utils/getStringElements.js
  shared/clients/draft-js/utils/hasStringElements.js
  shared/draft-utils/process-message-content.js
  shared/graphql/mutations/message/sendMessage.js
  shared/notification-to-text.js
  shared/types.js
  src/components/message/view.js
Labels: Ready for Review

#4800 Use cypress retries
  cypress/support/index.js
  package.json
  yarn.lock
Labels: Ready for Review

#4797 Add support for lists to messages
  shared/clients/draft-js/message/renderer.js
  shared/clients/draft-js/message/test/__snapshots__/renderer.test.js.snap
  src/components/message/style.js
  src/reset.css.js
  src/views/thread/style.js
Labels: Ready for Review

#4806 Remove sam sentence logic
  api/mutations/thread/publishThread.js
Labels: Ready for Review

#4796 Fix thread links across the board
  src/components/composer/index.js
  src/components/message/index.js
  src/helpers/get-thread-link.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/messages.js
  src/views/thread/components/sidebar.js
  src/views/thread/components/threadCommunityBanner.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/container.js
Labels: Ready for Review

#4793 Add project board to readme
  README.md
Labels: Ready for Review

#4807 Fix title wrapping
  shared/truncate.js
  src/views/thread/style.js
Labels: Ready for Review

#4808 Hide the placeholder composer on profile views on mobile
  src/components/threadComposer/style.js
Labels: Ready for Review

#4809 2.8.2
  README.md
  api/mutations/directMessageThread/createDirectMessageThread.js
  api/mutations/message/addMessage.js
  api/mutations/message/editMessage.js
  api/mutations/thread/publishThread.js
  api/package.json
  api/queries/directMessageThread/snippet.js
  api/yarn.lock
  athena/queues/direct-message-notification.js
  athena/queues/moderationEvents/message.js
  athena/queues/new-message-in-thread/index.js
  cypress/support/index.js
  package.json
  shared/clients/draft-js/message/renderer.js
  shared/clients/draft-js/message/test/__snapshots__/renderer.test.js.snap
  shared/clients/draft-js/thread/renderer.js
  shared/clients/draft-js/utils/getStringElements.js
  shared/clients/draft-js/utils/hasStringElements.js
  shared/draft-utils/process-message-content.js
  shared/graphql/mutations/message/sendMessage.js
  shared/notification-to-text.js
  shared/truncate.js
  shared/types.js
  src/components/composer/index.js
  src/components/message/index.js
  src/components/message/style.js
  src/components/message/view.js
  src/components/threadComposer/style.js
  src/helpers/get-thread-link.js
  src/reset.css.js
  src/routes.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/messages.js
  src/views/thread/components/sidebar.js
  src/views/thread/components/threadCommunityBanner.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/watercoolerActionBar.js
  src/views/thread/container.js
  src/views/thread/style.js
  yarn.lock
Labels: Ready for Review

#4810 Temporarily disable spectrum bot
  api/mutations/thread/publishThread.js
Labels: Ready for Review

#4814 :bug: Show error message when uploading of image failed in composer
  src/components/composer/index.js
Labels: Ready for Review

#4817 Fix duplicate links and embeds
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
Labels: Ready for Review

#4794 Fix nested modals
  src/routes.js
  src/views/threadSlider/index.js
Labels: Ready for Review

#4826 Combine thread and message renderer
  shared/clients/draft-js/message/renderer.js
  shared/clients/draft-js/renderer/index.js
  shared/clients/draft-js/thread/renderer.js
Labels: Ready for Review

#4828 Fix editing communities
  api/models/community.js
  src/views/communitySettings/components/editForm.js
Labels: Ready for Review

#4831 Message render styling
  src/components/chatInput/index.js
  src/components/message/style.js
  src/reset.css.js
Labels: Ready for Review

#4823 Add watercooler to community settings
  api/migrations/20190306125252-threads-watercooler-index.js
  api/models/community.js
  api/models/thread.js
  api/mutations/community/disableCommunityWatercooler.js
  api/mutations/community/enableCommunityWatercooler.js
  api/mutations/community/index.js
  api/types/Community.js
  cypress/integration/community_settings_overview_spec.js
  shared/analytics/event-types/community.js
  shared/graphql/fragments/community/communityInfo.js
  shared/graphql/mutations/community/disableCommunityWatercooler.js
  shared/graphql/mutations/community/enableCommunityWatercooler.js
  src/views/communitySettings/components/editForm.js
  src/views/communitySettings/components/overview.js
  src/views/communitySettings/components/watercooler.js
Labels: Ready for Review

#4833 2.8.3
  api/migrations/20190306125252-threads-watercooler-index.js
  api/models/community.js
  api/models/thread.js
  api/mutations/community/disableCommunityWatercooler.js
  api/mutations/community/enableCommunityWatercooler.js
  api/mutations/community/index.js
  api/mutations/thread/publishThread.js
  api/types/Community.js
  cypress/integration/community_settings_overview_spec.js
  package.json
  shared/analytics/event-types/community.js
  shared/clients/draft-js/message/renderer.js
  shared/clients/draft-js/renderer/index.js
  shared/clients/draft-js/thread/renderer.js
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
  shared/graphql/fragments/community/communityInfo.js
  shared/graphql/mutations/community/disableCommunityWatercooler.js
  shared/graphql/mutations/community/enableCommunityWatercooler.js
  src/components/chatInput/index.js
  src/components/composer/index.js
  src/components/message/style.js
  src/reset.css.js
  src/routes.js
  src/views/communitySettings/components/editForm.js
  src/views/communitySettings/components/overview.js
  src/views/communitySettings/components/watercooler.js
  src/views/threadSlider/index.js
Labels: Ready for Review

#4820 Do not run contributors e2e tests 9 times
  .circleci/config.yml
Labels: Ready for Review, WIP: Needs Testing

#4835 Post new threads to watercooler v2
  api/mutations/message/addMessage.js
  api/mutations/thread/publishThread.js
  api/types/Message.js
  shared/graphql/fragments/message/messageInfo.js
  src/components/badges/index.js
  src/components/message/authorByline.js
  src/components/message/index.js
Labels: Ready for Review

#4836 Disable email notifications for bot messages
  athena/queues/new-message-in-thread/index.js
Labels: Ready for Review

#4834 Fix upload images during thread editing
  src/views/thread/components/actionBar.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#4837 Run contributor PR e2e tests on one machine
  .circleci/config.yml
Labels: WIP: Needs Testing

#4825 Fix /thread/:id modal routes
  src/views/thread/redirect-old-route.js
Labels: Ready for Review

#4772 Move markdown conversion to microservice
  api/mutations/directMessageThread/createDirectMessageThread.js
  api/mutations/message/addMessage.js
  api/mutations/message/editMessage.js
  flow-typed/npm/snarkdown_vx.x.x.js
  package.json
  shared/clients/draft-js/utils/isShort.js
  shared/clients/draft-js/utils/plaintext.js
  shared/draft-utils/message-types.js
  shared/draft-utils/process-message-content.js
  shared/draft-utils/process-thread-content.js
  shared/generate-meta-info.js
  shared/graphql/mutations/message/sendMessage.js
  shared/notification-to-text.js
  shared/types.js
  src/components/composer/inputs.js
  src/components/message/editingBody.js
  src/components/message/view.js
  src/views/thread/components/threadDetail.js
  yarn.lock
Labels: Ready for Review

#4849 Console an error in case a user queries threads from a deleted community or channel
  api/queries/thread/channel.js
  api/queries/thread/community.js
Labels: Ready for Review

#4848 Fix messages getting empty lines appended
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/test/__snapshots__/add-embeds-to-draft-js.test.js.snap
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#4847 2.8.4
  .circleci/config.yml
  api/mutations/directMessageThread/createDirectMessageThread.js
  api/mutations/message/addMessage.js
  api/mutations/message/editMessage.js
  api/mutations/thread/publishThread.js
  api/package.json
  api/queries/thread/channel.js
  api/queries/thread/community.js
  api/types/Message.js
  api/yarn.lock
  athena/queues/new-message-in-thread/index.js
  flow-typed/npm/snarkdown_vx.x.x.js
  package.json
  shared/clients/draft-js/utils/isShort.js
  shared/clients/draft-js/utils/plaintext.js
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/message-types.js
  shared/draft-utils/process-message-content.js
  shared/draft-utils/process-thread-content.js
  shared/draft-utils/test/__snapshots__/add-embeds-to-draft-js.test.js.snap
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
  shared/generate-meta-info.js
  shared/graphql/fragments/message/messageInfo.js
  shared/graphql/mutations/message/sendMessage.js
  shared/notification-to-text.js
  shared/types.js
  src/components/badges/index.js
  src/components/composer/inputs.js
  src/components/message/authorByline.js
  src/components/message/editingBody.js
  src/components/message/index.js
  src/components/message/view.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/threadDetail.js
  src/views/thread/redirect-old-route.js
  vulcan/package.json
  vulcan/yarn.lock
  yarn.lock
Labels: Ready for Review

#4850 Fix optimistic updates and react warning
  shared/graphql/mutations/message/sendMessage.js
  src/components/message/view.js
Labels: Ready for Review

#4851 Fix athena deploys
  athena/package.json
  athena/yarn.lock
Labels: Ready for Review

#4827 Move thread embeds to automatic embed system
  api/migrations/seed/default/messages.js
  shared/clients/draft-js/renderer/index.js
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/test/__snapshots__/add-embeds-to-draft-js.test.js.snap
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
  src/components/message/ThreadAttachment/Attachment.js
  src/components/message/ThreadAttachment/style.js
  src/components/message/view.js
  src/reset.css.js
  src/views/thread/components/messages.js
Labels: Ready for Review, WIP: Building

#4866 Fix media messages
  shared/graphql/mutations/message/sendMessage.js
Labels: Ready for Review

#4867 v2.8.5
  analytics/package.json
  analytics/yarn.lock
  api/migrations/seed/default/messages.js
  api/package.json
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  package.json
  shared/clients/draft-js/renderer/index.js
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/test/__snapshots__/add-embeds-to-draft-js.test.js.snap
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
  shared/graphql/mutations/message/sendMessage.js
  src/components/message/ThreadAttachment/Attachment.js
  src/components/message/ThreadAttachment/style.js
  src/components/message/view.js
  src/reset.css.js
  src/views/thread/components/messages.js
Labels: Ready for Review

#4869 Render "App" badge for bot posts
  src/components/badges/index.js
Labels: Ready for Review

#4884 Fix external images breaking while editing
  shared/imgix/signThread.js
Labels: Ready for Review

#4886 Add white-space: pre-wrap to Paragraph component to preserve new line
  src/components/message/style.js
Labels: Ready for Review

#4887 Add default alt text to img
  shared/clients/draft-js/renderer/index.js
Labels: Ready for Review

#4921 Fix editing messages with automatic embeds
  shared/clients/draft-js/links-decorator/core.js
  shared/draft-utils/add-embeds-to-draft-js.js
  shared/draft-utils/test/__snapshots__/add-embeds-to-draft-js.test.js.snap
  shared/draft-utils/test/add-embeds-to-draft-js.test.js
Labels: Ready for Review

#4922 First pass of v3 polish
  src/components/composer/style.js
  src/components/entities/listItems/channel.js
  src/components/entities/profileCards/components/communityActions.js
  src/components/layout/index.js
  src/components/message/style.js
  src/reset.css.js
  src/views/community/components/communityFeeds.js
  src/views/directMessages/components/style.js
  src/views/directMessages/style.js
  src/views/thread/style.js
Labels: Ready for Review

#4931 Upsell open chat for team members
  src/views/community/components/communityFeeds.js
  src/views/community/components/openChatUpsell.js
Labels: Ready for Review

#4933 Hotfix community member tab
  shared/graphql/fragments/community/communityMembers.js
  shared/graphql/queries/community/getCommunityMembers.js
  src/views/community/components/membersList.js
Labels: Ready for Review

#4928 Add Divjoy to Web Development category in Explore
  src/views/explore/collections.js
Labels: Ready for Review

#4948 Track websocket connections to datadog
  api/apollo-server.js
Labels: Ready for Review

#4941 Fix edit thread UI
  src/views/thread/container/index.js
Labels: Ready for Review

#4940 Let community team members edit threads
  api/models/thread.js
  api/mutations/thread/editThread.js
  api/queries/thread/editedBy.js
  api/queries/thread/index.js
  api/types/Thread.js
  cypress/integration/thread/action_bar_spec.js
  shared/graphql/fragments/thread/threadInfo.js
  shared/types.js
  src/components/inboxThread/header/threadHeader.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#4950 Add user info tab on mobile
  src/views/user/index.js
Labels: Ready for Review

#4953 Never load watercoolers in lists of threads
  api/models/thread.js
  api/queries/thread/rootThread.js
Labels: Ready for Review

#4955 [API] Temporarily log all POST request paths
  api/routes/middlewares/index.js
Labels: Ready for Review

#4944 Set up GraphQL response caching
  api/apollo-server.js
  api/package.json
  api/types/Channel.js
  api/types/ChannelSlackSettings.js
  api/types/Community.js
  api/types/CommunityMember.js
  api/types/CommunitySlackSettings.js
  api/types/Message.js
  api/types/Meta.js
  api/types/Reaction.js
  api/types/Search.js
  api/types/Thread.js
  api/types/User.js
  api/yarn.lock
  flow-typed/npm/apollo-server-cache-redis_vx.x.x.js
  flow-typed/npm/apollo-server-plugin-response-cache_vx.x.x.js
  package.json
  shared/cache/redis.js
  yarn.lock
Labels: Ready for Review, WIP: Building

#4954 Improve thread headers
  src/components/badges/style.js
  src/components/entities/listItems/style.js
  src/components/entities/listItems/user.js
  src/views/thread/components/stickyHeader.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#4958 Fetch community metadata for user community connection
  cypress/integration/channel/settings/private_invite_link_spec.js
  cypress/integration/thread/action_bar_spec.js
  shared/graphql/fragments/user/userCommunityConnection.js
  shared/graphql/queries/user/getUserCommunityConnection.js
Labels: Ready for Review

#4960 Fix API cache redis prod config
  api/apollo-server.js
Labels: Ready for Review

#4957 Highlight unseen notifications
  src/views/navigation/notificationsTab.js
  src/views/notifications/components/browserNotificationRequest.js
  src/views/notifications/components/communityInviteNotification.js
  src/views/notifications/components/mentionMessageNotification.js
  src/views/notifications/components/mentionThreadNotification.js
  src/views/notifications/components/newChannelNotification.js
  src/views/notifications/components/newReactionNotification.js
  src/views/notifications/components/newThreadNotification.js
  src/views/notifications/components/newThreadReactionNotification.js
  src/views/notifications/components/newUserInCommunityNotification.js
  src/views/notifications/components/privateChannelRequestApprovedNotification.js
  src/views/notifications/components/privateChannelRequestSentNotification.js
  src/views/notifications/components/privateCommunityRequestApprovedNotification.js
  src/views/notifications/components/privateCommunityRequestSentNotification.js
  src/views/notifications/index.js
  src/views/notifications/style.js
Labels: Ready for Review, WIP: Building

#4932 Open threads as modals
  cypress/integration/modal_routes_spec.js
  src/components/composer/index.js
  src/components/inboxThread/index.js
  src/components/message/threadAttachment/attachment.js
  src/components/profile/thread.js
  src/helpers/notifications.js
  src/routes.js
  src/views/communityAnalytics/components/threadListItem.js
  src/views/notifications/utils.js
  src/views/thread/container/index.js
  src/views/thread/style.js
  src/views/threadSlider/index.js
  src/views/threadSlider/style.js
Labels: WIP: Building

#4964 Fix composer tab height
  src/components/composer/index.js
  src/components/composer/inputs.js
Labels: Ready for Review

#4951 Add info tab to channels on mobile
  src/views/channel/index.js
Labels: Ready for Review

#4952 Better thread action bar
  cypress/integration/thread/action_bar_spec.js
  src/components/hoverProfile/style.js
  src/components/hoverProfile/userProfile.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/actionsDropdown.js
  src/views/thread/components/stickyHeader.js
  src/views/thread/style.js
Labels: Ready for Review

#4971 Fix home view redirect
  src/views/homeViewRedirect/index.js
Labels: Ready for Review

#4965 Mini Composer
  api/migrations/20190327134509-delete-bot-messages.js
  api/mutations/thread/publishThread.js
  config-overrides.js
  cypress/integration/channel/view/composer_spec.js
  cypress/integration/composer/localstorage_spec.js
  cypress/integration/composer/mini_spec.js
  cypress/integration/composer/selection_spec.js
  cypress/integration/modal_routes_spec.js
  package.json
  shared/clients/group-messages.js
  src/components/badges/index.js
  src/components/composer/LocationSelectors/ChannelSelector.js
  src/components/composer/index.js
  src/components/composer/inputs.js
  src/components/composer/style.js
  src/components/composerMini/index.js
  src/components/composerMini/style.js
  src/components/entities/profileCards/components/channelActions.js
  src/components/entities/profileCards/components/communityActions.js
  src/components/error/BlueScreen.js
  src/components/error/ErrorBoundary.js
  src/components/error/index.js
  src/components/icon/index.js
  src/components/layout/index.js
  src/components/message/authorByline.js
  src/components/message/editingBody.js
  src/components/modals/CloseComposerConfirmationModal/index.js
  src/components/modals/CloseComposerConfirmationModal/style.js
  src/components/modals/modalContainer.js
  src/components/modals/modalRoot.js
  src/components/modals/styles.js
  src/components/threadFeed/nullState.js
  src/components/titlebar/base.js
  src/helpers/navigation-context.js
  src/helpers/thread-draft-handling.js
  src/routes.js
  src/views/channel/index.js
  src/views/community/components/communityFeeds.js
  src/views/community/components/postsFeeds.js
  src/views/navigation/communityList.js
  src/views/navigation/directMessagesTab.js
  src/views/navigation/globalComposerTab.js
  src/views/navigation/index.js
  src/views/navigation/notificationsTab.js
  src/views/thread/container/index.js
  yarn.lock
Labels: Ready for Review

#4974 3.1.0
  api/migrations/20190327134509-delete-bot-messages.js
  api/mutations/thread/publishThread.js
  api/package.json
  api/yarn.lock
  config-overrides.js
  cypress/integration/channel/view/composer_spec.js
  cypress/integration/composer/localstorage_spec.js
  cypress/integration/composer/mini_spec.js
  cypress/integration/composer/selection_spec.js
  cypress/integration/modal_routes_spec.js
  cypress/integration/thread/action_bar_spec.js
  package.json
  shared/clients/group-messages.js
  src/components/badges/index.js
  src/components/composer/LocationSelectors/ChannelSelector.js
  src/components/composer/index.js
  src/components/composer/inputs.js
  src/components/composer/style.js
  src/components/composerMini/index.js
  src/components/composerMini/style.js
  src/components/entities/profileCards/components/channelActions.js
  src/components/entities/profileCards/components/communityActions.js
  src/components/error/BlueScreen.js
  src/components/error/ErrorBoundary.js
  src/components/error/index.js
  src/components/icon/index.js
  src/components/layout/index.js
  src/components/message/authorByline.js
  src/components/message/editingBody.js
  src/components/modals/CloseComposerConfirmationModal/index.js
  src/components/modals/CloseComposerConfirmationModal/style.js
  src/components/modals/modalContainer.js
  src/components/modals/modalRoot.js
  src/components/modals/styles.js
  src/components/threadFeed/nullState.js
  src/components/titlebar/base.js
  src/helpers/navigation-context.js
  src/helpers/thread-draft-handling.js
  src/routes.js
  src/views/channel/index.js
  src/views/community/components/communityFeeds.js
  src/views/community/components/postsFeeds.js
  src/views/homeViewRedirect/index.js
  src/views/navigation/communityList.js
  src/views/navigation/directMessagesTab.js
  src/views/navigation/globalComposerTab.js
  src/views/navigation/index.js
  src/views/navigation/notificationsTab.js
  src/views/thread/container/index.js
  yarn.lock
Labels: Ready for Review

#4978 Use clientside routing for spectrum urls
  shared/clients/draft-js/links-decorator/index.js
  shared/clients/draft-js/renderer/index.js
  shared/regexps.js
Labels: Ready for Review

#4977 Button loading state audit
  src/components/emailInvitationForm/index.js
  src/components/hoverProfile/channelProfile.js
  src/components/hoverProfile/communityProfile.js
  src/components/message/editingBody.js
  src/components/modals/BanUserModal/index.js
  src/components/modals/ChangeChannelModal/index.js
  src/components/modals/CreateChannelModal/index.js
  src/components/modals/ReportUserModal/index.js
  src/components/modals/RestoreChannelModal/index.js
  src/components/upsell/joinChannel.js
  src/components/userEmailConfirmation/index.js
  src/views/channelSettings/components/channelMembers.js
  src/views/channelSettings/components/editForm.js
  src/views/channelSettings/components/resetJoinToken.js
  src/views/community/containers/privateCommunity.js
  src/views/communityMembers/components/communityMembers.js
  src/views/communityMembers/components/resetJoinToken.js
  src/views/communitySettings/components/brandedLogin.js
  src/views/communitySettings/components/editForm.js
  src/views/communitySettings/components/slack/sendInvitations.js
  src/views/communitySettings/components/watercooler.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/newCommunity/components/editCommunityForm/index.js
  src/views/notifications/index.js
  src/views/thread/components/actionsDropdown.js
  src/views/userSettings/components/deleteAccountForm.js
  src/views/userSettings/components/editForm.js
Labels: Ready for Review

#4976 Fix list item width
  src/components/entities/listItems/style.js
  src/components/settingsViews/style.js
  src/views/communityMembers/components/communityMembers.js
Labels: Ready for Review

#4975 Force inputs to match line heights to prevent awkward expanding
  src/components/chatInput/style.js
  src/components/composer/style.js
  src/components/composerMini/index.js
  src/components/composerMini/style.js
Labels: Ready for Review

#4979 Fix new community onboarding flow
  cypress/integration/channel/settings/edit_spec.js
  shared/graphql/mutations/community/createCommunity.js
  shared/graphql/queries/community/getCommunity.js
  src/views/channelSettings/components/channelMembers.js
  src/views/newCommunity/components/share/index.js
Labels: Ready for Review

#4984 Fix thread subscriptions sending down age-old threads
  api/models/thread.js
Labels: Ready for Review

#4983 Fix unseen robotext jumping around in real-time
  src/components/messageGroup/thread.js
Labels: Ready for Review

#4985 Fix max width of select dropdowns in community settings
  src/views/communitySettings/components/slack/channelSlackManager.js
Labels: Ready for Review

#4980 Quieter emails by default
  src/components/badges/style.js
  src/components/button/style.js
  src/components/entities/listItems/channel.js
  src/components/entities/listItems/style.js
  src/components/icon/index.js
  src/components/menu/index.js
  src/components/message/index.js
  src/components/toggleChannelNotifications/index.js
  src/views/channelSettings/components/editForm.js
  src/views/thread/components/actionsDropdown.js
Labels: Ready for Review

#4987 Break word in mini composer
  src/components/composerMini/style.js
Labels: Ready for Review

#4990 Desktop cleanup
  src/components/titlebar/index.js
  src/views/navigation/index.js
  src/views/navigation/style.js
Labels: Ready for Review

#4989 Mark notifications as seen on click
  src/views/notifications/components/communityInviteNotification.js
  src/views/notifications/components/mentionMessageNotification.js
  src/views/notifications/components/mentionThreadNotification.js
  src/views/notifications/components/newChannelNotification.js
  src/views/notifications/components/newMessageNotification.js
  src/views/notifications/components/newReactionNotification.js
  src/views/notifications/components/newThreadNotification.js
  src/views/notifications/components/newThreadReactionNotification.js
  src/views/notifications/components/newUserInCommunityNotification.js
  src/views/notifications/components/privateChannelRequestApprovedNotification.js
  src/views/notifications/components/privateChannelRequestSentNotification.js
  src/views/notifications/components/privateCommunityRequestApprovedNotification.js
  src/views/notifications/components/privateCommunityRequestSentNotification.js
  src/views/notifications/index.js
Labels: Ready for Review

#4988 Fix dm scroll position when revisiting a thread
  src/views/directMessages/components/messages.js
Labels: Ready for Review

#4992 Fix channel join action in mobile titlebar
  src/components/titlebar/actions.js
Labels: Ready for Review
