Repository withspectrum/spectrum, pull requests merged in 2019-04, with the labels that each got.

#5009 Fix editing first DM messages
  api/mutations/directMessageThread/createDirectMessageThread.js
Labels: Ready for Review

#5008 Optimistically mark notifications as seen
  shared/graphql/mutations/notification/markNotificationsSeen.js
Labels: Ready for Review

#5006 [HOTFIX] Links in thread bodies
  shared/clients/draft-js/renderer/index.js
Labels: Ready for Review

#5010 Add actions dropdown to thread sticky header
  cypress/integration/channel/view/membership_spec.js
  cypress/integration/thread/action_bar_spec.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/actionsDropdown.js
  src/views/thread/components/stickyHeader.js
  src/views/thread/components/threadDetail.js
Labels: Ready for Review

#5007 Hopefully hotfix thread crashes
  shared/clients/draft-js/utils/getStringElements.js
Labels: Ready for Review

#4956 Unified community sidebar
  cypress/integration/channel/settings/edit_spec.js
  cypress/integration/channel/view/membership_spec.js
  cypress/integration/channel/view/notifications_spec.js
  cypress/integration/channel/view/profile_spec.js
  cypress/integration/thread/view_spec.js
  cypress/integration/user/new_user_spec.js
  cypress/integration/user_spec.js
  shared/graphql/fragments/channel/channelInfo.js
  src/components/communitySidebar/index.js
  src/components/entities/listItems/channel.js
  src/components/entities/listItems/style.js
  src/components/layout/index.js
  src/components/toggleChannelNotifications/index.js
  src/views/channel/components/notificationsToggle.js
  src/views/channel/index.js
  src/views/community/components/channelsList.js
  src/views/community/containers/signedIn.js
  src/views/navigation/style.js
  src/views/thread/components/topBottomButtons.js
  src/views/thread/components/trendingThreads.js
  src/views/thread/container/index.js
  src/views/thread/style.js
  src/views/threadSlider/index.js
  src/views/threadSlider/style.js
Labels: Ready for Review, WIP: Building

#5012 Small polish
  cypress/integration/user_spec.js
  src/components/nextPageButton/style.js
  src/views/threadSlider/style.js
Labels: Ready for Review

#5013 3.1.2
  api/mutations/directMessageThread/createDirectMessageThread.js
  athena/package.json
  athena/yarn.lock
  cypress/integration/channel/settings/edit_spec.js
  cypress/integration/channel/view/membership_spec.js
  cypress/integration/channel/view/notifications_spec.js
  cypress/integration/channel/view/profile_spec.js
  cypress/integration/thread/action_bar_spec.js
  cypress/integration/thread/view_spec.js
  cypress/integration/user/new_user_spec.js
  cypress/integration/user_spec.js
  package.json
  shared/clients/draft-js/renderer/index.js
  shared/clients/draft-js/utils/getStringElements.js
  shared/graphql/fragments/channel/channelInfo.js
  shared/graphql/mutations/notification/markNotificationsSeen.js
  src/components/communitySidebar/index.js
  src/components/entities/listItems/channel.js
  src/components/entities/listItems/style.js
  src/components/layout/index.js
  src/components/nextPageButton/style.js
  src/components/toggleChannelNotifications/index.js
  src/views/channel/components/notificationsToggle.js
  src/views/channel/index.js
  src/views/community/components/channelsList.js
  src/views/community/containers/signedIn.js
  src/views/navigation/style.js
  src/views/thread/components/actionBar.js
  src/views/thread/components/actionsDropdown.js
  src/views/thread/components/stickyHeader.js
  src/views/thread/components/threadDetail.js
  src/views/thread/components/topBottomButtons.js
  src/views/thread/components/trendingThreads.js
  src/views/thread/container/index.js
  src/views/thread/style.js
  src/views/threadSlider/index.js
  src/views/threadSlider/style.js
Labels: Ready for Review

#5014 Responsive navigation and better grids on large screens
  cypress/integration/channel/view/membership_spec.js
  cypress/integration/thread/action_bar_spec.js
  src/components/appViewWrapper/style.js
  src/components/entities/profileCards/style.js
  src/components/layout/index.js
  src/views/community/style.js
  src/views/navigation/style.js
  src/views/thread/style.js
  src/views/threadSlider/style.js
Labels: Ready for Review

#5016 Fix websocket connections tracking to datadog
  api/apollo-server.js
Labels: Ready for Review

#5015 Rework hyperion deployment
  api/queries/user/index.js
  api/queries/user/isOnline.js
  config-overrides.js
  hyperion/index.js
  hyperion/renderer/html-template.js
  package.json
  scripts/deploy.js
Labels: Ready for Review

#5017 3.1.3
  api/apollo-server.js
  api/queries/user/index.js
  api/queries/user/isOnline.js
  config-overrides.js
  cypress/integration/channel/view/membership_spec.js
  cypress/integration/thread/action_bar_spec.js
  hyperion/index.js
  hyperion/renderer/html-template.js
  package.json
  scripts/deploy.js
  src/components/appViewWrapper/style.js
  src/components/entities/profileCards/style.js
  src/components/layout/index.js
  src/views/community/style.js
  src/views/navigation/style.js
  src/views/thread/style.js
  src/views/threadSlider/style.js
Labels: Ready for Review

#5024 Fixes + polish
  api/package.json
  shared/generate-meta-info.js
  src/components/composer/index.js
  src/components/entities/profileCards/community.js
  src/components/entities/profileCards/components/communityMeta.js
  src/components/entities/profileCards/style.js
  src/components/titlebar/actions.js
  src/helpers/render-text-with-markdown-links.js
  src/views/channel/index.js
  src/views/channelSettings/index.js
  src/views/communitySettings/index.js
  src/views/directMessages/components/header.js
  src/views/directMessages/components/threadsList.js
  src/views/directMessages/containers/index.js
  src/views/navigation/communityList.js
  src/views/navigation/directMessagesTab.js
  src/views/navigation/globalComposerTab.js
  src/views/navigation/index.js
  src/views/navigation/notificationsTab.js
  src/views/navigation/style.js
  src/views/newCommunity/index.js
  src/views/newDirectMessage/style.js
  src/views/notifications/index.js
  src/views/thread/style.js
  src/views/userSettings/index.js
Labels: Ready for Review

#5034 Fix community name length validation
  src/components/modals/CreateChannelModal/index.js
  src/views/communitySettings/components/editForm.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/newCommunity/components/editCommunityForm/index.js
Labels: Ready for Review

#5036 Truncate sticky header title manually
  src/views/thread/components/stickyHeader.js
Labels: Ready for Review

#5037 3.1.5
  analytics/package.json
  analytics/yarn.lock
  api/package.json
  api/yarn.lock
  desktop/package.json
  desktop/yarn.lock
  package.json
  src/components/modals/CreateChannelModal/index.js
  src/views/communitySettings/components/editForm.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/newCommunity/components/editCommunityForm/index.js
  src/views/thread/components/stickyHeader.js
Labels: Ready for Review

#5042 Move to redis labs
  analytics/package.json
  analytics/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  now.json
  shared/bull/create-redis.js
Labels: Ready for Review

#5052 Connect to both RethinkDB portals in production
  now.json
  shared/db/db.js
Labels: Ready for Review

#5053 3.1.6
  analytics/package.json
  analytics/yarn.lock
  api/package.json
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  now.json
  package.json
  scripts/generate-table-diagram.js
  shared/bull/create-redis.js
  shared/db/db.js
  vulcan/package.json
  vulcan/yarn.lock
Labels: Ready for Review

#5050 Move navigation to community sidebar
  cypress/integration/channel/view/members_spec.js
  cypress/integration/channel/view/profile_spec.js
  cypress/integration/channel/view/search_spec.js
  shared/graphql/fragments/community/communityInfo.js
  src/components/entities/listItems/channel.js
  src/components/entities/profileCards/components/communityMeta.js
  src/views/channel/components/PostsFeed.js
  src/views/channel/index.js
  src/views/community/components/channelsList.js
  src/views/community/components/communityFeeds.js
  src/views/community/containers/signedIn.js
  src/views/community/style.js
Labels: WIP: Building

#5062 Fix thread action bar spec
  cypress/integration/thread/action_bar_spec.js
Labels: Ready for Review

#5065 Use webkit smoothing auto settings
  src/reset.css.js
Labels: Ready for Review

#5064 Delete users messages on ban
  shared/db/queries/user.js
  src/views/newUserOnboarding/index.js
Labels: Ready for Review

#5063 Short term fix for broken chat input in thread modals
  src/components/inboxThread/index.js
Labels: Ready for Review

#5066 3.1.7
  api/package.json
  api/yarn.lock
  chronos/package.json
  chronos/yarn.lock
  cypress/integration/channel/view/members_spec.js
  cypress/integration/channel/view/profile_spec.js
  cypress/integration/channel/view/search_spec.js
  cypress/integration/thread/action_bar_spec.js
  mercury/package.json
  mercury/yarn.lock
  package.json
  shared/db/queries/user.js
  shared/graphql/fragments/community/communityInfo.js
  src/components/entities/listItems/channel.js
  src/components/entities/profileCards/components/communityMeta.js
  src/components/inboxThread/index.js
  src/reset.css.js
  src/views/channel/components/PostsFeed.js
  src/views/channel/index.js
  src/views/community/components/channelsList.js
  src/views/community/components/communityFeeds.js
  src/views/community/containers/signedIn.js
  src/views/community/style.js
  src/views/newUserOnboarding/index.js
  vulcan/package.json
  vulcan/yarn.lock
Labels: Ready for Review
