Repository withspectrum/spectrum, pull requests merged in 2019-01, with the labels that each got.

#4507 Eliminate warning in console due to incorrect html element nesting
  src/components/threadFeed/index.js
  src/components/threadFeed/style.js
Labels: Ready for Review

#4522 Remove unused timeInUTC variable
  src/components/maintenance/index.js
Labels: Ready for Review

#4529 Add missing username property in onValidationResult object
  src/components/usernameSearch/index.js
Labels: Ready for Review

#4532 2.5.6
  analytics/package.json
  analytics/yarn.lock
  api/package.json
  api/routes/auth/google.js
  api/yarn.lock
  athena/package.json
  athena/yarn.lock
  chronos/package.json
  chronos/queues/constants.js
  chronos/queues/digests/getReputationString.js
  chronos/queues/digests/processThreads.js
  chronos/queues/digests/test/__snapshots__/reputation-string.test.js.snap
  chronos/yarn.lock
  cypress/integration/thread/chat_input_spec.js
  cypress/integration/thread_spec.js
  desktop/package.json
  desktop/yarn.lock
  hermes/package.json
  hermes/yarn.lock
  mercury/package.json
  mercury/yarn.lock
  package.json
  shared/bull/create-queue.js
  src/components/maintenance/index.js
  src/components/threadFeed/index.js
  src/components/threadFeed/style.js
  src/components/upsell/joinChannel.js
  src/components/usernameSearch/index.js
  src/views/thread/container.js
  vulcan/package.json
  vulcan/yarn.lock
Labels: Ready for Review

#4536 Add extra checks at send time for valid user recipient
  hermes/send-email.js
  hermes/user-can-receive-email.js
Labels: Ready for Review

#4537 Minor improvements
  admin/src/views/communities/components/search/index.js
  admin/src/views/users/components/search/index.js
  src/components/chatInput/index.js
  src/components/composer/index.js
  src/components/fullscreenView/index.js
  src/components/gallery/browser.js
  src/components/threadComposer/components/composer.js
  src/helpers/keycodes.js
  src/reducers/dashboardFeed.js
  src/views/dashboard/components/threadSearch.js
  src/views/directMessages/containers/newThread.js
  src/views/explore/components/search.js
  src/views/newUserOnboarding/components/communitySearch/index.js
  src/views/threadSlider/index.js
Labels: Ready for Review

#4539 Update `trouble loading thread` message to be more clear
  src/views/thread/container.js
Labels: Ready for Review

#4472 Plaintext markdown chatinput
  api/mutations/message/addMessage.js
  api/mutations/message/editMessage.js
  api/mutations/thread/publishThread.js
  api/package.json
  api/types/Message.js
  api/yarn.lock
  cypress/integration/messages_spec.js
  cypress/integration/thread/chat_input_spec.js
  cypress/integration/thread_spec.js
  flow-typed/npm/draft-js-export-markdown_vx.x.x.js
  package.json
  shared/graphql/mutations/message/sendMessage.js
  src/components/chatInput/components/mediaUploader.js
  src/components/chatInput/index.js
  src/components/chatInput/input.js
  src/components/chatInput/style.js
  src/components/message/editingBody.js
  src/components/message/style.js
  src/components/message/view.js
  src/views/directMessages/containers/existingThread.js
  src/views/directMessages/containers/newThread.js
  src/views/thread/components/threadDetail.js
  src/views/thread/container.js
  yarn.lock
Labels: WIP: Building

#4540 Implement GraphQL Rate Limiting
  api/apollo-server.js
  api/package.json
  api/schema.js
  api/types/Channel.js
  api/types/Community.js
  api/types/DirectMessageThread.js
  api/types/Message.js
  api/types/Thread.js
  api/utils/create-graphql-error-formatter.js
  api/utils/rate-limit-directive.js
  api/yarn.lock
  flow-typed/npm/graphql-rate-limit_vx.x.x.js
  flow-typed/npm/ms_vx.x.x.js
  flow-typed/npm/request-ip_vx.x.x.js
  package.json
  yarn.lock
Labels: Ready for Review, WIP: Building

#4545 Support hyperlinks in messages
  shared/clients/draft-js/message/renderer.web.js
  shared/clients/draft-js/message/types.js
  src/components/chatInput/index.js
Labels: Ready for Review

#4535 add delete cover feature to edit community form
  api/models/community.js
  api/types/Community.js
  src/components/editForm/style.js
  src/views/communitySettings/components/editForm.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/newCommunity/components/createCommunityForm/style.js
Labels: Ready for Review

#4551 Stop submitting message during IME is composing
  src/components/chatInput/index.js
Labels: Ready for Review

#4554 Fix dm chatinput onfocus and onblur handlers
  src/components/chatInput/index.js
  src/views/directMessages/containers/newThread.js
Labels: Ready for Review

#4558 [HOTFIX] Upgrade graphql-rate-limit
  api/package.json
  api/yarn.lock
  package.json
  yarn.lock
Labels: Ready for Review

#4574 Hotfix Android thread creation
  api/mutations/thread/publishThread.js
Labels: Ready for Review

#4576 Fix hyperion memory leak
  hyperion/renderer/index.js
Labels: Ready for Review

#4550 Add mention suggestions to chat input
  flow-typed/npm/react-mentions_vx.x.x.js
  package.json
  src/components/chatInput/index.js
  src/components/chatInput/style.js
  src/components/rich-text-editor/style.js
  src/views/directMessages/containers/existingThread.js
  src/views/thread/components/messages.js
  src/views/thread/container.js
  yarn.lock
Labels: WIP: Building

#4582 Mentions polish
  src/components/chatInput/index.js
  src/components/chatInput/style.js
  src/views/thread/components/messages.js
  src/views/thread/container.js
Labels: Ready for Review

#4583 2.6.3
  package.json
  src/components/chatInput/index.js
  src/components/chatInput/style.js
  src/views/thread/components/messages.js
  src/views/thread/container.js
Labels: Ready for Review

#4585 Properly transform author username suggestion
  src/components/chatInput/index.js
  src/views/directMessages/containers/existingThread.js
  src/views/thread/container.js
Labels: Ready for Review

#4580 Fix login redirects
  api/utils/is-spectrum-url.js
Labels: Ready for Review

#4588 Workaround react-mentions bug with markup option
  src/components/chatInput/index.js
  src/components/chatInput/style.js
  src/components/mentionsInput/index.js
  src/components/mentionsInput/mentionSuggestion.js
  src/components/mentionsInput/style.js
Labels: Ready for Review

#4590 Update draft-js-export-markdown to fix escaped code chars
  package.json
  yarn.lock
Labels: Ready for Review

#4591 2.6.4
  api/package.json
  api/utils/is-spectrum-url.js
  api/yarn.lock
  package.json
  src/components/chatInput/index.js
  src/components/chatInput/style.js
  src/components/mentionsInput/index.js
  src/components/mentionsInput/mentionSuggestion.js
  src/components/mentionsInput/style.js
  src/views/directMessages/containers/existingThread.js
  src/views/thread/container.js
  yarn.lock
Labels: Ready for Review

#4597 Update draft-js-import-markdown to fix link swallowing
  package.json
  yarn.lock
Labels: Ready for Review
