Repository withspectrum/spectrum, pull requests merged in 2019-09, with the labels that each got.

#5248 Fix now remove script
  package.json
  scripts/deploy.js
Labels: Ready for Review

#5246 Media query to fix logo overlap on homepage for 1660px+screens
  src/views/pages/view.js
Labels: Ready for Review

#5244 Fix apps page styling
  src/views/pages/apps/index.js
  src/views/pages/apps/style.js
Labels: Ready for Review

#5242 Add maskable icons
  public/img/apple-icon-192x192-precomposed.png
  public/img/apple-icon-512x512-precomposed.png
  public/manifest.json
Labels: Ready for Review

#5258 Update deps, attempt to fix flaky test
  .circleci/config.yml
  cypress/integration/thread_spec.js
  cypress/integration/user_spec.js
  package.json
  yarn.lock
Labels: Ready for Review

#5271 Removes redundant word on README.md folders structure
  README.md
Labels: Ready for Review

#5270 Fix cache update after message delete
  shared/graphql/mutations/message/deleteMessage.js
Labels: Ready for Review

#5171 fix extra scroll on hover
  src/components/hoverProfile/style.js
  src/components/hoverProfile/userContainer.js
  src/components/layout/index.js
Labels: Ready for Review, WIP: Building

#5272 Investigate flashing ui
  cypress/integration/composer/localstorage_spec.js
  cypress/integration/composer/selection_spec.js
  cypress/integration/user/new_user_spec.js
  package.json
  src/components/avatar/communityAvatar.js
  src/components/hoverProfile/channelContainer.js
  src/components/hoverProfile/communityContainer.js
  src/components/hoverProfile/index.js
  src/components/inboxThread/header/threadHeader.js
  src/components/inboxThread/header/userProfileThreadHeader.js
  src/components/listItems/channel/index.js
  src/components/listItems/index.js
  src/helpers/history.js
  src/helpers/render-text-with-markdown-links.js
  src/views/channel/components/PostsFeed.js
  src/views/channel/index.js
  src/views/community/components/channelsList.js
  src/views/explore/components/communitySearchWrapper.js
  src/views/newCommunity/components/createCommunityForm/index.js
  src/views/thread/components/threadDetail.js
  src/views/thread/container/index.js
  src/views/threadSlider/style.js
  yarn.lock
Labels: WIP: Needs Testing

#5284 Flickering take two
  cypress/integration/modal_routes_spec.js
  src/components/avatar/userAvatar.js
  src/components/chatInput/style.js
  src/components/entities/listItems/channel.js
  src/components/entities/listItems/style.js
  src/components/hoverProfile/style.js
  src/components/inboxThread/index.js
  src/components/message/style.js
  src/views/community/containers/signedIn.js
Labels: Ready for Review

#5286 Globally disable thread modal
  cypress/integration/composer/mini_spec.js
  src/routes.js
Labels: Ready for Review
